# Advancement

## Experience Points (XP)

Experience points are given for monsters defeated, and for other challenges as the GM sees fit. The following table provides XP values for monsters. Where a monster has both a character level and hit dice given, use the larger value as the monster's level. Non-combat challenges may be assigned a level, or a flat XP value assigned, as the GM wishes.

If asterisks appear after the hit dice listing for a monster, each asterisk adds the special ability bonus once; for example, a creature with a hit dice figure of 2** is worth 125 XP.

For monsters with more than 25 hit dice, add 750 XP to the XP Value and 25 XP to the Special Ability Bonus per additional hit die.

NPCs should be treated as monsters of a number of hit dice equivalent to the character's level. Add a special ability bonus for Clerics and Magic-Users if they are able to cast useful spells during the encounter.

After tallying the XP earned in a given adventure, the amount should be divided by the number of adventurers. As described above, each retainer should receive a one-half share; so a group with four player characters and a retainer is counted as having 4½ members. If 2,000 XP are earned by this group, one share is 444 XP, and the retainer receives 222 XP.

No character may advance more than one level due to the experience points from a single adventure. For example, Barthal the Thief is 1st level and has 1,000 XP before going on an adventure; during the adventure, he earns 2,000 more XP (an amazing feat). This would make his total 3,000 XP, and he would be a 3rd level Thief. This is not allowed; instead, he advances to 2,499 XP, one short of the amount required for 3rd level, and starts his next adventure at 2nd level.


<div class="tableFixHead">

| **Monster Hit Dice** | **XP Value** | **Special Ability Bonus** |
|----|----|---|
| less than 1 | 10 | 3 |
| 1 | 25 | 12 |
| 2 | 75 | 25 |
| 3 | 145 | 30 |
| 4 | 240 | 40 |
| 5 | 360 | 45 |
| 6 | 500 | 55 |
| 7 | 670 | 65 |
| 8 | 875 | 70 |
| 9 | 1,075 | 75 |
| 10 | 1,300 | 90 |
| 11 | 1,575 | 95 |
| 12 | 1,875 | 100 |
| 13 | 2,175 | 110 |
| 14 | 2,500 | 115 |
| 15 | 2,850 | 125 |
| 16 | 3,250 | 135 |
| 17 | 3,600 | 145 |
| 18 | 4,000 | 160 |
| 19 | 4,500 | 175 |
| 20 | 5,250 | 200 |
| 21 | 6,000 | 225 |
| 22 | 6,750 | 250 |
| 23 | 7,500 | 275 |
| 24 | 8,250 | 300 |
| 25 | 9,000 | 325 |

: Monster XP values {#tbl-monsterexp}

</div>