# Spells, Alphabetical

<input type="text" id="input" placeholder="Filter Spell">

<div class="spell" data-tag="Animate Dead" id="Animate Dead">

## Animate Dead

Range: 30'

Cleric 4, Magic-User 5

Duration: special

The casting of this spell causes the mortal remains of one or more deceased creatures to arise as animated
skeletons or zombies. Such undead monsters persist until slain, and obey the verbal commands of the caster.
A single casting of this spell may animate a number of hit dice of undead equal to twice the caster's level of ability, and no more. Animated skeletons have hit dice equal to the number the creature had in life; for skeletons of members of player character races, this means one hit die, regardless of the character level of the deceased. Zombies have one more hit die than the creature had in life.

The sort of monsters created depend on the condition of the remains. A reasonably intact corpse may only
arise as a zombie, while similarly intact skeletal remains may only be animated as a skeleton. The caster
chooses which remains are animated when casting the spell, in any case where there are more bodies than the
caster can animate.

No character may normally control more hit dice of undead than 4 times their level, regardless of how
many times this spell is cast. 

</div>
<div class="spell" data-tag="Animate Objects" id="Animate Objects">

## Animate Objects

Range: 100'+10'/level

Cleric 6

Duration: 1 round/level

This spell allows the caster to animate objects that are
normally inanimate, such that they may move and even
appear to be alive. Objects to be animated may not be
in the possession (worn or carried) of any creature, and
must be non-magical in nature. The caster can animate
one object per level, up to a maximum of 25 lbs. per
caster level (i.e. 300 lbs. at 12th level, 325 lbs. at 13th
level, and so on).

Such objects are normally used to attack the enemies of the caster, and the GM must rule on their effectiveness in combat. In general, animated objects attack using the same attack bonus as the caster. Small or lightweight objects do no more than 1d4 damage per hit, while larger and/or heavier objects do 1d6 or 1d8 (at the GM's discretion). As a special case, weapons which are animated do damage using the normal die roll for the type, but only up to a maximum 1d8. Animated objects have a movement rate of 10', and generally must move in contact with the ground (walking, hopping, slithering, or bouncing, however
seems most appropriate to the GM).

</div>
<div class="spell" data-tag="Anti-Magic Shell" id="Anti-Magic Shell">

## Anti-Magic Shell

Range: 10' radius

Magic User 6

Duration: 1 turn/level

Within a 10' radius around the caster, all magic is negated for the full duration of the spell. Magical attacks will not affect the caster, magic items and spells within the radius are suppressed, and the caster cannot perform further magic until the spell has expired.

</div>
<div class="spell" data-tag="Blade Barrier" id="Blade Barrier">

## Blade Barrier

Range: 90'

Cleric 6

Duration: 1 round/level

This spell creates a barrier of flying, spinning, flashing
blades. The caster may choose a barrier up to 20' high
which extends up to 20' long per level of caster, or a
ring-shaped barrier up to 20' high with a radius of up to
5' per each two full caster levels (so 30' at level 12 or
13, 35' at level 14 or 15, and so on).

Should any creature pass through the wall, it suffers
1d6 points of damage per caster level, with a maximum
damage of 15d6. A successful save vs. Death Ray
reduces damage by half.

The caster may choose to conjure the wall in an area
where creatures are already located; if this is done, all
such creatures are harmed as if they passed through the
wall, but a successful save vs. Death Ray in this case
indicates that the creature has avoided all damage by
jumping to one side or the other of the wall as chosen
by the creature.

Any ranged attacks passing through a blade barrier
suffer a penalty of -4 on the attack roll.

</div>
<div class="spell" data-tag="Bless*" id="Bless*">

## Bless*

Range: 50' radius

Cleric 2

Duration: 1 minute/level

This spell gives the caster and their allies within a 50'
radius a bonus of +1 on all attack rolls, morale checks
(for monsters or NPCs allied with the caster), and
saving throws vs. any kind of magical **fear**. Casters of
the 7th or higher level grant a bonus of +2 to attacks
and saves vs. **fear**, but the morale bonus remains +1.

The reverse of **bless** is called **bane**. The caster's
enemies within a 50' radius become fearful and
uncertain, causing them to suffer a penalty of -1 on
attack rolls, morale checks, and saving throws vs. any
kind of magical **fear**. Casters of the 7th or higher level
apply a penalty of -2 to attacks and saves vs. **fear**, but
the morale penalty remains -1.

</div>
<div class="spell" data-tag="Charm Animal" id="Charm Animal">

## Charm Animal

Range: 60'

Cleric 2

Duration: level+1d4 rounds

```{ojs}
// function rolld4() {
//   var randomNumber = Math.floor(Math.random() * 4) + 1;
//   return randomNumber;
// }

import {rolld4} from "./custom.js"

viewof click = Inputs.button("Roll 1d4", {value: 0, reduce: () => rolld4()})
```


1d4 = ${click}

This spell allows the caster to charm one or more animals, in much the same fashion as **charm person**, at a rate of 1 hit die per caster level. The caster may decide which individual animals out of a mixed group are to be affected first; excess hit dice of effect are ignored. No saving throw is allowed, either for normal or giant-sized animals, but creatures of more fantastic nature (as determined by the GM) are allowed a save vs. Spells to resist. When the duration expires, the animals will resume normal activity immediately.

This spell does not grant the caster any special means of communication with the affected animals; if combined with **speak with animals**, this spell becomes significantly more useful.

</div>
<div class="spell" data-tag="Charm Monster" id="Charm Monster">

## Charm Monster

Range: 30'

Magic User 4

Duration: special

This spell functions like **charm person**, except that the effect is not restricted by creature type or size. Undead monsters are unaffected, as are constructs such
as golems and any creature which is functionally
mindless (such as any kind of jelly). This spell can affect 3d6 hit dice of creatures of 3 or fewer hit dice, or one creature of more than 3 hit dice. Saving throws are made just as for **charm person**.

</div>
<div class="spell" data-tag="Charm Person" id="Charm Person">

## Charm Person

Range: 30'

Magic User 1

Duration: special

This spell causes a humanoid (including all character
races as well as creatures such as orcs, goblins, gnolls,
and so on) of 4 hit dice or less to perceive the caster as
a close friend, love interest, or at the very least as its
trusted ally. Normal characters (PC or NPC) may be
affected regardless of level of ability.

A save vs. Spells will negate the effect. If hostilities
have already commenced or the target otherwise feels
threatened by the caster, it receives a bonus of +5 on its
saving throw.

The caster does not directly control the target; rather,
orders must be given verbally, in writing, or by means
of gestures. Obviously, verbal orders will only work if
the target and caster share a spoken language, and the
same limitation applies to written orders. Also note that
the exact perception of the caster by the affected
individual is not under the control of the caster; the GM
should decide how the subject of this spell perceives its
relationship to the caster.

The target receives a new saving throw each day if it
has an Intelligence of 13 or greater, every week if its
Intelligence is 9-12, or every month if its Intelligence is
8 or less; the GM must rule on the equivalent
intelligence of humanoid monsters.

</div>
<div class="spell" data-tag="Clairvoyance" id="Clairvoyance">

## Clairvoyance

Range: 60'

Magic User 3

Duration: 12 turns

This spell enables the caster to see into another area through the eyes of a living creature in that area. The caster must specify the direction and approximate distance, up to a maximum of 60' away. If there is no appropriate creature in that area, the spell fails. No saving throw is allowed, and the target creature is unaware that it is being so used. The caster may choose another subject creature after at least a turn has passed, enabling multiple locations to be viewed. If the subject creature moves out of range, contact is lost, though the caster may be able to choose another target in this case.

</div>
<div class="spell" data-tag="Cloudkill" id="Cloudkill">

## Cloudkill

Range: 100'+10'/level

Magic User 5

Duration: 6 rounds/level

This spell creates a 20'x20'x20' cloud of poison gas which moves at a rate of 10' per round under the control of the caster (so long as he or she concentrates on it). The gas kills outright any creatures of 3 or fewer hit dice or levels it comes in contact with; creatures having 4 or more hit dice or levels must save vs. Poison or die. The cloud persists for the entire duration even if the caster ceases to concentrate upon it.

</div>
<div class="spell" data-tag="Commune" id="Commune">

## Commune

Range: self

Cleric 5

Duration: 1 round/level

This spell puts the caster in contact with his patron deity or an extraplanar servant thereof, who answers one yes-or-no question per caster level. The ritual to cast this spell takes 1 turn to complete. The being contacted may or may not be omniscient, and further, though the being is technically allied with the caster, it may still not answer questions clearly or completely. These details are left to the GM's discretion.

</div>
<div class="spell" data-tag="Confusion" id="Confusion">

## Confusion

Range: 360'

Magic User 4

Duration: 2 rounds+1/level

This spell causes up to 3d6 living creatures within a 30' radius circle around the target point to become confused*,*making them unable to independently determine what they will do. A saving throw vs. Spells is allowed to resist the effect. Roll on the following table on each subject's Initiative number each round to see what the subject does.

```{ojs}

import {confusionTable, highlightTableRow} from "./custom.js"

viewof gemJewel3 = Inputs.button("Roll on Table", {value: 0, reduce: () => highlightTableRow("#confusion-table", confusionTable())})

```

<br>

::: {#confusion-table}

| d10 | Behavior |
|-----|-----|
| 1 | Act Normally |
| 2 | Move toward the caster, and attack if possible |
| 3--5 | Take no action except possibly to babble |
| 6--7 | Move swiftly away from the caster |
| 8--10 | Attack the nearest creature, regardless of whether it is a friend or foe |

:::

If the target cannot perform the action indicated, the
GM should move down the table (going back to the top
if the table runs out) until an action is found that the
target can perform. If a confused creature is attacked, it
returns the attack on its next initiative number (later in
this round or in the next round if it has already acted)
regardless of what is rolled on the table.

</div>
<div class="spell" data-tag="Conjure Elemental" id="Conjure Elemental">

## Conjure Elemental

Range: 240'

Magic User 5

Duration: special

A portal to one of the Elemental Planes of Air, Earth, Fire, or Water is opened, allowing the Magic-User to summon an elemental from that plane. Review the [Elemental](monstersAll.qmd#elemental) entry in the
Monsters section for further details regarding the types available and their statistics. At most one elemental of each type may be summoned by the caster in a given day. Once the elemental appears, it serves the conjurer indefinitely, provided the caster concentrates on nothing but controlling the creature; spell casting, combat, or movement over half the normal rate results in loss of concentration. The conjurer, while in control of an elemental, can dismiss it to its native plane at will (doing so on his or her Initiative if in combat). If the Magic-User loses concentration, control of the summoned Elemental is lost and cannot be regained. The creature then seeks to attack the conjurer and all others in its path. Only **dispel magic** or **dispel evil** will banish the elemental once control has been lost. An elemental may, of course, choose to return to its home plane on its own; such creatures will not choose to remain on the material plane for long.

</div>
<div class="spell" data-tag="Continual Light*" id="Continual Light*">

## Continual Light*

Range: 360'

Cleric 3, Magic-User 2

Duration: 1 year/level

This spell creates a spherical region of light, as bright as full daylight up to a 30' radius, with light of lesser intensity to a radius of 60'. Continual light can be cast on an object, into the air, or at a creature, just as with the **light** spell, up to a maximum range of 360' from the caster. The spell remains in effect for one year per level of the caster.

As with **light**, this spell can be used to blind a creature if cast on its visual organs. Creatures targeted by this spell are allowed a save vs. Death Ray; if the save is made, the spell is cast into the air just behind the target creature. A penalty of -4 is applied to the blinded creature's attack rolls if the saving throw fails.

The reversed spell, **continual darkness**, causes complete absence of light in the area of effect, overpowering normal light sources. Continual darkness may be used to blind in the same way as continual light.

</div>
<div class="spell" data-tag="Create Food" id="Create Food">

## Create Food

Range: 10'

Cleric 5

Duration: permanent

This spell creates food sufficient to feed up to 3 men or
one horse per caster level for one day. This food
remains edible for just a day, but this can be extended
by a day by casting **purify food and water** on it (and
this can be done repeatedly, keeping the food good
indefinitely). Food created by this spell is nourishing
and satisfying, but is rather bland.

</div>
<div class="spell" data-tag="Create Water" id="Create Water">

## Create Water

Range: 10'

Cleric 4

Duration: permanent

This spell creates one gallon of water per caster level. Note that one or more vessels to contain the water must be available at the time of casting. The water created by this spell is just like clean rain water. Note: Water weighs about 8 pounds per gallon, and one cubic foot of water is roughly 8 gallons.

</div>
<div class="spell" data-tag="Cure Blindness*" id="Cure Blindness*">

## Cure Blindness*

Range: touch

Cleric 3

Duration: instantaneous

With this spell the caster can cure a creature suffering
blindness (whether caused by injury or by magic,
including **light** or **continual light**). Blindness caused
by a curse cannot be cured by this spell.

Reversed, this spell becomes **cause blindness**, which
causes a living creature touched to become blind. A
successful melee attack roll is required to touch the
victim, and no Saving Throw is allowed. Blinded
creatures suffer the penalties described in [Deafness and Blindness](combat.qmd#deafness-and-blindness).

</div>
<div class="spell" data-tag="Cure Disease*" id="Cure Disease*">

## Cure Disease*

Range: touch

Cleric 3

Duration: instantaneous

Cure disease cures all diseases and kills all parasites
afflicting the target creature. A magical or otherwise
special disease (as defined by the GM) may be
unaffected by this spell, or may require a caster of a
certain minimum level to cure it. Also note, just
because a disease or parasite is removed does not
mean that the victim cannot be infected anew should
that affliction be encountered again.

The reverse form of this spell, **cause disease**, causes a
living creature touched by the caster to suffer from a
debilitating and potentially deadly disease for the next
1d10 days. A successful melee attack roll is required to
touch the victim, and no Saving Throw is allowed. The
target suffers a -2 penalty to attack rolls, Armor Class
and Saving Throws. While the victim is sick they
cannot benefit from natural healing of damage or
Constitution point losses, nor prepare spells or move at
running speed. At the end of each day in which an
infected character performed any form of exertion (for
example by fighting, traveling, working, or doing
magical research), the character must roll a saving
throw vs. Spells or suffer 1d6 points of damage. Once
the spell duration has elapsed the affected character, if
still alive, is free of the illness and can start healing
damage and recovering lost Constitution points, and
can again prepare spells.

</div>
<div class="spell" data-tag="Cure Light Wounds*" id="Cure Light Wounds*">

## Cure Light Wounds*

Cleric 1

Range: touch

Duration: instantaneous

With this spell the caster heals 1d6+1 hit points of damage by laying his or her hand upon the injured creature.

The reverse form of this spell, **cause light wounds**, causes 1d6+1 damage to the creature affected by it. A successful attack roll is required in this case,  and the spell is wasted if the attack roll fails.

Undead are affected by this spell and its reverse in opposite fashion; they are injured by **cure light wounds** and healed by **cause light wounds**.

</div>
<div class="spell" data-tag="Cure Serious Wounds*" id="Cure Serious Wounds*">

## Cure Serious Wounds*

Cleric 4

Range: touch

Duration: instantaneous

This spell works exactly like **cure light wounds,** save that it heals 2d6 points of damage, plus 1 point per caster level. The reverse, **cause serious wounds**, also works exactly like **cause light wounds**, except that it inflicts 2d6 + 2 points per caster level.

</div>
<div class="spell" data-tag="Darkvision" id="Darkvision">

## Darkvision

Range: touch

Magic User 3

Duration: 1 hour/level

The subject receives [Darkvision](dungeonAdventures.qmd#darkvision) with a range of 60' for the duration of the spell. 

</div>
<div class="spell" data-tag="Death Spell" id="Death Spell">

## Death Spell

Range: 240'

Magic User 6

Duration: instantaneous

This spell will kill 3d12 hit dice or levels of creatures in a 30' radius sphere centered wherever the caster wishes (within the range limit). Excess levels of effectiveness are lost. Each creature affected is allowed to save vs. Death Ray; those that fail the save die immediately. Creatures of 8 or more hit dice or levels are immune to the spell, as are undead monsters, golems, and any other "creature" that is not truly alive.

</div>
<div class="spell" data-tag="Detect Evil*" id="Detect Evil*">

## Detect Evil*

Range: 60'

Cleric 1, Magic-User 2

Duration: 1 round/level

This spell allows the caster to detect evil; specifically, the caster can detect creatures with evil intentions, magic items with evil enchantments, and possibly extraplanar creatures of evil nature. Normal characters, even "bad" characters, cannot be detected by this spell, as only overwhelming evil is detectable. The caster sees the "evil" creatures or objects with a definite glow around them, but the glow cannot be seen by anyone else.

The exact definition of evil is left for the GM to decide. Note that items such as ordinary traps or poisons are not "evil," and thus not detectable by this spell.

Reversed, this spell becomes **detect good**, which works just as described above with respect to detecting "good" enchantments, angelic creatures, and so on.

</div>
<div class="spell" data-tag="Detect Invisible" id="Detect Invisible">

## Detect Invisible

Range: 60'

Magic User 2

Duration: 1 turn/level

By means of this spell the caster is able to see invisible characters, creatures or objects within the given range, seeing them as translucent shapes.

</div>
<div class="spell" data-tag="Detect Magic" id="Detect Magic">

## Detect Magic

Range: 60'

Cleric 1, Magic-User 1

Duration: 2 turns

The caster of this spell is able to detect enchanted or enspelled objects or creatures within the given range by sight, seeing them surrounded by a pale glowing light. Only the caster sees the glow. Invisible creatures or objects are not detected by this spell, but the emanations of the invisibility magic will be seen as an amorphous glowing fog, possibly allowing the caster (only) to attack the invisible creature at an attack penalty of only -2.

</div>
<div class="spell" data-tag="Dimension Door" id="Dimension Door">

## Dimension Door

Range: 10'

Magic User 4

Duration: instantaneous

The caster of this spell instantly transfers himself or herself, or any single target creature within range, to any spot within 200' plus 20' per caster level. The caster or target creature always arrives at exactly the spot desired, whether the caster visualizes the area or states direction and distance. An unwilling target may save vs. Spells to avoid being transported. Anything worn or carried by the caster or target creature will be transported also, including another character or creature if the transportee can lift it. If the target area is within a solid object, the spell fails automatically.

</div>
<div class="spell" data-tag="Disintegrate" id="Disintegrate">

## Disintegrate

Range: 60'

Magic User 6

Duration: instantaneous

This spell causes a green laser-like beam of light to
spring from the caster's pointing finger. Any single
creature or object (up to a 10x10x10 foot cube of
material) will be completely disintegrated. The target is
allowed a save vs. Spells to resist. This spell can target
just one creature per casting, so if the target makes its
save the spell is wasted.

Equipment worn or carried by a disintegrated creature
is not affected, and will naturally fall to the floor as if
dropped.

</div>
<div class="spell" data-tag="Dispel Evil" id="Dispel Evil">

## Dispel Evil

Range: touch

Cleric 5

Duration: 1 round/level

This powerful spell aids the caster in dealing with
creatures from the nether planes, hereafter called "evil
creatures."

First, the caster's Armor Class is improved by 4 points
when attacked by evil creatures; this effect lasts until the
spell ends, whether by expiration of the duration or
through the employment of one of the following effects.

With a successful attack roll the caster can drive an evil
creature back to the nether planes; the caster must of
course be engaged with the creature (i.e. in melee
range). The creature may make a save vs. Spells to
resist. Any successful attack roll by the caster for this
purpose ends the spells effects, whether or not the
creature saves.

Alternately, by touching the affected creature, item, or area, the caster can immediately dispel any one spell or similar magical effect cast by the evil creature. There is no roll for this effect, except if the target is an unwilling creature in which case an attack roll is needed to actually touch it. The only spells which cannot be ended this way are those which are immune to **dispel magic**. Successfully performing the touch ends the spell, regardless of whether or not any evil magic is actually ended.

</div>
<div class="spell" data-tag="Dispel Magic" id="Dispel Magic">

## Dispel Magic

Range: 120'

Cleric 4, Magic-User 3

Duration: instantaneous

The caster can use dispel magic to end ongoing spells that have been cast on a creature or object, or to end ongoing spells (or at least their effects) within a cubic area 20' on a side. The caster must choose whether to dispel magic on a creature or object, or to affect an area.

If dispel magic is targeted at a creature, all spell effects (including ongoing potion effects) may be canceled. If cast upon an area, all such effects within the area may be canceled. Any spell or effect having a caster level equal to or less than the **dispel magic** caster's level is ended automatically. Those created by higher level casters might not be canceled; there is a 5% chance the dispel magic will fail for each level the spell effect exceeds the caster level. For example, a 10^th^ level caster dispelling magic created by a 14^th^ level caster has a 20% chance of failure.

Some spells cannot be ended by dispel magic; this specifically includes any curse, including those created by **bestow curse** (the reverse of **remove curse**) as well as by cursed items.

</div>

<div class="spell" data-tag="Feeblemind*" id="Feeblemind*">

## Feeblemind*

Range: 180'

Magic User 5

Duration: permanent

This spell allows the caster to inflict a terrible curse on a
living creature, reducing both Intelligence and Charisma
to just 1 point each. A saving throw vs. Spells is
allowed to resist this effect, but if the target creature is a
spellcaster a penalty of -4 is applied to the saving throw.

Once feebleminded, the victim of this spell can no
longer cast spells, speak or understand any language, or
indeed communicate at all as their mind can no longer
understand even such simple things as pointing or
beckoning. The victim still knows their friends and
allies and will follow them and try to help or protect
them.

This effect can be removed with a **heal** spell, or with
the reversed form of this spell **restoremind**.

</div>
<div class="spell" data-tag="Find Traps" id="Find Traps">

## Find Traps

Range: 30'

Cleric 2

Duration: 3 turns

This spell permits the caster to detect a variety of traps, both mechanical and magical. When the caster moves within 30' of a trap, he or she will see it glow with a faint greenish-blue aura. The caster is not, however, able to detect certain natural hazards such as quicksand, a sinkhole, or unsafe walls of natural rock. The spell also does not bestow the caster with the knowledge needed to disarm the trap, nor any details about its type or nature.

</div>
<div class="spell" data-tag="Find the Path" id="Find the Path">

## Find the Path

Range: touch

Cleric 6

Duration: 1 turn/level

This spell grants the caster, or another subject the caster
touches, the ability to find the best and shortest route to
a destination selected by the caster. The caster must
have some knowledge about the location; any location
the caster has ever visited can be so located, as well as
locations described to the caster. Even knowing the
name of a location (if it has a name) is enough for this
spell to function.

This spell works as well indoors or even underground
as it does in the outdoors. However, **find the path** works with respect to locations, not objects or creatures. It can only lead someone to a destination that is on the same plane of existence as the caster when cast; this can be very limiting if the caster (and subject if any) is in a closed or pocket universe of some kind.
 
The subject can sense the approximate direction of the
destination, but also knows the best path to get there,
sensing each turning and knowing which paths or
corridors to follow when choices appear (but not
sooner, unfortunately). The spell even overcomes
things such as secret doors, which the subject will sense
and know how to open, and grants the knowledge of
passwords or codes at the correct moments.

Note that the spell will always choose the best path.
For example, if the shortest way requires the use of a
key which the subject does not have, the spell will
choose a different, probably longer way if possible. If
this is not possible, the subject will be led to the locked
door and will understand that they must find a way to
pass through on their own.

The spell ends when the subject arrives at the
destination or when the duration expires, whichever
comes first. If the duration expires before arrival, the
subject may still remember the approximate direction to
the destination but will no longer know the way.

</div>
<div class="spell" data-tag="Fireball" id="Fireball">

## Fireball

Range: 100'+10'/level

Magic User 3

Duration: instantaneous

Casting this spell causes a tiny glowing ember about the
size of a pea to fly forth from the caster's pointing finger,
by which the direction of flight is indicated. The ember
flies as fast as an arrow and explodes into flames filling
a 20' radius sphere when it reaches a distance chosen
by the caster (up to its maximum range), or sooner if it
impacts any solid or liquid surface. Those within the
area of the flames suffer 1d6 points of damage per
caster level, with a saving throw vs. Spells allowed for
half damage.

No roll is normally required when casting this spell, but
if the caster wishes to project the ember through a slit or
other small opening they must roll a missile attack
(without range adjustments) to hit it; failure indicates
the fireball hits an adjacent surface and detonates there.

Combustible objects or substances within the area of
effect will generally catch fire and possibly be destroyed
(as determined by the GM). Metals with low melting
points such as gold, silver, lead, copper, or bronze may
be softened briefly and thus deformed, but the flames
do not persist long enough to actually melt the metal
items unless they are very small (such as a thin gold
neck chain for example).

While the fireball exerts little if any force or pressure
when exploding, it may still destroy weak or flammable
barriers; if such a thing happens (in the determination
of the GM, of course), the fireball completes its
expansion in the space beyond the destroyed barrier.

</div>
<div class="spell" data-tag="Flesh to Stone*" id="Flesh to Stone*">

## Flesh to Stone*

Range: 30'/level

Magic User 6

Duration: permanent

This spell causes a living creature, along with all gear it
wears or carries, to be petrified. This is the same effect
caused by the gaze of a medusa or the touch of a
cockatrice. A saving throw vs. Petrification is allowed to
resist the spell.

The petrified victim becomes dormant; its mind cannot
be contacted in any way, and it is neither properly alive
nor dead. Damage inflicted on its statue-like form will
apply to its fleshy form if it is ever restored; simply
breaking off an arm or leg is probably enough to result
in death due to blood loss. The GM should determine
the effects of any such injury.

The reverse spell, **stone to flesh**, acts as a counterspell for **flesh to stone**, restoring the creature just as it was when it was petrified. It does nothing if applied to stone that is not the result of **flesh to stone** or similar petrification effects (such as a medusa's gaze).

</div>
<div class="spell" data-tag="Floating Disc" id="Floating Disc">

## Floating Disc

Range: 0

Magic User 1

Duration: 5 turns +1/level

The casting of this spell causes an invisible platform of
magical force to appear. It is about the size of a shield,
about 3 feet in diameter and an inch deep at its center.
It can support a maximum of 500 pounds of weight.
(Note that water weighs about 8 pounds per gallon.)
The disc floats level to the ground, at about the height
of the caster's waist. It remains still when within 10' of
the caster, and follows at the caster's movement rate if
they move away from it. The floating disc can be
pushed as needed to position it but will be dispelled if
somehow moved more than 10 feet from the caster.
When the spell duration expires, the disc disappears
from existence and drops whatever was supported to
the surface beneath.

The disc must be loaded so that the items placed upon
it are properly supported, or they will (of course) fall off.
For example, the disc can support just over 62 gallons
of water, but the water must be in a barrel or other
reasonable container that can be placed upon the disc.
Similarly, a pile of loose coins will tend to slip and slide
about, and some will fall off with every step the caster
takes; but a large sack full of coins, properly tied, will
remain stable.

</div>
<div class="spell" data-tag="Fly" id="Fly">

## Fly

Range: touch

Magic User 3

Duration: 1 turn/level

The subject of this spell can fly at a speed equal to his or her normal ground movement rate (as adjusted by encumbrance). The subject can ascend at half speed and descend at double speed, with the same maneuverability as the subject has when moving on the ground. Flying under the effect of this spell requires only as much concentration as walking, so the subject can attack or cast spells normally. The subject of a fly spell can neither charge nor run, nor carry aloft more weight than his or her maximum load.

If the spell duration expires while the subject is still
airborne, the magic fails slowly such that the subject
descends at a rate of 120 feet per round for 1d10
rounds. If the subject reaches the ground in that time
they land safely; if not, the subject falls the rest of the
distance and suffers normal falling damage. However,
if this spell is ended by **dispel magic** or similar outside
forces, the subject falls immediately. For any such fall,
see [Falling Damage](combat.qmd#falling-damage) for details of the
consequences.

</div>
<div class="spell" data-tag="Geas*" id="Geas*">

## Geas*

Range: 5' per level

Magic User 6

Duration: special

By means of this spell the caster compels a living
creature to perform some specific action or services, or
alternately to avoid performing some action. The target
creature must be able to hear and understand the
caster, or it cannot be affected. This spell will
automatically fail if used to compel a creature to engage
in some obviously self-destructive action.

A saving throw vs. Spells will allow an unwilling target
to resist a geas when it is first cast. However, the target
may choose to accept the geas, typically as part of a
bargain with the caster for some service. Once
subjected to this spell the subject must obey the
instructions given by the caster indefinitely, though if
the geas is to perform some action the spell effectively
ends when that action has been completed.

For every 24 hours that the subject chooses not to obey
the geas (or is prevented from obeying it), it suffers a
penalty of -2 to each of its ability scores, up to a
maximum penalty of -8. No ability score can be
reduced to less than 3 by this effect. If the subject
resumes obeying the geas, all such penalties are
removed after 24 hours.

If the task assigned to the subject of this spell is open-
ended or otherwise unable to be completed, the subject
is still compelled to try to perform the task, but the spell
will end in no more than one day per caster level.
Very clever creatures may be able to subvert the
instructions given; the GM must decide on the results of
any such attempts

This spell can be ended by **remove curse** cast by a
character of higher level than the caster of the geas, but
is never affected by **dispel magic**. 

</div>
<div class="spell" data-tag="Growth of Animals" id="Growth of Animals">

## Growth of Animals

Cleric 3

Range: 60'+10'/level

Duration: 1 turn/level

This spell causes an animal to grow to twice its normal size and eight times its normal weight. The affected creature will do double normal damage with all physical attacks, and its existing natural Armor Class increases by 2. The animal's carrying capacity is also doubled. Unfriendly animals may save vs. Spells to resist this spell; normally, domesticated animals will not attempt to resist it, though they may become confused or panicky afterward (at the GM's discretion).

All equipment worn or carried by an animal is similarly enlarged by the spell, though this change has no effect on the magical properties of any such equipment. Any enlarged item that leaves the enlarged creature's possession instantly returns to its normal size.

The spell gives no means of command or influence over the enlarged animals.

</div>
<div class="spell" data-tag="Growth of Plants*" id="Growth of Plants*">

## Growth of Plants*

Range: 120'

Magic User 4

Duration: permanent

This spell causes normal vegetation of any sort within
range to become thick and overgrown. The area of
effect is determined by the caster, but cannot exceed
1,000 square feet (a 10'x100' area or equivalent) per 5
caster levels. The plants become densely entangled,
and characters or creatures wishing to move through
must hack or force their way through it. All movement
within the affected area is reduced to no more than 5’
per round for less than giant sized creatures; giant sized
creatures are reduced to half normal movement rate.

This spell cannot take effect in an area that does not
already have some plants present. Any sort of
animated plant creature affected by this spell is allowed
a saving throw vs. Spells to resist, but if this save fails it
is affected as with **growth of animals** above.

The reverse form, **shrink plants**, may be used to
render overgrown areas passable. The area of effect is
identical to the normal version. Animated plant
creatures are normally unaffected by this spell, but if
such creatures have already been enlarged by **growth of plants** this spell will reverse the effect. In the latter
case, a saving throw vs. Spells is allowed to resist.

Both forms of this spell are permanent until countered,
either by the reverse of the spell or by **dispel magic**.

</div>
<div class="spell" data-tag="Hallucinatory Terrain" id="Hallucinatory Terrain">

## Hallucinatory Terrain

Magic User 4

Range: 400'+40'/level

Duration: 12 turns/level

This spell makes one 10 yard cube per level of outdoor terrain appear like a different type (i.e. field into forest, grassland into desert, or the like). This spell requires a full turn to cast.

The affected terrain looks, sounds, and smells like another sort of natural terrain. Structures, equipment, and creatures within the area are not hidden or changed in appearance. A save vs. Spells is allowed to see through the illusion, but only if the creatures or characters affected actively attempt to do so.

</div>
<div class="spell" data-tag="Haste*" id="Haste*">

## Haste*

Range: 30'+10'/level

Magic User 3

Duration: 1 round/level

This spell accelerates the actions of 1 creature per caster
level. The affected creatures move and act twice as fast
as normal, having double their normal movement rates
and making twice the normal attacks per round, for the
duration of the spell. Spellcasting is not accelerated,
nor is the use of magic items such as wands, which may
still be used just once per round. Multiple haste or
speed effects don’t combine; only apply the most
powerful or longest lasting effect.

In combat, the subject of this spell performs a full round
of actions (movement followed by attacking) on their
normal Initiative; after all combatants have acted, the
subject may perform another round of actions as
before. If two or more combatants are under the effect
of this spell, use the same Initiative numbers to
determine the order of their actions in each of their
"extra" rounds.

Reversed, haste becomes **slow**; affected creatures move at half speed, attacking half as often (generally, every other round) and making half a normal move each round. Naturally, target creatures may save vs. Spells to avoid the effect. Haste and slow counter and dispel each other.

</div>
<div class="spell" data-tag="Heal*" id="Heal*">

## Heal*

Range: touch

Cleric 6

Duration: permanent

This spell enables the caster to almost totally cure
wounds, diseases, and other afflictions of a single living
creature. With a touch the caster cures blindness,
deafness, **confusion**, disease, **feeblemind**, choking,
nausea, and poison. All but 1d4 hit points are restored
to the subject, if it has any injuries. Ability points losses
are fully restored, if and only if those losses would be
recoverable without this spell; permanent losses to
ability scores are not recovered. Energy drain is also
not affected by this spell.

The reversed spell, **harm**, injures the creature touched so horribly that it is left with only 1d4 hit points. The caster must succeed at a normal attack roll in this case; failure means the spell is wasted. Note that, if the victim has fewer hit points remaining than the number rolled, he or she will take at least one point of damage (and this is the only case in which **harm** may kill a creature).

Generally, both **heal** and** harm** only affect living creatures. If used against an undead creature, heal instead acts like harm; likewise, harm affects undead like heal. Constructs such as golems are unaffected by either spell.

</div>
<div class="spell" data-tag="Hold Monster" id="Hold Monster">

## Hold Monster

Range: 180'

Magic User 5

Duration: 2d8 turns

This spell functions like **hold person**, except that it affects any living creature that fails its save vs. Spells.

</div>
<div class="spell" data-tag="Hold Person" id="Hold Person">

## Hold Person

Range: 180'

Cleric 2, Magic-User 3

Duration: 2d8 turns

This spell will render any living (not undead) humanoid
creature (as defined in **charm person**) paralyzed.
Creatures larger than ogres will not be affected by this
spell. Targets of the spell are conscious and able to
breathe, but cannot move, act, or speak in any way. A
successful save vs. Spells is allowed to resist the effect.
The spell may be cast at a single person, who makes
their save at -2, or at a group, in which case 1d4 of the
creatures in the group may be affected.

A paralyzed swimmer can’t swim and may drown. A
character who has somehow gained wings and is then
paralyzed while airborne will not be able to move its
wings to fly and will thus fall.

</div>
<div class="spell" data-tag="Hold Portal" id="Hold Portal">

## Hold Portal

Range: 100'+10'/level

Magic User 1

Duration: 1 round/level

This spell secures a portal such as a door, gate,
window, or shutter made of normal non-magical
building materials; the portal behaves as if securely
locked for the duration of the spell. The door may be
opened early only by means of **knock** or a successful
casting of **dispel magic**, or by literally destroying the
door (which may well require more time than the
duration of this spell allows).

</div>
<div class="spell" data-tag="Ice Storm" id="Ice Storm">

## Ice Storm

Range: 300'+30'/level

Magic User 4

Duration: 1 round

This spell causes a powerful storm of sleet and hail to
fall in a 20' radius around the target spot for a full
round. This effect causes 5d6 points of damage to
every creature within the area, with a save vs. Spells
allowed to reduce damage by half. The ice storm fills a
vertical volume of 40', so creatures higher than that
distance above the target spot are unaffected. Any
creature naturally resistant to cold takes half damage (or
one-quarter damage if it makes its save).

Visibility within the storm is very poor, such that most
creatures will attack with a penalty of -2 on the attack
roll. Walking movement is reduced to half speed, and
running is not possible within the storm; anyone who
tries will fall down and be forced to remain on the
ground until the spell ends. Flying is likewise
impossible, and any flying creature within the area will
be driven to the ground. A penalty of -20% is applied
to any Listen rolls made by those in the storm's area.

When the spell ends, the hail and ice deposited by the
storm disappears as if it had never existed.

</div>
<div class="spell" data-tag="Insect Plague" id="Insect Plague">

## Insect Plague

Range: 300'+30'/level

Cleric 5

Duration: 1 round/level

This spell summons one swarm of locusts per three caster levels, to a maximum of six swarms at 18^th^ level. See [Insect Swarm](monstersAll.qmd#insect-swarm) in the **Monsters** section for the effects of a swarm. As explained there, a normal swarm of insects occupies a contiguous area equal to three 10 foot cubes; all swarms summoned by this spell must be contiguous with each other such that they effectively form a single huge swarm, though the caster may stretch them out in a line, form them into a block, or indeed arrange them in some serpentine form if desired.

The summoned swarms persist for the duration above,
or until they are slain, whichever comes first. The
caster may summon them in areas where creatures are
already located. Once summoned, the swarms are
stationary until they disappear or are slain, and they
attack any creatures who are within their area.

</div>
<div class="spell" data-tag="Invisibility" id="Invisibility">

## Invisibility

Range: touch

Magic User 2

Duration: special

This spell causes the creature touched (who may be the
caster) to become invisible, undetectable by normal
vision or Darkvision. Invisible creatures may be
detected by those with non-visual sensory abilities.

All items worn or carried by the target when the spell is
cast become invisible as well. If the target lays down an invisible item, it instantly becomes visible again; on the  other hand, items picked up do not automatically  become invisible. If the target places a visible item entirely inside its invisible clothing, backpack, pouch, or other container so that if the target were visible the item could not be seen, it will become invisible just as if it
were held when the spell was cast.

Note that casting this spell upon another makes the
target invisible to the caster as well as everyone else. A
party of invisible characters will likely experience
problems with running into or tripping over each other.
The spell lasts at most 24 hours if not ended sooner. It
ends instantly if the target attacks an opponent or casts
any spell. Other actions do not normally end the spell.
The target may end the spell at will.

Objects that shed light may be made invisible but the
light itself will remain visible, and the source of that light
(and the character carrying it) can thus be discovered.
Rain, dust, paint, and any other visible substance
thrown or applied to an invisible creature will also
render it detectable.

</div>
<div class="spell" data-tag="Invisibility 10' Radius" id="Invisibility 10' Radius">

## Invisibility 10' Radius

Magic User 3

Range: touch

Duration: 1 turn/level

The target of this spell becomes invisible just as with
**invisibility**, but in addition all other creatures within 10
feet of the target at the time of casting (referred to as
members of the group) also become invisible. Unlike
with normal invisibility, all members can see each other
and themselves normally.

If any member negates the effect by attacking or casting
a spell, it becomes visible but all other members remain
invisible. However, if the original subject takes an
action that negates the invisibility, it ends for the entire
group. If a member negates its own invisibility, that
member will no longer be able to see the still-invisible
group members. Moving further than 10 feet from the
target also causes a group member to become visible;
returning to the area does not reinstate the invisibility.

</div>
<div class="spell" data-tag="Invisible Stalker" id="Invisible Stalker">

## Invisible Stalker

Range: 0

Magic User 6

Duration: special

The caster summons an **invisible stalker** to do his or her bidding (see the [Monsters](monstersAll.qmd#invisible-stalker) section, below, for details). The spell persists until **dispel evil** is cast on the creature, it is slain, or the task is fulfilled. The GM is advised to review the monster entry for the invisible stalker when this spell is used, as they may not always be reliable servants.

</div>
<div class="spell" data-tag="Knock" id="Knock">

## Knock

Range: 30'

Magic User 2

Duration: special

The knock spell opens stuck, barred, locked, **held**, or **wizard locked** doors. It opens secret doors, as well as locked or trick-opening boxes or chests. It also loosens welds, shackles, or chains (provided they serve to hold shut something which can be opened). If used to open a **wizard locked** door, the spell does not remove the **wizard lock** but simply suspends its functioning for one turn. In all other cases, the door does not relock itself or become stuck again on its own. Knock will not raise a portcullis or operate any other similar mechanism, nor will it affect ropes, vines, and the like. 

Each casting undoes a single method of securing the
door or item, so that for example a door which is both
locked and stuck can be unlocked but will still be stuck;
a second casting of knock will open such a door.

</div>
<div class="spell" data-tag="Levitate" id="Levitate">

## Levitate

Range: touch

Magic User 2

Duration: 1 turn/level

When this spell is cast, the caster or any one creature or
object they touch begins to levitate. Levitation allows
the caster to cause the subject to rise or fall at a rate of
as much as 20 feet per round.

If a target creature is unwilling, the caster must roll a
successful attack roll in order to touch the target, and
even if this roll succeeds the target is allowed a save vs.
Spells to resist the magic. Likewise, if the target is an
object being held by an unwilling creature, a similar
attack roll and saving throw will be required.
Unattended objects are automatically affected when
touched.

The caster controls the levitating subject mentally. If
the caster ceases to control the subject, it remains at its
current altitude until the spell ends, at which point it
falls.

Levitation does not provide any means of horizontal
movement, but neither is the levitated subject fixed in
place. It can be moved by pushing or by towing with a
rope, for example. A creature being levitated can pull
itself along a cliff face or across a ceiling, or pull itself
with a rope fixed to a solid object. Movement of this
sort is usually at half normal walking speed. The
subject cannot, however, change its own altitude.

If a levitating creature attempts to attack with most
weapons it will find that it is unstable. The first such
attack is made at a penalty of -1 on the attack roll, and
this penalty worsens by an additional -1 each round to
a maximum penalty of -5. Should the creature refrain
from making an attack for a full round, it is reduced to
the -1 penalty level on the next round. This does not
usually affect spellcasting while levitated, however.

</div>
<div class="spell" data-tag="Light*" id="Light*">

## Light*

Range: 120'

Cleric 1, Magic-User 1

Duration: 6 turns + 1/level

This spell creates a light equal to torchlight which illuminates a 30' radius area (and provides dim light for an additional 20') around the target location or object. The effect is immobile if cast into an area, but it can be cast on a movable object. Light taken into an area of magical darkness does not function.

Reversed, **light** becomes **darkness**, creating an area of darkness just as described above. This darkness blocks out Darkvision and negates mundane light sources.

A light spell may be cast to counter and dispel the darkness spell of an equal or lower level caster (and vice versa). Doing so causes both spells to instantly cease, restoring the existing ambient light level.

Either version of this spell may be used to blind an opponent by means of casting it on the target's ocular organs. The target is allowed a saving throw vs. Death Ray to avoid the effect, and if the save is made, the spell does not take effect at all. A **light** or **darkness** spell cast to blind does not have the given area of effect (that is, no light or darkness is shed around the victim).

</div>
<div class="spell" data-tag="Lightning Bolt" id="Lightning Bolt">

## Lightning Bolt

Range: 100' + 10'/level

Magic User 3

Duration: instantaneous

Casting this spell causes a bright thin spark about the
thickness of a string to fly forth from the caster's
pointing finger, which indicates the direction. The spark
stretches as fast as an arrow's flight until it reaches the
caster's chosen distance (but not more than the range
given above) or strikes a solid or liquid surface, at which
point it explodes into a full-fledged bolt of lightning
extending another 60 feet further. The lightning bolt
passes through an area 5 feet wide, arcing and jumping,
so that while it is not actually 5 feet wide, for game
purposes it is treated as if it were.

Those within the area of the lightning bolt suffer 1d6
points of damage per caster level, with a saving throw
vs. Spells allowed for half damage.

If a lightning bolt is targeted at a body of water it
explodes at the point of impact, as described above, but
within the water volume struck it expands like a fireball
to a maximum radius of 20 feet instead of performing
as it does in the air. If a lightning bolt is cast
underwater it explodes in the same way, but at the tip
of the caster's outstretched finger.

The lightning bolt sets fire to combustibles and damages
objects in its path. It can damage metals with a low
melting point; metals such as gold, silver, lead, copper,
or bronze may be softened briefly and thus deformed,
but the lightning does not persist long enough to
actually melt the metal items unless they are very small
(such as a thin gold neck chain for example).

If the damage caused to an interposing barrier shatters
or breaks through it, the bolt may continue beyond the
barrier if the spell’s range permits; otherwise, it may
reflect from the barrier back toward the caster, or in a
random direction at the GM's option. Creatures already
affected by the lightning bolt do not take additional
damage if struck by the reflection of the same bolt.

</div>
<div class="spell" data-tag="Locate Object" id="Locate Object">

## Locate Object

Range: 360'

Cleric 3, Magic-User 2

Duration: 1 round/level

This spell grants the caster knowledge of the location of
an object. The caster must know the object well or be
able to clearly imagine it. (Viewing an accurate drawing
or painting will suffice for the latter option.) A general
item can be located; if more than one such item is in
range, the spell will lead the caster to the nearest one.

Unique or unusual items can only be located if the
caster has first-hand knowledge (not merely through
divination such as **clairvoyance** or a **crystal ball**). The
spell cannot be used to locate creatures of any sort. A
layer of lead or gold no thicker than foil surrounding the
item will prevent it from being located.

</div>
<div class="spell" data-tag="Lower Water" id="Lower Water">

## Lower Water

Range: 20'/level

Magic User 6

Duration: 1 turn/level

Using this spell the caster lowers the level of the water
in a river, a lake, or even the sea by up to 2 feet per
caster level for the given duration, but to no less than 1
inch deep. The spell affects an area with radius of at
most 10 feet per level centered on the caster's chosen
location (within the range given).

There will be a steep slope up to the surface of any area
of un-lowered water that falls outside the spell's radius.
Ships which were already in the area of effect as well as
any that dare to enter it will be unable to climb the
slope and thus unable to leave the area (if not outright
beached by the spell in the first place).

This spell has the effect of **slow** (the reverse of **haste**)
when cast upon water elementals and other creatures
formed from water; a save vs. Spells is allowed, with
success negating the effect. It cannot be cast upon any
other kind of creatures.

</div>
<div class="spell" data-tag="Magic Jar" id="Magic Jar">

## Magic Jar

Range: 60'

Magic User 5

Duration: special

This spell allows the caster to attempt to possess the
body of another living creature. The caster begins by
placing their spirit into a gem, jewel, or large crystal of
some sort within the spell range, called the magic jar.
The caster needs to know where the magic jar is
located, but does not have to be able to see it. While
the caster's spirit is outside their body, that body
appears to all intents and purposes to be dead, but
does not undergo decay as a normal dead body would.

Each round after entering the magic jar the caster's spirit
can attempt to take control of the body of a living
creature within the spell range; the target is allowed a
save vs. Spells to resist. If the saving throw fails, the
spirit of the target (now called the host) is trapped in the
magic jar and the caster's spirit takes possession of the
host's body. Possession of a creature by means of this
spell is blocked by **protection from evil** or a similar
ward.

If the attempt to possess a victim fails, the caster's spirit
remains in the magic jar, and that target creature is
immune to further attempts for the duration of the spell.
The caster may make an attempt to possess another
target on the following round, if desired.

If on the other hand the possession attempt is
successful, the caster may remain in control of the host's
body for as long as desired. The caster's spirit may
return to the magic jar at any time when it is within spell
range, restoring the host's spirit to its own body. The
caster may not return to the same host's body again for
the remainder of the duration of this spell, but may
attempt to possess it again on a subsequent casting.

Whenever the caster's spirit is in the magic jar, it may
choose to return to its own body if it is within spell
range. If the body is not in range, the caster's spirit may
become trapped if no vulnerable creatures are in range.

Whenever the caster's spirit returns to their own body,
the spell ends. There is a 50% chance that the magic
jar will shatter when the spell ends (if the spell did not
end because it was broken), becoming worthless and
unusable.

When the caster's spirit possesses a host, the caster has
access to the physical abilities of the host's body,
including Strength, Dexterity, and Constitution, while
still retaining their own Intelligence, Wisdom, and
Charisma. The caster has access only to their own
knowledge, class and level, attack bonus, saving
throws, spell casting ability, and any other purely
mental capabilities.

The caster does not gain access to supernatural or
otherwise extraordinary powers of the host, and may
not be able to perform physical actions that the caster
has never done before (such as flying, if a winged body
has been possessed). The caster does have access to
the host's sensory capabilities, such as Darkvision, the
enhanced sense of smell of a dog, and so on

If the caster's spirit is in the magic jar, and the jar is
broken (whether by **dispel magic** or physical damage),
the caster's spirit will return to its own body if it is in
spell range; if not, the caster's spirit departs (i.e. the
caster dies). In either case, the spell ends.

If the caster's spirit is driven from the host body by
dispel evil, and the magic jar is in range of the host
body, the caster's spirit returns to the jar and the host's
spirit returns to its body. The caster will not be able to
possess the same host again for the remaining duration
of the spell. If the magic jar is not in range of the host
body, the caster's spirit departs, the host's spirit is freed
from the jar and also departs, and the host's body dies.

If the host's spirit is in the magic jar, and the jar is
broken while in spell range of the host body, the
caster's spirit departs, the host's spirit returns to its body,
and the spell ends. If the jar is broken while out of
range of the host's body, the host's spirit departs, the
caster's spirit is stranded in the host body. Note here
that the spell has not ended. **Dispel evil** can still be
used to drive the caster's spirit from the body, which
departs as noted, ending the spell. A stranded caster
may use another casting of this spell (with another
magic jar, of course) to return to their own body, which
of course kills the host's body.

</div>
<div class="spell" data-tag="Magic Missile" id="Magic Missile">

## Magic Missile

Range: 100'+10'/level

Magic User 1

Duration: instantaneous

This spell causes a missile of magical energy to dart forth from the caster's fingertip and strike its target, which must be at least partially visible to the caster, dealing 1d6+1 points of damage. The missile strikes unerringly. Specific parts of a creature can't be singled out. Inanimate objects are not damaged by the spell.

For every three caster levels beyond 1^st^, an additional missile is fired -- two at 4^th^ level, three at 7^th^, four at 10^th^, and the maximum of five missiles at 13^th^ level or higher. If the caster fires multiple missiles, he or she can target a single creature or several creatures. A single missile can strike only one creature. Targets must be designated before damage is rolled.

</div>
<div class="spell" data-tag="Magic Mouth" id="Magic Mouth">

## Magic Mouth

Range: 30'

Magic User 1

Duration: special

This spell places a simple form of programmed illusion
on a non-living object within range. When triggered,
the spell causes the illusion of a mouth to appear on the
object and a message to be said aloud. The
enchantment can remain in place indefinitely, but is
expended when triggered (i.e. the message is normally
delivered only once).

The message recounted may be up to three words per
caster level in length. The caster may insert pauses in
the message, but the entire message must be delivered
in a time period of no more than a turn. The voice of
the spell can be made to speak at any volume
attainable by a normal human. It will sound enough
like the caster's own voice to be recognized by a close
associate of the caster, but not identical.

The illusionary mouth moves as if actually speaking the
message being delivered, and remains visible during
pauses. If placed on an artistic depiction of a creature
with a mouth (such as a painting or statue), the spell
can be made to appear to animate the mouth of the
object.

This spell cannot be used to activate magic items which
have command words, nor to activate any other
magical effects.

The caster must choose the conditions under which this
spell is triggered. The conditions may be as
complicated or simple as desired, but must depend only
on sight and hearing; the spell has no other sensory
capabilities. The spell also has no particular
intelligence, and can be fooled by disguises or illusions.
The spell does have the capability to effectively see in
normal darkness, but not in any sort of magical
darkness, and it cannot detect invisible creatures nor
see through doors, walls, or even opaque curtains.
Likewise, stealth or magical silence are effective in
preventing audible triggers. Finally, the spell cannot
detect a character's class, level, ability scores, or any
other feature not obvious to a normal NPC.

Triggers have an effective sensory range of 10 feet per
caster level; sounds, sights, or actions outside that range
will never trigger the spell.

</div>
<div class="spell" data-tag="Massmorph" id="Massmorph">

## Massmorph

Range: 100'+10'/level

Magic User 4

Duration: 1 hour/level

With this spell the caster causes 1d4+1 man-sized (or smaller) creatures per four caster levels to appear as if they are natural effects of the terrain (for example, trees in a forest, stalagmites in a cave, coral underwater, boulders in a cavern, etc.). All creatures to be affected must be within a 120' radius of the caster at the time the spell is cast. Only those creatures the caster wishes to hide are affected, and then only if they are willing to be concealed. The caster may include himself or herself among the affected creatures.

Those affected are thus concealed from other creatures passing through the area for so long as they remain still. If an affected creature chooses to move or attack, the illusion is dispelled for that creature, but those who remain still continue to be hidden. The caster may end the spell early if he or she wishes by speaking a single word. The illusion can also be ended by **dispel magic**.

</div>

<div class="spell" data-tag="Mind Control" id="Mind Control">

## Mind Control

Range: 60'

Magic User 2

Duration: 1 turn/level

This spell, sometimes incorrectly called **ESP**, permits
the caster to hear (and possibly see, if the target
visualizes anything) the surface thoughts of one or more
living creatures within range. The caster must designate
a direction or select a visible target, and then
concentrate for a turn in order to "hear" the thoughts.
Each turn the caster may choose to "listen" in a different
direction. The caster may stop listening, then resume
again later, so long as the duration has not expired.
The target creature is not normally aware of being spied
upon in this way, though any creature already under
the effect of this spell or any similar form of telepathy
will instantly know and be able to sense the direction of
the caster.

Rock more than 2 inches thick or even a very thin
covering of lead or gold will block the spell. All undead
creatures are immune to this effect, as are mindless
creatures and constructs such as golems.

</div>

<div class="spell" data-tag="Mirror Image" id="Mirror Image">

## Mirror Image

Range: self

Magic User 2

Duration: 1 turn/level

This spell allows the caster to create multiple illusory
duplicates (called figments) which seem to swirl and
move around and through each other as well as the
caster more or less constantly, making it impossible for
most creatures to determine which is the real one. A
total of 1d4 images plus one image per three caster
levels (maximum eight images total) are created.

The figments mimic the caster's actions, going through
the motions of casting spells, drinking potions,
levitating, and so on, just as the caster does. Figments
always look exactly like the caster.

Any opponent who attacks or casts spells directly on the
caster will always hit a figment instead. Attacking a
figment destroys it, whether or not the attack roll is
successful, as does any attack spell directed at one.
Area-effect spells are not cast directly on the caster, and
thus appear to affect all figments exactly as they affect
the caster; for instance, if the caster is subjected to a
**fireball**, all figments will appear to be injured just as the
caster was

</div>
<div class="spell" data-tag="Neutralize Poison*" id="Neutralize Poison*">

## Neutralize Poison*

Range: touch

Cleric 4

Duration: instantaneous

This spell detoxifies any sort of venom in the creature or object touched. A poisoned creature suffers no additional effects from the poison; if cast upon a creature slain by poison in the last 10 rounds, the creature is revived with 1 hit point. If cast upon a poisonous object (weapon, trap, etc.) the poison is rendered permanently ineffective.

Reversed, this spell becomes **poison**. The caster must make a successful attack roll; if the attack is a success, the target must save vs. Poison or die. The caster's touch remains poisonous for 1 round per level of ability, or until discharged (i.e. only one creature can be affected by the reversed spell).

</div>
<div class="spell" data-tag="Passwall" id="Passwall">

## Passwall

Range: 30'

Magic User 5

Duration: 3 turns

Passwall creates a passage through wooden, plaster, or stone walls, but not through metal or other harder materials. The passage is up to 10 feet deep plus an additional 10 feet deep per three caster levels above 9^th^ (20 feet at 12^th^, 30 feet deep at 15^th^, 40 feet deep at 18^th^). If the wall's thickness is more than the depth of the passage created, then a single passwall simply makes a niche or short tunnel. Several passwall spells can then form a continuing passage to breach very thick walls. When passwall ends (due to duration, **dispel magic**, or caster's choice), creatures within the passage are ejected out the nearest exit.

</div>
<div class="spell" data-tag="Phantasmal Force" id="Phantasmal Force">

## Phantasmal Force

Range: 180'

Magic User 2

Duration: concentration

This spell creates the visual illusion of an object, creature (or small group of creatures), or other effect, as visualized by the caster up to a maximum size of 20'x20'x20'. The illusion does not create sound, smell, texture, or temperature. The caster can animate the image within the limits of the area of effect. The image persists so long as the caster concentrates upon it.

If used to create the illusion of one or more creatures, they will have an Armor Class of 11 and will disappear if hit in combat. Damage done by monsters, spells, etc. simulated by this spell is not real; those "killed" or otherwise apparently disabled will wake up uninjured (at least from this spell) after 2d8 rounds. The illusory damage done will be equivalent to the normal damage for any attack form simulated.

Attempting to animate more creatures than the caster's level grants viewing creatures with at least average Intelligence an immediate save vs. Spells to recognize the creatures as illusions; those making the save will be unaffected by any actions taken by the illusions from that point on. A similar save may be granted by the GM any time he or she feels the illusion is likely to be seen through, especially if the player describes an illusion which seems improbable or otherwise poorly conceived.

</div>
<div class="spell" data-tag="Polymorph Other" id="Polymorph Other">

## Polymorph Other

Range: 30'

Magic User 4

Duration: permanent

This spell allows the caster to change one target into another form of living creature. The assumed form can't have more hit dice than caster's level, or be incorporeal or gaseous. Unlike **polymorph self**, the transformed target also gains the behavioral and mental traits, any physical attacks, special, supernatural or spell-like abilities of the new form, in addition to the physical capabilities and statistics of such. If the new form is substantially less intelligent, the target may not remember its former life.

The target creature will have the same number of hit points it previously had, regardless of the hit dice of the form assumed. Incorporeal or gaseous creatures are immune to this spell, as noted above. A creature with shape changing abilities such as a doppleganger can revert to its natural form after one round.

Equipment worn or carried will be dropped if the new
form is unable to wear or carry the items. If any such
items would be constricting or physically harmful to the
new form, the transformation slows and alters such that
they are dropped without damage to the items nor
harm to the target creature. If the GM determines that
any items cannot be removed in this way, they must
decide on the exact results.

Unwilling targets that successfully save against Polymorph are not affected. The spell is permanent until dispelled or the creature is slain, at which time the target reverts to his or her original form.

</div>
<div class="spell" data-tag="Polymorph Self" id="Polymorph Self">

## Polymorph Self

Range: self

Magic User 4

Duration: 1 hour/level

This spell allows the caster to change into a different
form of living creature. The form assumed may not
have more hit dice than the caster has levels, nor be
incorporeal or gaseous.

The caster assumes the physical nature of the assumed
form while retaining their mental and spiritual
characteristics. They gain the Armor Class and all
physical attacks possessed by the form but does not
gain any special, supernatural or spell-like abilities.
Dragon breath is a special ability, for instance, so were
the caster to assume the form of a dragon they could
use the dragon's normal claw, bite, and tail swipe
attacks, but not the dragon's breath.

If the form assumed is capable of speaking and making
appropriate gestures (as determined by the GM) the
caster may use their own spells in the assumed form.

Equipment worn or carried will be dropped if the new
form is unable to wear or carry the items. If any such
item would be constricting or physically harmful to the
new form, the transformation slows and alters such that
the item is dropped without damage to the items nor
harm to the target creature. If the GM decides that any
such item cannot be removed in this way, the spell fails.

The caster can remain transformed up to one hour per
level of ability, or may choose to end the spell before
that point if they wish.

</div>
<div class="spell" data-tag="Projected Image" id="Projected Image">

## Projected Image

Range: 240'

Magic User 6

Duration: 6 turns

This spell creates a quasi-real, illusory version of the
caster. This illusory projected image looks, sounds, and
smells like the caster, in addition to mimicking gestures
and actions (including speech, which is projected from
the caster to the illusory image as if by a form of
**ventriloquism**). Any further spells cast seem to
originate from the illusion, not the actual caster.

A line of sight between the caster and their illusory self
must be maintained or the spell ends. Any effect or
action that breaks the line of sight dispels the image, as
does the illusionary caster being struck in combat. Note
that this spell grants no special sensory powers to the
caster; for example, if the illusory self is positioned so as
to be able to see something the caster can't directly see,
the caster does not see it. Also, all spell ranges are still
figured from the caster's actual position, not the illusory
self's position.

</div>
<div class="spell" data-tag="Protection from Evil*" id="Protection from Evil*">

## Protection from Evil*

Cleric 1, Magic-User 1

Range: touch

Duration: 1 turn/level

This spell protects the caster or a creature touched by
the caster (the "subject") from evil; specifically, the spell
wards against summoned creatures, creatures with
significantly evil intentions, and extraplanar creatures of
evil nature. A magical barrier with a radius of just 1
foot is created around the subject. The barrier moves
with the subject, and provides three specific forms of
magical protection against attacks or other effects
attempted by the affected creatures against the subject.

First, the subject receives a bonus of +2 to their Armor
Class, and a similar bonus of +2 on all saving throws.
Second, the barrier blocks all attempts to **charm** or
otherwise control the subject, or to possess the subject
(such as with **magic jar**). Such attempts simply fail
during the duration of this spell. Note however that a
creature who receives this protection after being
possessed is not cured of the possession.

Third, any and all summoned creatures and extraplanar
creatures of evil nature are unable to physically touch
the subject. Attacks by such creatures using their
natural weapons simply fail. This effect is canceled if
the subject performs any form of physical attack (even
with a ranged weapon) on any affected creature, but
the other features of the spell continue in force.

Reversed, this spell becomes **protection from good**. It
functions in all ways as described above, save that
"good" creatures are kept away, rather than "evil" ones.

</div>
<div class="spell" data-tag="Protection from Evil 10' Radius*" id="Protection from Evil 10' Radius*">

## Protection from Evil 10' Radius*

Cleric 4, Magic-User 3

Range: touch

Duration: 1 turn/level

This spell functions exactly as **protection from evil**, but with a 10' radius rather than a 1' radius. All within the radius receive the protection; those who leave and then re-enter, or who enter after the spell is cast, receive the protection as well.

Reversed, this spell becomes **protection from good 10' radius**, and functions exactly as the reversed form of **protection from evil**, except that it covers a 10' radius around the target rather than the normal 1' radius.

</div>
<div class="spell" data-tag="Protection from Normal Missiles" id="Protection from Normal Missiles">

## Protection from Normal Missiles

Magic User 3

Range: self

Duration: 1 turn/level

The caster is completely protected from small sized, non-magical missile attacks. Therefore, magic arrows, hurled boulders, or other such are not blocked, but any number of normal arrows, sling bullets, crossbow bolts, thrown daggers, etc. will be fended off. Note that normal missiles projected by magic bows count as magical missiles for the purposes of this spell.

</div>
<div class="spell" data-tag="Purify Food and Water" id="Purify Food and Water">

## Purify Food and Water

Cleric 1

Range: 10'

Duration: instantaneous

With this spell the caster makes contaminated food or
water pure and safe to eat or drink. Poison is
neutralized and spoilage is reversed by this spell. The
spell does not protect against future decay, however,
nor does it affect magic potions (including,
unfortunately, **Potions of Poison**). Unholy water, if it
exists in your campaign, is ruined by the casting of this
spell. The spell affects about 2 pounds of food and/or
drink per caster level; note that a quart of water or
similar drink weighs just over 2 pounds.

</div>
<div class="spell" data-tag="Quest*" id="Quest*">

## Quest*

Range: 5'/level

Cleric 5

Duration: special

By means of this spell the caster compels a living
creature to perform some specific action or services, or
alternately to avoid performing some action. The target
creature must be able to hear and understand the
caster, or it cannot be affected. This spell will
automatically fail if used to compel a creature to engage
in some obviously self-destructive action.

A saving throw vs. Spells will allow an unwilling target
to resist a quest when it is first cast. However, the
target may choose to accept the quest, typically as part
of a bargain with the caster to perform some service.
Once subjected to this spell, the subject must obey the
instructions given by the caster indefinitely, though if
the quest is to perform some action the spell effectively
ends when that action has been completed.

For every 24 hours that an affected creature chooses
not to obey the quest (or is prevented from obeying it),
it suffers 3d6 points of damage. This damage is limited,
in that it will not kill the target; if the damage is enough
to do so, roll 1d4 for the number of hit points the
affected creature retains (similar to the spell **harm**, the
reverse of **heal**).

If the task assigned to the subject of this spell is open-
ended or otherwise unable to be completed, the subject
is still compelled to try to perform the task, but the spell
will end in no more than one day per caster level.

Very clever creatures may be able to subvert the
instructions given; the GM must decide on the results of
any such attempts.

A quest (and all effects thereof) can be ended by a
**remove curse** spell from a caster two or more levels
higher than the caster of the quest, or by a wish, or by
the reverse of this spell. **Dispel magic** does not affect a
quest spell.

</div>
<div class="spell" data-tag="Raise Dead*" id="Raise Dead*">

## Raise Dead*

Range: touch

Cleric 5

Duration: instantaneous

This spell restores life to a deceased humanoid (as
defined in **charm person**). The caster can only raise a
being that has not been dead for more days than the
caster has levels. The spirit of the target of this spell
must be willing to return. If the target's spirit is trapped
or contained in any way, the spell will fail. It will also
fail if the target died of old age, as the body simply has
no life left in it. Similarly, undead creatures are not
affected by this spell as they can no longer be returned
to life in any normal sense.

The body of the target must be adequately intact to
support life, but all wounds no matter how major are
healed. Body parts missing when the target is raised
are still missing afterward. Normal poison and normal
disease are cured in the process of raising the subject,
but magical diseases and curses are not undone.

Creatures brought back from the dead always suffer
some loss or penalty from the ordeal. Characters lose
one level of ability permanently (i.e. it does not accrue
a negative level, but rather loses an actual level, being
reduced to the minimum number of experience points
required for the previous level). First level characters
are reduced to Normal Man status; if the character was
already a Normal Man they lose a point of Constitution.
These losses are permanent, though of course the
character may gain levels in the normal fashion.
(Characters reduced to Normal Man status must gain
1,000 XP to return to 1st level).

Monstrous humanoids (orcs, goblins, and the like) lose
one hit die, or are reduced to ½ hit dice if the monster
has just one to start with. Such humanoids who
already have ½ hit dice are reduced to a single hit point.
These losses are generally permanent, though the GM
may allow such creatures in service to a player
character to recover by gaining 1,000 XP per hit die the
creature would be returning to (so a lizard man who has
been reduced to 1 hit die must earn 2,000 XP to return
to its original 2 hit dice); treat such a creature as being a
retainer for this purpose.

Upon being raised, the target has 1 hit point per level or
hit die (using its current reduced figure, of course), with
a minimum of 1 hit point. A character who died with
spells prepared has none prepared upon being raised.

The reverse of this spell, **slay living**, will kill instantly
the creature touched (which may be of any sort, not
just a humanoid) unless a save vs. Spells is made. If
the saving throw is successful, 2d6 points of damage is
dealt to the victim instead. An attack roll is required to
apply this spell in combat.

</div>
<div class="spell" data-tag="Read Languages" id="Read Languages">

## Read Languages

Range: 0

Magic User 1

Duration: special

This spell grants the caster the ability to read almost any written language. It may be cast in one of three modes:

In the first mode, the spell allows the caster to read any number of written works in a variety of languages. This mode lasts for 1 turn per caster level.

In the second mode, the spell allows the caster to read any one book or tome; this mode lasts 3 hours per caster level.

In the third mode, the spell allows the caster to read any one non-magical scroll or other single-sheet document; this mode is permanent.

This spell does not work on any sort of magical text, such as spell scrolls or spellbooks; see **read magic**, below, for the correct spell to use in such cases.

The spell grants the ability to read the texts, but does not in any way hasten the reading nor grant understanding of concepts the caster doesn't otherwise have the ability to understand. Also, for this spell to function, there must be at least one living creature that can read the given language somewhere on the same plane. The knowledge is not copied from that creature's mind; rather, it is the existence of the knowledge that enables the spell to function.

</div>
<div class="spell" data-tag="Read Magic" id="Read Magic">

## Read Magic

Range: 0

Magic User 1

Duration: permanent

When cast upon any magical text, such as a spellbook or magic-user spell scroll, this spell enables the caster to read that text. Casting this spell on a cursed text will generally trigger the curse. All Magic-Users begin play knowing this spell, and it can be prepared even if the Magic-User loses access to his or her spellbook.

</div>
<div class="spell" data-tag="Regenerate" id="Regenerate">

## Regenerate

Range: touch

Cleric 6

Duration: permanent

This spell causes the subject's severed body members (fingers, toes, hands, feet, arms, legs, tails, or even heads of multiheaded creatures), broken bones, and ruined organs to grow back. After the spell is cast, the physical regeneration is complete in 1 round if the severed members are present and touching the creature. Otherwise, a full turn is required for the regeneration to complete.

This spell also heals 3d8 points of damage. Regenerate has no effect on nonliving creatures or constructs (including undead).

</div>
<div class="spell" data-tag="Reincarnate" id="Reincarnate">

## Reincarnate

Range: touch

Magic User 6

Duration: instantaneous

By touching the body of a deceased humanoid (as
defined in **charm person**), the caster brings them back
in an entirely new body. The whole body is not
needed; in fact, even the smallest fragment of body is
sufficient, so long as that fragment was part of the body
at the time of the target's death.

The caster can only reincarnate a being that has not
been dead for more than a week. The spirit of the
target of this spell must be willing to return. If the
target's spirit is trapped or contained in any way, the
spell will fail.

Roll on the following table to determine what sort of creature the character becomes:

```{ojs}

import {generalTableSelect} from "./custom.js"

viewof reincarnate = Inputs.button("Roll on Table", {value: 0, reduce: () => highlightTableRow("#reincarnate-spell", generalTableSelect([1,100,0],[[1,1],[2,15],[16,29],[30,30],[31,39],[40,46],[47,60],[61,88],[89,91],[92,93],[94,98],[99,100]]))})

```
<br>

:::{#reincarnate-spell}

| d% | Incarnation |
|----|----|
| 01 | Bugbear |
| 02--15 | Dwarf |
| 16--29 | Elf |
| 30 | Gnoll |
| 31--39 | Gnome |
| 40--46 | Goblin |
| 47--60 | Halfling |
| 61--88 | Human |
| 89--91 | Kobold |
| 92--93 | Lizard Man |
| 94--98 | Orc |
| 99--100 | Choice* |

:::

If "choice" is rolled for a player character being
reincarnated, the player is allowed to choose the new
form from among those on the table above. If an NPC
is being reincarnated, the GM may choose or roll again.

When the spell is cast, a new body forms in a nearby
location selected by the caster. The body forms over a
period of 6 turns (i.e. an hour), first as a misty outline,
then becoming more solid moment by moment until it
takes its first breath and awakens. The new form is a
young adult, unless the target was younger than that
when they died, in which case the new body is the
same age as the deceased body.

The target creature's new body has obviously suffered
none of the harm that may have befallen the old one,
and is completely healthy (at least, to start with).

The target remembers their previous life, and retains
the same class (if possible for the new form) as well as its Intelligence, Wisdom, and Charisma. Strength,
Dexterity, and Constitution scores should be rerolled.
(If the character's ability scores are outside the allowable
range for the new form, they should be adjusted up or
down by the GM as needed.) The target loses one
level (or hit die); this is a real reduction, not a negative
level, and is not subject to magical **restoration**. The
target's hit points should be rerolled completely, as this
is an entirely new body. If the target was 1st level,
instead of a hit point reduction its new Constitution
score is reduced by 2

Characters turned into non-character humanoids (such
as an elf who returns as a kobold) will require
adjudication by the GM; if the restored target is a player
character, the GM is counseled to give as much leeway
to the player as possible with the character's new form.
Conversely, non-character humanoids who return as
characters will need all ability scores rolled; such
characters will usually be fighters with a level equal to
the target's previous hit dice minus 1, or as Normal Men
if the target's previous hit dice were 1 or less.

Undead creatures are not affected by this spell; such
creatures can no longer be returned to life in any
normal sense.

</div>
<div class="spell" data-tag="Remove Curse*" id="Remove Curse*">

## Remove Curse*

Range: 30'

Cleric 3, Magic-User 4

Duration: instantaneous

This spell removes any and all ordinary curses afflicting
a creature. It does not generally remove the curse from
a magic item such as a sword or suit of armor, but a
character afflicted by a cursed item of this type will be
freed of it long enough to discard the item (a turn, at
least).

Some special curses are more difficult to remove, and
may require a caster of a certain minimum level. A
very few curses created by godlike beings cannot be
removed by this spell at all.

The reverse of this spell, bestow curse, allows the
caster to place a curse on the subject. A save vs. Spells
is allowed to resist. The caster must choose one of the
following three effects:

* -4 decrease to an ability score (minimum 1).

* -4 penalty on attack rolls and saves.

* Each round of combat, the target has a 50% chance to act normally; otherwise, it takes no action.

The caster may also invent his or her own curse, but it should be no more powerful than those described above. The curse thus bestowed cannot be dispelled, but it can be removed with a **remove curse** spell.

</div>
<div class="spell" data-tag="Remove Fear*" id="Remove Fear*">

## Remove Fear*

Range: touch (120')

Cleric 1

Duration: instantaneous (2 turns)

This spell will calm the creature touched. If the target creature is currently subject to any sort of magical fear, it is allowed a new save vs. Spells to resist that fear, at a bonus of +1 per level of the caster.

The reverse of this spell, **cause fear**, causes one target creature within 120' to become frightened; if the target fails to save vs. Spells, it flees for 2 turns. Creatures with 6 or more hit dice are immune to this effect.

</div>
<div class="spell" data-tag="Resist Cold" id="Resist Cold">

## Resist Cold

Range: touch

Cleric 1

Duration: 1 round/level

This spell makes the caster, or any living creature the
caster touches, completely immune to normal cold.
The spell also gives protection against magical or
otherwise superior cold such as the breath of an Ice
Dragon or the **ice storm** spell. Specifically, the spell
gives the protected creature a bonus of +3 on all saving
throws against such effects, and reduces any damage
suffered by half (so that for example a successful save
vs. the Ice Dragon's breath would reduce damage to
just one-fourth normal, and even if the saving throw
fails the protected creature only takes half damage).

</div>
<div class="spell" data-tag="Resist Fire" id="Resist Fire">

## Resist Fire

Range: touch

Cleric 2

Duration: 1 round/level

This spell makes the caster, or any living creature the
caster touches, completely immune to normal heat or
fire. The spell also gives protection against magical or
otherwise superior heat or fire such as the breath of a
Mountain Dragon or the **fireball** spell. Specifically, the
spell gives the protected creature a bonus of +3 on all
saving throws against such effects, and reduces any
damage suffered by half (so that for example a
successful save vs. the **fireball** spell would reduce
damage to just one-fourth normal, and even if the
saving throw fails the protected creature only takes half
damage).

</div>
<div class="spell" data-tag="Restoration" id="Restoration">

## Restoration

Range: touch

Cleric 6

Duration: permanent

Each casting of the spell removes a single negative level from a creature who has suffered energy drain. At 16th level, two negative levels may be removed. See the rules for Energy Drain (in the [Encounter](combat.qmd#energy-drain) section) for more details.

Alternately, this spell can be used to restore drained ability score points. If applied to a character who has suffered temporary loss of ability points, it will restore up to 1d4 lost points to any one drained ability immediately. If applied to a character who has suffered permanent loss of ability points, 1 point can be restored.

Restoration does not restore levels lost due to death (as described for the spell **raise dead**).

</div>
<div class="spell" data-tag="Shield" id="Shield">

## Shield

Range: self

Magic User 1

Duration: 5 rounds+1/level

Shield creates an invisible, shield-like mobile disk of force that hovers in front of the caster. It negates **magic missile** attacks directed at the caster, and improves the caster's Armor Class by +3 vs. melee attacks and +6 vs. missile weapons. The Armor Class benefits do not apply to attacks originating from behind the caster, but **magic missiles** are warded off from all directions.

</div>
<div class="spell" data-tag="Silence 15' Radius" id="Silence 15' Radius">

## Silence 15' Radius

Cleric 2

Range: 360'

Duration: 2 rounds/level

This spell creates a spherical area with a 15 foot radius
where no sound will pass. No one within the affected
area can make nor hear any sound. Neither does
sound issue from the affected area; those outside
cannot hear those inside. This effect blocks verbal
communication, of course, as well as spell casting.

This effect can be cast in a fixed area, upon an item
(making it portable), or upon a creature. An unwilling
target receives a save vs. Spells to negate the spell. If
an item in another creature’s possession is targeted, that
creature also receives a save vs. Spells to negate.

This spell can be used to protect against any kind of
attack or magic where the victims must be able to hear
the attacker, for such attacks cannot pass into or out of
the affected area

</div>
<div class="spell" data-tag="Sleep" id="Sleep">

## Sleep

Range: 90'

Magic User 1

Duration: 5 rounds/level

This spell puts several creatures of 3 or fewer hit dice,
or a single 4 hit die creature, into a magical slumber.
Creatures of 5 or more hit dice are not affected. The
caster chooses a point of origin for the spell (within the
given range, of course), and those creatures within 30'
of the chosen point may be affected. Each creature in
the area of effect is allowed a save vs. Spells to resist.

Victims of this spell can always be hit if attacked.
Injuring such a creature will cause it to awaken, and it
may begin fighting back or defending itself on the very
next round. Slapping or shaking such a creature will
awaken it in 1d4 rounds, but normal noises will not.

Sleep does not affect unconscious creatures, constructs,
or undead creatures.

When the duration elapses, the sleeping creatures
normally wake up immediately; however, if they are
made very comfortable and the surroundings are quiet,
the affected creatures may continue sleeping normally
at the GM's option.

</div>
<div class="spell" data-tag="Speak with Animals" id="Speak with Animals">

## Speak with Animals

Cleric 2

Range: special

Duration: 1 turn/4 levels

This spell allows the caster to speak to and understand
any single animal (normal or giant sized, but not
magical or monstrous) that is in sight of the caster and
able to hear them. The caster may change which
animal they are speaking with at will, once per round.
The spell doesn’t alter the animal’s reaction or attitude
towards the caster; a standard reaction roll should be
made to determine this. The GM should ensure that
the animal's manner of speaking reflects its intelligence
and nature

</div>
<div class="spell" data-tag="Speak with Monsters" id="Speak with Monsters">

## Speak with Monsters

Cleric 6

Range: special

Duration: 1 turn/5 levels

This spell allows the caster to speak to and understand
any single living monster that is in sight of the caster
and able to hear them. The caster may change which
monster they are speaking with at will, once per round.
Others able to understand the language spoken by the
target monster (if any) will be able to understand the
caster. The spell doesn’t alter the monster’s reaction or
attitude towards the caster. Mindless monsters, plant
creatures and undead are unaffected by this spell.

</div>
<div class="spell" data-tag="Speak with Plants" id="Speak with Plants">

## Speak with Plants

Range: 20'

Cleric 4

Duration: 1 turn

This spell allows the caster to speak to and understand
any single plant (either normal plant or animate plant
creature). The GM should remember that normal
plants have a limited sense of their surroundings, and
most never move from the place where they sprouted.
The spell doesn’t alter the plant’s reaction or attitude
towards the caster; however, normal plants will
generally communicate freely with the caster, as they
have nothing else of importance to do. Plant creatures
will tend to be slightly more intelligent, and a reaction
roll should be used to determine how such creatures
respond to the caster's words.

</div>
<div class="spell" data-tag="Speak with Dead" id="Speak with Dead">

## Speak with Dead

Range: 10'

Cleric 3

Duration: 3 rounds/level

With this spell the caster causes the corpse of an
intelligent creature to become animated and to answer
the caster's questions. It does not matter how long the
corpse has been dead, but it must be essentially intact
with at least a comple
te mouth in order to answer
questions.
The corpse will answer at most one question per two
caster levels, but if the duration expires any remaining
questions are lost. The corpse only knows what it knew
when it was alive; this includes the languages it knew in
life. Thus, the caster must share a language with the
deceased in order to get any questions answered at all.

The answers given are drawn from knowledge
"imprinted" on the corpse during life; the caster does
not in any case actually communicate with the spirit of
the deceased creature. The corpse cannot retain any
information given to it, and does not even remember
any previous instances of communication via this spell.

The answers given may not be useful for various
reasons. If the corpse knew the caster when it was
alive, or if the caster is a member of a group the
deceased disliked, it may choose to lie or mislead the
caster. If the caster asks the corpse questions of a
personal nature, or questions that indicate the caster
may be working against whatever interests the corpse
had in life, it will almost certainly seek to mislead the
caster.

If the corpse has been roused by this spell within the
last seven days, the spell will fail. Undead creatures
(including the remains of defeated undead creatures)
cannot be affected by this spell.

</div>
<div class="spell" data-tag="Spiritual Hammer" id="Spiritual Hammer">

## Spiritual Hammer

Range: 30'

Cleric 2

Duration: 1 round/level

This spell causes a warhammer made of pure force to spring into existence, attacking any foe chosen by the Cleric within range once per round. It deals 1d6 hit points of damage per strike, +1 point per three caster levels (maximum of +5). It uses the caster's normal attack bonus, striking as a magical weapon, and thus can inflict damage upon creatures that are only hit by magic weapons. If the hammer goes beyond the spell range, the Cleric loses sight of it, or the caster ceases to direct it, the hammer disappears. The hammer cannot be attacked or harmed by physical attacks, but **dispel magic**, **disintegrate**, or a **rod of cancellation** will dispel it.

</div>
<div class="spell" data-tag="Sticks to Snakes" id="Sticks to Snakes">

## Sticks to Snakes

Range: 120'

Cleric 4

Duration: 6 turns

This spell transforms normal wooden sticks into 1d4 hit dice worth of normal (not giant) snakes per every four caster levels. (See the **Monsters** section for details on types of [snakes](monstersAll.qmd#snake-giant-rattlesnake).) The snakes follow the commands of the caster. When slain, dispelled, or the spell expires, the snakes return to their original stick form. Magical "sticks" such as enchanted staves cannot be affected.

</div>
<div class="spell" data-tag="Striking" id="Striking">

## Striking

Range: touch

Cleric 3

Duration: 1 round/level

This spell bestows upon one weapon the ability to deal 1d6 points of additional damage. This extra damage is applied on each successful attack for the duration of the spell. It provides no attack bonus, but if cast on a normal weapon, the spell allows monsters only hit by magical weapons to be affected; only the 1d6 points of magical damage applies to such a monster, however.

</div>
<div class="spell" data-tag="Telekinesis" id="Telekinesis">

## Telekinesis

Range: self

Magic User 5

Duration: 3 turns

This spell permits the caster to move objects or
creatures by concentration alone; the caster can move
such things weighing up to 50 pounds per caster level
at a rate of up to 20 feet per round. Creatures targeted
by this spell are allowed a saving throw vs. Death Ray
to resist, whether it is the creature itself being affected
or an object in its possession.

In order to use this power the caster must maintain
concentration, moving no more than normal movement
(no running), making no attacks and casting no further
spells. If concentration is lost (whether intentionally or
not), the power may be used again on the next round
but the target of the effect is allowed a new saving
throw.

</div>
<div class="spell" data-tag="Teleport" id="Teleport">

## Teleport

Range: self

Magic User 5

Duration: instantaneous

The caster of this spell is instantly transported to
another location up to 100 miles away per level of
ability. The spell transports the caster only within their
current plane of existence.
Other creatures
(passengers) and inanimate objects (cargo) may be
transported along with the caster, up to a maximum of
300 pounds plus 100 pounds per level above 10th.
The caster must be in contact with all objects and/or
creatures to be transported (although creatures to be
transported may be in contact with one another, with at
least one of those creatures in contact with the caster).
Unwilling creatures are allowed a saving throw vs.
Spells to resist the spell, and the caster may need to
make an attack roll to make contact with such a
creature. Likewise, a successful save vs. Spells will
prevent items in a creature's possession from being
teleported.

The spell is directed by the mind of the caster, who
must visualize the destination area; failure to visualize it
properly can cause the spell to fail in a variety of ways,
and destinations heavily saturated with magical energy
(as defined by the Game Master) will cause the spell to
fail automatically.

To determine the results of this spell, roll d% and consult the table below. Below the table is an explanation of the terms used.

| Knows Well | Knows Somewhat | Saw Once | Spell Result | 
|------------|----------------|----------|--------------|
| 01         | 01--02         | 01-03    | Disaster     |
| 02         | 03--07         | 04--13   | Wrong Place  |
| 03         | 08--13         | 14--25   | Fell Short   |
| 04--100    | 14--00         | 26--100  | Success!     |


**Knows Well** applies when the caster has visited the
destination frequently and/or spent a substantial
amount of time there; generally, the caster should have
spent at least 7 days (not necessarily in a row) at the
destination within the last year to qualify for this
category. Any place where the caster lived for more
than a month in the last ten years, or more than a year
in their life, also qualifies.

**Knows Somewhat** applies when the caster has spent
substantial time in the destination area, but not enough
to qualify for Knows Well. Alternately, the caster may
have made an in-depth study of the area, looking at
accurate drawings, maps, and floorplans or spending
hours listening to descriptions from one or more people
who Know Well the destination.

**Saw Once** applies when the caster has visited a place
for as much as a day, but no more, or when the caster
has attempted the study required for the second
definition of Knows Somewhat but has failed to acquire
enough information (in the GM's opinion).

**If the caster attempts to travel to a location that
does not exist**, or perhaps once existed but has been
destroyed or otherwise changed so much that the caster
would not recognize it, roll 2d20 instead d% for the
result of the casting. In this case, if Success! is rolled
the spell simply fails and no one is transported
anywhere.

**Success!** means exactly what it says. The caster,
passengers, and cargo arrive safely exactly where the
caster intended

**Fell Short** indicates that the caster, passengers, and
cargo arrive safely 1d8x10% of the way to the intended
destination. Note that arriving "safely" does not mean
that the destination is safe, but only the trip

**Wrong Place** means that the caster, passengers, and
cargo arrive at some place that resembles the intended
destination. This means that the caster appears in the
closest similar place within range, as decided by the
GM. If no such area exists within the spell’s range, the
spell simply fails instead.

**Disaster** indicates that the caster, passengers, and
cargo have encountered dimensional turbulence and
have crashed, becoming separated (if passengers
and/or cargo accompanied the caster) and being injured
in the process. Each creature including the caster
suffers 1d12 points of damage, and then rolls again on
the same column using 2d20 instead of d%. If another
Disaster is rolled for any creature, apply another 1d12
points of damage and roll once more. Cargo objects
are not normally damaged but the result must be rolled
for each such item to determine where it has appeared;
in this case, if Disaster is rolled the cargo item
disappears forever.

</div>
<div class="spell" data-tag="True Seeing" id="True Seeing">

## True Seeing

Range: touch

Cleric 5

Duration: 1 round/level

This spell confers on the target the ability to see all things as they actually are. The subject sees through normal and magical darkness, notices secret doors, sees the exact locations of displaced creatures or objects, sees through normal or magical disguises, sees invisible creatures or objects normally, sees through illusions, and sees the true form of polymorphed, changed, or transmuted things. The range of true seeing conferred is 120 feet.

True seeing, however, does not penetrate solid objects. It in no way confers X-ray vision or its equivalent. It does not negate concealment, including that caused by fog and the like. In addition, the spell effects cannot be further enhanced with known magic, so one cannot use true seeing through a **crystal ball** or in conjunction with **clairvoyance**.

</div>
<div class="spell" data-tag="Ventriloquism" id="Ventriloquism">

## Ventriloquism

Range: 60'

Magic User 1

Duration: 1 turn/level

This spell causes the caster's voice to appear to come
from another location within range, for example, from a
dark alcove or statue. The caster may choose a new
location each round if desired, and can cause the spell
to temporarily abate without ending it and then resume
it again at any time within the given duration

</div>
<div class="spell" data-tag="Wall of Fire" id="Wall of Fire">

## Wall of Fire

Range: 180'

Cleric 5, Magic-User 4

Duration: 1 round/level (or special)

This spell creates a vertical sheet of flames in an area
indicated by the caster, which is either a wall of flame
up to 20' in length per caster level, or a ring with a
radius up to 5' per caster level. The caster may choose
to make the wall smaller if desired. The wall may be up
to 20' tall (as desired by the caster and/or constrained
by the ceiling). The entire wall must lie within the range
given above. One or both sides of the wall may be hot,
as determined by the caster at the time of casting.
Once created, the wall cannot be moved or changed.

Any creature within 20 feet of a hot side of the wall will
suffer 1d4 points of damage each round, or 2d4 points
if within 10 feet. Damage is applied on the round the
spell is cast and each round thereafter. Actually passing
through the wall causes 2d6 points of damage, plus 1
per caster level, even if the side the character or
creature entered from was not a hot side.

Undead creatures are particularly susceptible to this
spell, and suffer twice the damage described above.

If the caster evokes the wall so that it appears where
creatures are, each creature takes damage as if passing
through the wall; a save vs. Spells is allowed, with
success indicating that damage is rolled as if the
creature is within 10' of the wall.

The caster may choose to maintain the spell indefinitely
(within reasonable limits of endurance) by
concentration, or may cast it with the standard duration
of 1 round per level, at their option

</div>
<div class="spell" data-tag="Wall of Iron" id="Wall of Iron">

## Wall of Iron

Range: 90'

Magic User 6

Duration: permanent

Using this spell the caster creates an iron wall. The wall
stands upright, and consists of up to one 10'x10' square
section, one inch thick, per caster level. The caster can
increase the thickness of the wall with a proportionate
reduction in the area; for example, doubling the
thickness halves the area. The caster may choose to
make the wall smaller than the maximum size if desired.
The wall may not be made less than one inch thick, and
must always be created in contact with the ground or
floor beneath it. It is always a flat plate with no bends,
but the edges do not have to be straight; indeed, the
caster can cause the wall edge to mold itself around any
obstructing object very closely. The wall cannot
otherwise be created such that it occupies the space of
any object or creature.

If the caster wishes, the wall edges will bond to any
inanimate materials they touch (stone walls, soil,
furnishings, and so on). If this is not done, the wall may
be unsupported (as determined by the GM based on
the situation) and will thus likely fall. If left unattended,
there is an equal chance it will fall in either direction in
1d6 rounds, but it can be pushed in a specific direction
by any character having a minimum of Strength score
of 13, or any monster with 4 or more hit dice. Several
creatures can work together to do so if desired. (If the
optional Ability Roll rule is being used, a Strength roll at
-3 is sufficient to topple the wall.)

When the wall falls, any creatures it falls upon are likely
to be injured or killed. If it is possible for a character or
creature to escape the area (i.e. it has sufficient
movement rate and is not otherwise prevented from
doing so), it is allowed to roll a save vs. Death Ray (with
Dexterity bonus added). If this save is successful, the
creature or character moves by the most direct route to
the nearest safe space; if the save fails or it is for some
reason impossible to flee, 10d6 points of damage are
inflicted on that victim. Creatures larger than ogre-sized
are immune to being crushed and will simply be
knocked down if the save fails.

The wall is permanent, as indicated, but being made of
iron is susceptible to rust and corrosion

</div>
<div class="spell" data-tag="Wall of Stone" id="Wall of Stone">

## Wall of Stone

Range: 15' per level

Magic User 5

Duration: permanent

Using this spell the caster creates a stone wall. The wall
is composed of up to one 10'x10' square section, one
foot thick, per caster level. The caster can form this
wall into almost any shape, with some restrictions. The
caster can increase the thickness of the wall with a
proportionate reduction in the area; for example,
doubling the thickness halves the area. The wall cannot
be created such that it occupies the space of any object
or creature. It must be adequately supported by
existing stone, which it will bond with automatically, but
need not be supported over its entire area. For
example, a wall of stone may be formed into a bridge
over a stream or chasm, so long as both ends of the
bridge rest solidly upon (and bond with) existing stone.

Bridges longer than 20 feet must be arched, buttressed,
or both in order to stand; this extra construction
reduces the wall's usable volume by half, as does
creating a wall with battlements, crenelations, and
similar basic structural elements. No complex structural
elements may be created by this spell.

Though made by magic, the wall is made of stone and
can be broken or damaged just as if it were ordinary
stone.

The wall can be formed into a container to trap
creatures, and if this is attempted the targets of the spell
are allowed to save vs. Death Ray to avoid being
trapped. If the save is successful the targets are able to
make up to one full move to a space outside the
container.

</div>
<div class="spell" data-tag="Water Breathing" id="Water Breathing">

## Water Breathing

Range: touch

Magic User 3

Duration: 2 hours/level

This spell grants living creatures touched by the caster
(including the caster, if desired) the ability to breath in
water as a fish does. The duration may be divided
evenly if the caster touches multiple targets one after
another. Affected targets do not lose the ability to
breathe air.

</div>
<div class="spell" data-tag="Web" id="Web">

## Web

Range: 10' per level

Magic User 2

Duration: 2 turns/level

This spell creates a volume of sticky strands resembling
a spider's web but much larger and thicker. The spell
fills a volume of up to 8,000 cubic feet (equivalent to
eight 10'x10'x10' cubes). The webs must be attached
to adjacent solid objects such as walls, pillars, and the
like; any unsupported section of webbing collapses to
the ground and disappears. Within this limitation, the
caster may choose any arrangement of webs they wish,
up to the limit of range and the given 8,000 cubic foot
volume. The caster may choose to create a smaller
volume if they wish.

Creatures within the web at the time the spell is cast, as
well as anyone entering the area afterward, will become
entangled. Each should roll a save vs. Death Ray, and
any creatures who succeed at this save may move
through the webbing but are reduced to one-half
normal movement rate. Such creatures may not cast
spells or perform normal attacks; whether other actions
are possible is left to the GM to decide. Once an
entangled creature leaves the area of effect of the web,
it will be able to act normally again.

Those who fail the save are fully entangled and
trapped. They cannot move, cast spells, or perform
normal attacks or any other physical action. Speech
remains possible, however. Creatures with Strength of
13 or higher (or 4 or more hit dice) may be able to
break loose, however; each round, such creatures are
allowed another save vs. Death Ray with results as
given above. Creatures failing the initial save and
having Strength of 12 or less (or fewer than 4 hit dice)
are trapped until the duration expires or the webs are
otherwise removed.

Attacks against an entangled creature by one outside
the webbing will not normally entrap the attacker, so
long as they do not need to venture into the web to
reach the entangled target.

The web can be ignited; any application of fire to the
webbing will cause a 10 foot cube to burn away in one
round, with all 10 foot cubes adjacent to the destroyed
one burning in the next round, and so on. If any part
of the web becomes unsupported it will collapse and
disappear as noted above.

Creatures trapped within the burning web suffer 2d4
points of damage when the cube they are trapped in
burns, but they are thereafter completely free of the
web.

</div>
<div class="spell" data-tag="Wizard Eye" id="Wizard Eye">

## Wizard Eye

Range: 240'

Magic User 4

Duration: 6 turns

With this spell the caster creates an invisible magical "eye" through which he or she can see. The eye has Darkvision, but otherwise sees exactly as the caster would. It can be created in any place the caster can see, up to a range of 240' away, and thereafter can move at a rate of 40' per round as directed by the caster. The eye will not move more than 240' feet away from the caster under any circumstances. The eye cannot pass through solid objects, but as it is exactly the size of a normal human's eye, it can pass through holes as small as 1 inch in diameter. The caster must concentrate to use the eye.

</div>
<div class="spell" data-tag="Wizard Lock" id="Wizard Lock">

## Wizard Lock

Range: 20'

Magic User 2

Duration: permanent

This spell magically holds shut a door, gate, window, or
shutter of wood, metal, or stone. The magic affects the
portal just as if it were securely closed and normally
locked. The effect lasts indefinitely. **Knock** can be
used to open the doorway without ending the spell, and
**dispel magic** can be used to end it permanently. The
caster of this spell can easily open the door or other
portal without ending the spell, as can a Magic-User
three or more levels higher than the caster.

</div>

<div class="spell" data-tag="Word of Recall" id="Word of Recall">

## Word of Recall

Range: self (special)

Cleric 6

Duration: instantaneous

With the utterance of a single word this spell transports
the caster to a place of refuge which they designate
when preparing the spell. The place must be Known
Well (as explained for **teleport**) to the caster to be so
designated. This spell cannot transport the caster
beyond their current plane of existence.

The caster can bring along objects or creatures, not to
exceed 300 pounds plus 100 pounds per level above
10th. The caster must be in contact with all objects
and/or creatures to be transported (although creatures
to be transported may be in contact with one another,
with at least one of those creatures in contact with the
caster).

Unwilling creatures cannot be transported by this spell,
nor can items in their possession. If the caster or one of
their passengers is holding an object that is also being
held by an unwilling creature, the latter can retain
possession of the object with a successful save vs.
Spells.

</div>

```{=html}

<script>
let input = document.getElementById('input');
let animalDivs = document.querySelectorAll('.spell');

input.addEventListener('input', function(e) {
  const term = this.value.toLowerCase();
  animalDivs.forEach(function(div) {
    const animal = div.dataset.tag.toLocaleLowerCase();
    div.hidden = !animal.includes(term)
  });
});
</script>
```
