# Character Classes

## Cleric
+-------+-------------+----------+----------+---+---+---+---+---+---+
|       |             |          |          | Spell Lvl |   |   |   |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| Level | Exp. Points | Hit Dice | AB       | 1 | 2 | 3 | 4 | 5 | 6 |
+:======+============:+:========:+:========:+===+===+===+===+===+===+
| 1     | 0           | 1d6      | +1       | – | – | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 2     | 1,500       | 2d6      | +1       | 1 | – | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 3     | 3,000       | 3d6      | +2       | 2 | – | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 4     | 6,000       | 4d6      | +2       | 2 | 1 | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 5     | 12,000      | 5d6      | +3       | 2 | 2 | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 6     | 24,000      | 6d6      | +3       | 2 | 2 | 1 | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 7     | 48,000      | 7d6      | +4       | 3 | 2 | 2 | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 8     | 90,000      | 8d6      | +4       | 3 | 2 | 2 | 1 | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 9     | 180,000     | 9d6      | +5       | 3 | 3 | 2 | 2 | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 10    | 270,000     | 9d6+1    | +5       | 3 | 3 | 2 | 2 | 1 | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 11    | 360,000     | 9d6+2    | +5       | 4 | 3 | 3 | 2 | 2 | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 12    | 450,000     | 9d6+3    | +6       | 4 | 4 | 3 | 2 | 2 | 1 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 13    | 540,000     | 9d6+4    | +6       | 4 | 4 | 3 | 3 | 2 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 14    | 630,000     | 9d6+5    | +6       | 4 | 4 | 4 | 3 | 2 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 15    | 720,000     | 9d6+6    | +7       | 4 | 4 | 4 | 3 | 3 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 16    | 810,000     | 9d6+7    | +7       | 5 | 4 | 4 | 3 | 3 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 17    | 900,000     | 9d6+8    | +7       | 5 | 5 | 4 | 3 | 3 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 18    | 990,000     | 9d6+9    | +8       | 5 | 5 | 4 | 4 | 3 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 19    | 1,080,000   | 9d6+10   | +8       | 6 | 5 | 4 | 4 | 3 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 20    | 1,170,000   | 9d6+11   | +8       | 6 | 5 | 5 | 4 | 3 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+

Clerics are those who have devoted themselves to the service of a deity, pantheon or other belief system. Most Clerics spend their time in mundane forms of service such as preaching and ministering in a temple; but there are those who are called to go abroad from the temple and serve their deity in a more direct way, smiting undead monsters and aiding in the battle against evil and chaos. Player character Clerics are assumed to be among the latter group.

Clerics fight about as well as Thieves, but not as well as Fighters. They are hardier than Thieves, at least at lower levels, as they are accustomed to physical labor that the Thief would deftly avoid. Clerics can cast [spells of divine nature](spells.qmd#cleric-spells) starting at 2^nd^ level, and they have the power to Turn the Undead, that is, to drive away undead monsters by means of faith alone (see the [Encounter](combat.qmd#turning-the-undead) section for details).

The Prime Requisite for Clerics is Wisdom; a character must have a Wisdom score of 9 or higher to become a Cleric. They may wear any armor, but may only use blunt weapons (specifically including warhammer, mace, maul, club, quarterstaff, and sling).

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **1** | 11 | 12 | 14 | 16 | 15 |
| **2-3** | 10 | 11 | 13 | 15 | 14 |
| **4-5** | 9 | 10 | 13 | 15 | 14 |
| **6-7** | 9 | 10 | 12 | 14 | 13 |
| **8-9** | 8 | 9 | 12 | 14 | 13 |
| **10-11** | 8 | 9 | 11 | 13 | 12 |
| **12-13** | 7 | 8 | 11 | 13 | 12 |
| **14-15** | 7 | 8 | 10 | 12 | 11 |
| **16-17** | 6 | 7 | 10 | 12 | 11 |
| **18-19** | 6 | 7 | 9 | 11 | 10 |
| **20** | 5 | 6 | 9 | 11 | 10 |

: Cleric Saving Throws {#tbl-save-clerics}

## Fighter


| Level | Exp. Points | Hit Dice |AB       |
|-------|-------------|----------|---------|
| 1     | 0           | 1d8      |+1       |
| 2     | 2,000       | 2d8      |+2       |
| 3     | 4,000       | 3d8      |+2       |
| 4     | 8,000       | 4d8      |+3       |
| 5     | 16,000      | 5d8      |+4       |
| 6     | 32,000      | 6d8      |+4       |
| 7     | 64,000      | 7d8      |+5       |
| 8     | 120,000     | 8d8      |+6       |
| 9     | 240,000     | 9d8      |+6       |
| 10    | 360,000     | 9d8+2    |+6       |
| 11    | 480,000     | 9d8+4    |+7       |
| 12    | 600,000     | 9d8+6    |+7       |
| 13    | 720,000     | 9d8+8    |+8       |
| 14    | 840,000     | 9d8+10   |+8       |
| 15    | 960,000     | 9d8+12   |+8       |
| 16    | 1,080,000   | 9d8+14   |+9       |
| 17    | 1,200,000   | 9d8+16   |+9       |
| 18    | 1,320,000   | 9d8+18   |+10      |
| 19    | 1,440,000   | 9d8+20   |+10      |
| 20    | 1,560,000   | 9d8+22   |+10      |

Fighters include soldiers, guardsmen, barbarian warriors, and anyone else for whom fighting is a way of life. They train in combat, and they generally approach problems head on, weapon drawn.

Not surprisingly, Fighters are best at fighting of all the classes. They are also the hardiest, able to take more punishment than any other class. Although they are not skilled in the ways of magic, Fighters can nonetheless use many magic items, including but not limited to magical weapons and armor.

The Prime Requisite for Fighters is Strength; a character must have a Strength score of 9 or higher to become a Fighter. Members of this class may wear any armor and use any weapon.

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **NM** | 13 | 14 | 15 | 16 | 18 |
| **1** | 12 | 13 | 14 | 15 | 17 |
| **2-3** | 11 | 12 | 14 | 15 | 16 |
| **4-5** | 11 | 11 | 13 | 14 | 15 |
| **6-7** | 10 | 11 | 12 | 14 | 15 |
| **8-9** | 9 | 10 | 12 | 13 | 14 |
| **10-11** | 9 | 9 | 11 | 12 | 13 |
| **12-13** | 8 | 9 | 10 | 12 | 13 |
| **14-15** | 7 | 8 | 10 | 11 | 12 |
| **16-17** | 7 | 7 | 9 | 10 | 11 |
| **18-19** | 6 | 7 | 8 | 10 | 11 |
| **20** | 5 | 6 | 8 | 9 | 10 |

: Fighter Saving Throws {#tbl-save-fighter}

## Magic Users

+-------+-------------+----------+----------+---+---+---+---+---+---+
|       |             |          |          | Spell Lvl |   |   |   |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| Level | Exp. Points | Hit Dice | AB       | 1 | 2 | 3 | 4 | 5 | 6 |
+:======+============:+:========:+:========:+===+===+===+===+===+===+
| 1     | 0           | 1d4      | +1       | 1 | – | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 2     | 2,500       | 2d4      | +1       | 2 | – | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 3     | 5,000       | 3d4      | +1       | 2 | 1 | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 4     | 10,000      | 4d4      | +2       | 2 | 2 | – | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 5     | 20,000      | 5d4      | +2       | 2 | 2 | 1 | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 6     | 40,000      | 6d4      | +3       | 3 | 2 | 2 | – | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 7     | 80,000      | 7d4      | +3       | 3 | 2 | 2 | 1 | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 8     | 150,000     | 8d4      | +3       | 3 | 3 | 2 | 2 | – | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 9     | 300,000     | 9d4      | +4       | 3 | 3 | 2 | 2 | 1 | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 10    | 450,000     | 9d4+1    | +4       | 4 | 3 | 3 | 2 | 2 | – |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 11    | 600,000     | 9d4+2    | +4       | 4 | 4 | 3 | 2 | 2 | 1 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 12    | 750,000     | 9d4+3    | +4       | 4 | 4 | 3 | 3 | 2 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 13    | 900,000     | 9d4+4    | +5       | 4 | 4 | 4 | 3 | 2 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 14    | 1,050,000   | 9d4+5    | +5       | 4 | 4 | 4 | 3 | 3 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 15    | 1,200,000   | 9d4+6    | +5       | 5 | 4 | 4 | 3 | 3 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 16    | 1,350,000   | 9d4+7    | +6       | 5 | 5 | 4 | 3 | 3 | 2 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 17    | 1,500,000   | 9d4+8    | +6       | 5 | 5 | 4 | 4 | 3 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 18    | 1,650,000   | 9d4+9    | +6       | 6 | 5 | 4 | 4 | 3 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 19    | 1,800,000   | 9d4+10   | +7       | 6 | 5 | 5 | 4 | 3 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+
| 20    | 1,950,000   | 9d4+11   | +7       | 6 | 5 | 5 | 4 | 4 | 3 |
+-------+-------------+----------+----------+---+---+---+---+---+---+

Magic-Users are those who seek and use knowledge of the arcane. They do magic not as the Cleric does, by faith in a greater power, but rather through insight and understanding.

Magic-Users are the worst of all the classes at fighting; hours spent studying massive tomes of magic do not lead a character to become strong or adept with weapons. They are the least hardy, equal to Thieves at lower levels but quickly falling behind.

The Prime Requisite for Magic-Users is Intelligence; a character must have an Intelligence score of 9 or higher to become a Magic-User. The only weapons they become proficient with are the dagger and the walking staff (or cudgel). Magic-Users may not wear armor of any sort nor use a shield as such things interfere with spellcasting.

A first level Magic-User begins play knowing [read magic](allSpells.qmd#read-magic) and one other spell of first level. These spells are written in a spellbook provided by his or her master. The GM may roll for the spell, assign it as he or she sees fit, or allow the player to choose it, at his or her option. See the [Spells](spells.qmd#magic-user-spells) section for more details.

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **1** | 13 | 14 | 13 | 16 | 15 |
| **2-3** | 13 | 14 | 13 | 15 | 14 |
| **4-5** | 12 | 13 | 12 | 15 | 13 |
| **6-7** | 12 | 12 | 11 | 14 | 13 |
| **8-9** | 11 | 11 | 10 | 14 | 12 |
| **10-11** | 11 | 10 | 9 | 13 | 11 |
| **12-13** | 10 | 10 | 9 | 13 | 11 |
| **14-15** | 10 | 9 | 8 | 12 | 10 |
| **16-17** | 9 | 8 | 7 | 12 | 9 |
| **18-19** | 9 | 7 | 6 | 11 | 9 |
| **20** | 8 | 6 | 5 | 11 | 8 |

: Magic User Saving Throws {#tbl-save-mage}

## Thief


| Level | Exp. Points | Hit Dice |AB       |
|--|-----|--|---------|
| 1 | 0 | 1d4 |+1       |
| 2 | 1,250 | 2d4 |+1       |
| 3 | 2,500 | 3d4 |+2       |
| 4 | 5,000 | 4d4 |+2       |
| 5 | 10,000 | 5d4 |+3       |
| 6 | 20,000 | 6d4 |+3       |
| 7 | 40,000 | 7d4 |+4       |
| 8 | 75,000 | 8d4 |+4       |
| 9 | 150,000 | 9d4 |+5       |
| 10 | 225,000 | 9d4+2 |+5       |
| 11 | 300,000 | 9d4+4 |+5       |
| 12 | 375,000 | 9d4+6 |+6       |
| 13 | 450,000 | 9d4+8 |+6       |
| 14 | 525,000 | 9d4+10 |+6       |
| 15 | 600,000 | 9d4+12 |+7       |
| 16 | 675,000 | 9d4+14 |+7       |
| 17 | 750,000 | 9d4+16 |+7       |
| 18 | 825,000 | 9d4+18 |+8      |
| 19 | 900,000 | 9d4+20 |+8      |
| 20 | 975,000 | 9d4+22 |+8      |

Thieves are those who take what they want or need by stealth, disarming traps and picking locks to get to the gold they crave; or “borrowing” money from pockets, beltpouches, etc. right under the nose of the “mark” without the victim ever knowing.

Thieves fight better than Magic-Users but not as well as Fighters. Avoidance of honest work leads Thieves to be less hardy than the other classes, though they do pull ahead of the Magic-Users at higher levels.

The Prime Requisite for Thieves is Dexterity; a character must have a Dexterity score of 9 or higher to become a Thief. They may use any weapon, but may not wear metal armor as it interferes with stealthy activities, nor may they use shields of any sort. Leather armor is acceptable, however.

Thieves have a number of special abilities, described below. One Turn must generally be spent to use any of these abilities, though the GM may amend this as he or she sees fit. The GM may choose to make any of these rolls on behalf of the player, at his or her option, to help maintain the proper state of uncertainty. Also note that the GM may apply situational adjustments (plus or minus percentage points) as he or she sees fit; for instance, it's obviously harder to climb a wall slick with slime than one that is dry, so the GM might apply a penalty of 20% for the slimy wall.

| **Level** | Death Ray / Poison | Magic Wands | Paralysis / Petrify | Dragon Breath |Spells |
|----|---|----|----|---|---|---|
| **1** | 13 | 14 | 13 | 16 | 15 |
| **2-3** | 12 | 14 | 12 | 15 | 14 |
| **4-5** | 11 | 13 | 12 | 14 | 13 |
| **6-7** | 11 | 13 | 11 | 13 | 13 |
| **8-9** | 10 | 12 | 11 | 12 | 12 |
| **10-11** | 9 | 12 | 10 | 11 | 11 |
| **12-13** | 9 | 10 | 10 | 10 | 11 |
| **14-15** | 8 | 10 | 9 | 9 | 10 |
| **16-17** | 7 | 9 | 9 | 8 | 9 |
| **18-19** | 7 | 9 | 8 | 7 | 9 |
| **20** | 6 | 8 | 8 | 6 | 8 |

: Thief Saving Throws {#tbl-save-thief}

### Thief Abilities

| Thief Level | Open Locks | Remove Traps | Pick Pockets | Move Silently | Climb Walls | Hide | Listen |
|---|----|----|----|----|----|----|----|
| 1 | 25 | 20 | 30 | 25 | 80 | 10 | 30 |
| 2 | 30 | 25 | 35 | 30 | 81 | 15 | 34 |
| 3 | 35 | 30 | 40 | 35 | 82 | 20 | 38 |
| 4 | 40 | 35 | 45 | 40 | 83 | 25 | 42 |
| 5 | 45 | 40 | 50 | 45 | 84 | 30 | 46 |
| 6 | 50 | 45 | 55 | 50 | 85 | 35 | 50 |
| 7 | 55 | 50 | 60 | 55 | 86 | 40 | 54 |
| 8 | 60 | 55 | 65 | 60 | 87 | 45 | 58 |
| 9 | 65 | 60 | 70 | 65 | 88 | 50 | 62 |
| 10 | 68 | 63 | 74 | 68 | 89 | 53 | 65 |
| 11 | 71 | 66 | 78 | 71 | 90 | 56 | 68 |
| 12 | 74 | 69 | 82 | 74 | 91 | 59 | 71 |
| 13 | 77 | 72 | 86 | 77 | 92 | 62 | 74 |
| 14 | 80 | 75 | 90 | 80 | 93 | 65 | 77 |
| 15 | 83 | 78 | 94 | 83 | 94 | 68 | 80 |
| 16 | 84 | 79 | 95 | 85 | 95 | 69 | 83 |
| 17 | 85 | 80 | 96 | 87 | 96 | 70 | 86 |
| 18 | 86 | 81 | 97 | 89 | 97 | 71 | 89 |
| 19 | 87 | 82 | 98 | 91 | 98 | 72 | 92 |
| 20 | 88 | 83 | 99 | 93 | 99 | 73 | 95 |

**Open Locks** allows the Thief to unlock a lock without a proper key. It may only be tried once per lock. If the attempt fails, the Thief must wait until he or she has gained another level of experience before trying again.

**Remove Traps** is generally rolled twice: first to detect the trap, and second to disarm it. The GM will make these rolls as the player won't know for sure if the character is successful or not until someone actually tests the trapped (or suspected) area.

**Pick Pockets** allows the Thief to lift the wallet, cut the purse, etc. of a victim without the victim noticing. Obviously, if the roll is failed, the Thief didn't get what he or she wanted; but further, the intended victim (or an onlooker, at the GM's option) will notice the attempt if the die roll is more than two times the target number (or if the die roll is 00).

**Move Silently**, like Remove Traps, is always rolled by the GM. The Thief will usually believe he or she is moving silently regardless of the die roll, but those he or she is trying to avoid will hear the Thief if the roll is failed.

**Climb Walls** permits the Thief to climb sheer surfaces with few or no visible handholds. This ability should normally be rolled by the player. If the roll fails, the Thief falls from about halfway up the wall or other vertical surface. The GM may require multiple rolls if the distance climbed is more than 100 feet. See [Falling Damage](combat.qmd#falling-damage).

**Hide** permits the Thief to hide in any shadowed area large enough to contain his or her body. Like Move Silently, the Thief always believes he or she is being successful, so the GM makes the roll. A Thief hiding in shadows must remain still for this ability to work.

**Listen** is generally used to listen at a door, or to try to listen for distant sounds in a dungeon. The GM must decide what noises the Thief might hear; a successful roll means only that a noise *could* have been heard. The GM should always make this roll for the player. Note that the Thief and his or her party must try to be quiet in order for the Thief to use this ability.

Finally, Thieves can perform a **Sneak Attack** any time they are behind an opponent in melee and it is reasonably likely the opponent doesn't know the Thief is there. The GM may require a Move Silently or Hide roll to determine this. The Sneak Attack is made with a +4 attack bonus and does double damage if it is successful. A Thief usually can't make a Sneak Attack on the same opponent twice in any given combat.

The Sneak Attack can be performed with any melee (but not missile) weapon, or may be performed bare-handed (in which case [subduing damage](combat.qmd#subduing-damage) is done). Also, the Sneak Attack can be performed with the "flat of the blade;" the bonuses and penalties cancel out, so the attack has a +0 attack bonus and does normal damage; the damage done in this case is subduing damage.

## Combination Classes

To become a member of a combination class, a character must meet the requirements of both classes. Combination class characters use the best attack bonus and the best saving throw values of their original two classes, but must gain experience equal to the combined requirements of both base classes to advance in levels. Elves are the only characters eligible to be a member of one of these combination classes:

**Fighter/Magic-User:** These characters may both fight and cast magic spells; further, they are allowed to cast magic spells while wearing armor. These characters roll six-sided dice (d6) for hit points.

**Magic-User/Thief:** Members of this combination class may cast spells while wearing leather armor, and may use any weapon. These characters roll four-sided dice (d4) for hit points.