# Managing Encounters

## Wandering Monsters

*We had the foresight to bring several large sacks with us, and we swiftly filled them with coins and gems from beneath the sarcophagus. Without further delay we moved out, intent upon reaching the stairs to the surface and then returning to Morgansfort. But it couldn't be that easy...*

*On the way in, Barthal scouted ahead and we took our time, constantly on the lookout for monsters. On the way out, we threw caution to the wind, moving at full speed with Barthal watching behind us. So it was that Morningstar and I turned a corner and practically stepped on the first rank of a goblin patrol!*

*Once again I was caught flatfooted, but so were the goblins. Morningstar reacted more swiftly, striking down the first of the little monsters. You might think that parley would have been a better idea, but we had already tried that with these goblins without success... so I couldn't blame the Elf for striking first and asking questions later.*

*I raised the golden sword and waded into battle...*

## Dungeon Encounters

Besides "placed" monsters, dungeons usually contain wandering monsters. The Game Master may create special wandering monster tables for specific dungeons, or the general wandering monster tables (below) may be used.

In an average dungeon, a wandering monster encounter will occur on a roll of 1 on 1d6; the Game Master should check once every 3 turns. The circumstances of a specific dungeon may call for higher odds or more frequent (or possibly less frequent) wandering monster checks.

::: {.table-responsive}

| (1d12) | **Level 1** | **Level 2** | **Level 3** | **Level 4-5** | **Level 6-7** | **Level 8+** |
|----|-----|-----|-----|-----|-----|-----|
| 1 | Bee, Giant | Beetle, Giant Bombardier | Ant, Giant | Bear, Cave | Basilisk | Black Pudding |
| 2 | Goblin | Fly, Giant | Ape, Carnivorous | Caecilia, Giant | Black Pudding | Chimera |
| 3 | Green Slime* | Ghoul | Beetle, Giant Tiger | Cockatrice | Caecilia, Giant | Giant, Hill |
| 4 | Kobold | Gnoll | Bugbear | Doppleganger | Displacer | Giant, Stone |
| 5 | NPC Party: Adventurer | Gray Ooze | Doppleganger | Gray Ooze | Hydra | Hydra |
| 6 | NPC Party: Bandit | Hobgoblin | Gargoyle* | Hellhound | Lycanthrope, Weretiger* | Lycanthrope, Wereboar* |
| 7 | Orc | Lizard Man | Gelatinous Cube | Lycanthrope, Werewolf* | Mummy* | Purple Worm |
| 8 | Skeleton | NPC Party: Adventurer | Lycanthrope, Wererat* | Minotaur | Owlbear | Salamander, Flame* |
| 9 | Snake, Cobra | Snake, Pit Viper | Ogre | Ochre Jelly* | Rust Monster* | Salamander, Frost* |
| 10 | Spider, Giant Crab | Spider, Giant Black Widow | Shadow* | Owlbear | Scorpion, Giant | Vampire* |
| 11 | Stirge | Troglodyte | Tentacle Worm | Rust Monster* | Spectre* |  |
| 12 | Wolf | Zombie | Wight* | Wraith* | Troll |  |

::: 

## Wilderness Encounters

The Game Master should check for random encounters in the wilderness about every four hours of game time; this translates nicely to three night checks and three daytime checks. If your players choose to stand three night watches, you simply check for each watch; in the daytime, check morning, afternoon, and evening.

To check for a wilderness encounter, roll 1d6; on a roll of 1, an encounter occurs. If a wilderness encounter is indicated, roll 2d8 on the appropriate table below. The Game Master should think carefully about how the encounter happens; check for surprise in advance, and if the monster is not surprised, it may be considered to have had time to set up an ambush (at the GM's option).

| (2d8) | **Desert or Barren** | **Grassland** | **Inhabited Territories** |
|----|-----|-----|-----|
| 2 | Dragon, Blue | Dragon, Green | Dragon, Gold |
| 3 | Hellhound | Troll | Ghoul |
| 4 | Giant, Fire | Fly, Giant | Bugbear |
| 5 | Purple Worm | Scorpion, Giant | Goblin |
| 6 | Fly, Giant | NPC Party: Bandit | Centaur |
| 7 | Scorpion, Giant | Lion | NPC Party: Bandit |
| 8 | Camel | Boar, Wild | NPC Party: Merchant |
| 9 | Spider, Giant Tarantula | NPC Party: Merchant | NPC Party: Pilgrim |
| 10 | NPC Party: Merchant | Wolf | NPC Party: Noble |
| 11 | Hawk | Bee, Giant | Dog |
| 12 | NPC Party: Bandit | Gnoll | Gargoyle* |
| 13 | Ogre | Goblin | Gnoll |
| 14 | Griffon | Blink Dog | Ogre |
| 15 | Gnoll | Wolf, Dire | Minotaur |
| 16 | Dragon, Red | Giant, Hill | Vampire* |

| (2d8) | **Jungle** | **Mountains or Hills** | **Ocean** |
|----|-----|-----|-----|
| 2 | Dragon, Green | Dragon, White | Dragon, Sea |
| 3 | NPC Party: Bandit | Roc(1d6:1-3 Large, 4-5 Huge, 6 Giant) | Hydra |
| 4 | Goblin | Displacer | Whale, Sperm |
| 5 | Hobgoblin | Lycanthrope, Werewolf* | Crocodile, Giant |
| 6 | Centipede, Giant | Mountain Lion | Crab, Giant |
| 7 | Snake, Giant Python | Wolf | Whale, Killer |
| 8 | Elephant | Spider, Giant Crab | Octopus, Giant |
| 9 | Antelope | Hawk | Shark, Mako |
| 10 | Jaguar | Orc | NPC Party: Merchant |
| 11 | Stirge | Bat, Giant | NPC Party: Buccaneer (Pirate) |
| 12 | Beetle, Giant Tiger | Hawk, Giant | Shark, Bull |
| 13 | Caecilia, Giant | Giant, Hill | Roc (1d8: 1-5 Huge, 6-8 Giant) |
| 14 | Shadow* | Chimera | Shark, Great White |
| 15 | NPC Party: Merchant | Wolf, Dire | Mermaid |
| 16 | Lycanthrope, Weretiger* | Dragon, Red | Sea Serpent |

| (2d8) | **River or Riverside** | **Swamp** | **Woods or Forest** |
|----|-----|-----|-----|
| 2 | Dragon, Black | Dragon, Black | Dragon, Green |
| 3 | Fish, Giant Piranha | Shadow* | Alicorn (see Unicorn) |
| 4 | Stirge | Troll | Treant |
| 5 | Fish, Giant Bass | Lizard, Giant Draco | Orc |
| 6 | NPC Party: Merchant | Centipede, Giant | Boar, Wild |
| 7 | Lizardman | Leech, Giant | Bear, Black |
| 8 | Crocodile | Lizardman | Hawk, Giant |
| 9 | Frog, Giant | Crocodile | Antelope |
| 10 | Fish, Giant Catfish | Stirge | Wolf |
| 11 | NPC Party: Buccaneer | Orc | Ogre |
| 12 | Troll | Toad, Giant (see Frog, Giant) | Bear, Grizzly |
| 13 | Jaguar | Troglodyte | Wolf, Dire |
| 14 | Nixie | Blood Rose | Giant, Hill |
| 15 | Water Termite, Giant | Hangman Tree | Owlbear |
| 16 | Dragon, Green | Basilisk | Unicorn |

## City, Town or Village Encounters

It's important for the Game Master to remember that, unlike dungeon or wilderness environments, cities, towns and villages are busy places. During the day, most towns will have people on the streets more or less all the time; the absence of people on the streets is often an indication of something interesting. By night, much of the town will be dark and quiet, and encounters will be mostly Thieves or other unsavory types; but near popular eating (or drinking) establishments, people of all sorts are still likely to be encountered. The GM must make sure that his or her descriptions of the town environment make this clear; of course, this will also make it harder for the players to identify "real" encounters.

The GM is encouraged to create his or her own encounter tables for use in each city, town or village created (or assign encounters by other means if desired); however, a set of "generic" encounter tables are provided below for those times when such preparation has not been completed. Roll 2d6 on the table below to determine what sort of encounter occurs; a description of each type of encounter appears below the table.

| (2d6) | Day Encounter | Night Encounter |
|---|------|------|
| 2 | Doppleganger | Doppleganger |
| 3 | Noble | Shadow* |
| 4 | Thief | Press Gang |
| 5 | Bully | Beggar |
| 6 | City Watch | Thief |
| 7 | Merchant | Bully |
| 8 | Beggar | Merchant |
| 9 | Priest | Giant Rat |
| 10 | Mercenary | City Watch |
| 11 | Wizard | Wizard |
| 12 | Lycanthrope, Wererat* | Lycanthrope, Wererat* |

**Beggar** encounters will often begin with a single beggar approaching the party, but there will generally be 2d4 beggars in the area, and if any party member gives anything to the first beggar, the others will descend on the party like flies. Each beggar is 90% likely to be a normal man, and 10% likely to be a 1^st^ level Thief, possibly scouting for the Thieves Guild or a local gang.

**Bully** encounters will be with 2d4 young toughs; each is 70% likely to be a normal man, 30% likely to be a 1^st^ level Fighter. Bullies generally appear unarmed, depending on their brawling ability in a fight (but keeping a dagger or shortsword hidden, to be used in case the fight is going against them). Bullies can be a bit unpredictable, such that the GM may want to use a reaction roll to determine the leader's mood.

**City Watch** encounters will be with 2d6 watchmen, all 1^st^ level Fighters save for the squad leader, who will be from 2^nd^ through 4^th^ level. They will confront "suspicious-looking" characters, but generally will need a good reason before they attempt to arrest or otherwise interfere with player characters.

**Doppleganger** encounters will, of course, appear to be some other type of encounter; the GM should roll again to determine what the doppleganger is masquerading as. 1d6 dopplegangers will be encountered; any extra group members will be humans who do not know they are traveling in the company of shapeshifting monsters. If the party is "interesting" to the dopplegangers, one or more of the monsters will attempt to follow them and replace a party member (as described in the monster description). In many cases, player character parties will not discover the true nature of the encounter until much later.

**Giant Rat** encounters will generally involve alleys, the docks, or other "low" places. Rats are generally not dangerous unless provoked, but if surprised they may attack. See the monster description for details of this encounter type.

**Lycanthrope, Wererat** encounters will appear to be some other type of encounter, either another sort of "normal" encounter or a giant rat encounter (depending on the circumstances). Wererats are cowardly and will not attack a party of equal or larger size.

**Mercenary** encounters will involve 2d6 members of a mercenary company, going about some business or other. A mercenary leader may offer a position to Fighter-classed player characters if they have any reputation at all.

**Merchants** are a common feature of towns, and may be encountered performing any sort of business. As with mercenary encounters, merchants may offer jobs to interesting player characters, particularly those with good reputations. See **Creating an NPC Party**, below, for details on this type of encounter. (A merchant in a town may not have a full entourage as described below; the GM should use his or her discretion in creating the encounter.)

**Nobles** encountered may also offer positions to player characters, or possibly offer a reward for some dangerous task. Player characters with bad reputations may be confronted, ordered to leave town, or even arrested if the noble is able to call for the city watch. (See **Creating an NPC Party**, below, for details on this type of encounter.) A noble in a town may not have a full entourage as described below; the GM should use his or her discretion in creating the encounter.

**Press Gangs** will consist of 2d6 Fighters, all 1^st^ level except for one or two leaders of 2^nd^ through 5^th^ level. They will be armed with blunt weapons or possibly will fight with their bare hands, since their goal is to capture rather than kill player characters; however, it is likely that at least some members of a press gang will have daggers or swords on their persons in case a serious fight breaks out. A press gang will not confront a party of equal or greater size unless the party is obviously weakened, drunk, etc. If the party loses, they will awaken aboard a ship at sea or in a military camp (depending on whether sailors or soldiers captured them), unarmed and at the mercy of their captors.

**Priest** encounters will usually be similar to a group of pilgrims (see **Creating an NPC Party**, below, for details), though the group encountered will not be as large as would be encountered in the wilderness. Generally, a single priest of 1^st^ through 4^th^ level will be encountered, accompanied by 1d4 of the faithful.

**Shadow** encounters in a town will be much like the same encounter underground; see the monster description for details.

**Thief** encounters will be with a group of 1d6 Thieves, generally disguised as ordinary townsmen or sometimes as beggars. One Thief in the group will be from 2^nd^ to 4^th^ level, with the others being 1^st^ level only. They will seek to steal from the party, of course, unless watched very carefully.

**Wizard** encounters will involve a Magic-User of 4^th^ through 7^th^ level, accompanied by 1d4-1 apprentices of 1^st^ level. The GM must decide on the temperament and mood of the wizard.

## Creating An NPC Party

### **Adventurers**

A party of NPC adventurers will usually consist of 4-8 characters, as follows: 1d3 Fighters, 1d2 Thieves, 1d2 Clerics, and 1d2-1 Magic-Users. Usually the characters will all be of similar levels; after deciding what average level the party should be, you may wish to make a few of the characters lower levels (to reflect the usual "replacements" brought in when some characters die).

The Game Master must choose the race(s) of the NPC adventurers to suit the region they are found in (or come from). Probably 80% or more of adventurers are Human, 10% are Dwarves, 6% are Halfling and the remaining 4% Elvish. If the NPC adventurer party is evil, the GM may choose to replace some party members with humanoid monsters such as orcs, hobgoblins, or gnolls.

The party may be rivals with the player characters, vying for the same treasures, or they may actually be enemies, evil marauders that the player characters must defeat. It is, of course, possible that the NPC adventurers are allied or otherwise friendly with the player characters, but this may make things too easy for the players.

### **Bandits, Brigands, and Highwaymen**

A party of bandits will generally consist of 2d12 1^st^ level Fighters and 1d6 1^st^ level Thieves, led by a Fighter or Thief of 2^nd^ to 5^th^ level (1d4+1) or by one of each class (if there are 11 or more 1^st^ level members total). In the wilderness, bandits will generally have horses or other steeds appropriate to the terrain (stolen, of course) as well as light armor, swords and bows or crossbows. Determine magic items as given below for the leaders only; rank-and-file members will not normally have magic items.

In their lair or hideout, a party of bandits will generally have type A treasure (with magic items omitted since they will have already been generated using the rules below).

### **Buccaneers and Pirates**

The difference between buccaneers and pirates is largely a question of what they wish to be called; whatever you call them, they are waterborne equivalents of bandits, attacking other ships or raiding coastal towns for plunder.

A buccaneer party will consist of 3d8 1^st^ level Fighters, led by a Fighter of 3^rd^ to 6^th^ level (1d4+2) and 1d3 Fighters of 2^nd^ to 5^th^ level. All will be experienced at handling ships, of course. They will be unarmored or armored only in leather, and will be armed with swords and bows or crossbows.

Seagoing pirates may appear in larger numbers, but the number of leader-types will be similar to that given above. Generate magic items for leaders only as described below. A shipload of pirates or buccaneers will have a type A treasure, with magic items omitted (since magic items will already have been rolled for the NPCs); the treasure may not be aboard the ship, however, as pirates often prefer to bury their treasures on islands. In such a case, the Captain or one of his mates will have a treasure map leading to the location of the treasure.

### **Merchants**

Merchants must often transport their wares through wilderness areas. Roughly half of the time (50%), a land-bound merchant party will be led by a single wealthy merchant; other merchant parties will consist of 1d4+1 less wealthy merchants who have banded together for their own safety. There will be 2d4 wagons (but at least one per merchant) drawn by horses or mules. Each wagon is driven by a teamster who is a normal man, usually unarmored and armed with a dagger or shortsword. The caravan will employ 1d4+2 first-level Fighters and 1d4 second-level Fighters as guards.

If encountered at sea, a merchant party will generally consist of a single ship owned or rented by a single merchant. The ship will have a crew of 2d8+8 regular crewmen, who are normal men, unarmored and armed with clubs, daggers or shortswords; the Captain, First Mate, and other officers are taken from this number. Large ships may require larger crews. 1d4+2 first-level Fighters and 1d4 second-level Fighters will be aboard as guards, just as with a caravan.

Besides the valuable but undoubtedly bulky trade goods transported by the merchant caravan or ship, such a party will also have a type A treasure, with magic items omitted; it may be in one chest, or spread out among the wagons.

### **Nobles**

A noble party will consist of a noble (of course), possibly accompanied by a spouse (also a noble, of course) and/or one or more children. Each adult noble will have at least one attendant (assistant, lady-in-waiting, etc.).

Lower-ranking nobles (such as barons) will have a single wagon or carriage, drawn by fine horses; higher-ranking nobles will have two or more wagons. The noble may be mounted on a warhorse, though he or she may choose to ride in a carriage part of the time. Each carriage or wagon will have a teamster, who in this case will be a 1^st^ level Fighter in chainmail with a longsword. At least two mounted Fighters of 1^st^ through 4^th^ level will be with the noble as guards; again, higher ranking nobles will have more guards. Guards will generally be armed with longswords and possibly lances, armored in platemail, and their warhorses will usually be barded with chainmail. Determining the exact number of guards is left to the GM in this case. The normal chances for magic items apply, of course.

A noble will usually be traveling with a little spending money; a type A treasure should be rolled to represent this. In this case, do not omit the magic items, as nobles will generally be more wealthy than the average party of men.

Nobles are usually (70%) normal men; otherwise, roll 1d10: 1-6 indicates a Fighter, 7-8 indicates a Magic-User, 9 indicates a Cleric, and 10 indicates a Thief. (Clerical "nobles" are bishops, archbishops, and the like.) Roll 2d4-1 for the level of each "classed" noble.

### **Pilgrims**

A party of pilgrims is on its way to (or from) a major religious locale or activity. Such a party will be led by a 1d4 Clerics of level 1-4 (roll for each).

The remainder of the party is rather random in nature; most pilgrim groups include 3d6 normal men (or women if the religion allows women to go on pilgrimages), 1d6 Fighters of level 1-4 (roll for each) with chainmail and longsword, and 1d4 Thieves of level 1-4 (each of whom may be a genuine devout person, or possibly just on the lam). There is also a 50% chance of a single Magic-User of level 1-4 being with the party.

Pilgrims usually travel light, carrying a single bag each and walking or riding mules or horses. The pilgrim party will most likely be bringing offerings of some sort to their destination; generate a type A treasure for this purpose. If magic items are indicated, they will most likely not be used by any of the NPCs as they have already been dedicated to the god or pantheon.

### **Magic Items for NPCs**

NPCs will generally have magic items in proportion to their class and level; assume a 5% chance per level that any given Fighter, Thief or Cleric NPC will have a magic weapon or magic armor (roll for weapon and armor separately for each NPC). Regardless of level, a roll of 96-00 should be considered a failure. Magic-Users will have a Ring of Protection (roll the bonus as usual for the item) on a roll of 4% per level, and a magic dagger or walking staff on a roll of 3% per level.

In addition, assume a 2% per level chance that any given character will have a potion, and 3% per level that a Cleric or Magic-User will have a scroll of some sort.

Finally, add up the levels of all members of the party, and use this number as a percentage chance that a Miscellaneous Magic item will be found among them. If the roll is made, divide the number by two and roll again; if the second roll is made, two such items are found. If the party has more than 3 members, you might wish to divide the number in half again and roll for a third such item. Assign the Miscellaneous Magic item or items to whichever party members seem most appropriate, or roll randomly if you can't decide.

### **Demi-Human Parties**

It is assumed above that NPC parties will be Human, or predominantly so; but the Game Master may choose to present parties of Elves, Dwarves, or Halflings from time to time. In general, a party of demi-humans will be homogeneous.... an Elf party would consist of all Elves, for instance. If encountered in the territory of another race, the demi-human party might include a guide hired to lead them to their destination. For example, the Elf party mentioned above might hire a Human guide to help them when traveling through a Human country.

The Game Master may simply use the figures given above when generating such parties. One thing that the GM must decide is whether or not the "normal men" rules apply to demi-humans... are there "normal elves" for instance? This decision is left to the GM. If there are such characters, they will have the same racial abilities as others of their race, but will fight with an Attack Bonus of +0 just as normal men do. If there are no such characters in the campaign world, then simply substitute 1^st^ level Fighters for the normal men listed above.

## Dealing with Players

### Character Creation Options

The standard character creation rules call for rolling 3d6 for each Ability Score in order. Players may complain that they can't create the sort of characters they want to play. Here are several options you may choose from if you wish to make things easier for your players. Note that the players must not be allowed to demand these options; it's purely the decision of the Game Master.

**Point Swapping:** Allow the player to "move" points from one Ability Score to another, at a rate of -2 to one score for each +1 added to the other. The maximum score is still 18 (or the racial maximum if lower), and the player should not be allowed to lower any score below 9.

**Score Swapping:** Let the player exchange any two Ability Scores, once per character.

**The Full Shuffle:** Let the player arrange the six Ability Score values as he or she wishes. This allows the most customization for the player, but on the other hand you may find that all player characters in your campaign begin to look very much alike. It's not uncommon for players to "dump" the lowest statistic in Charisma, for instance.

### Hopeless Characters

Sometimes a player will look at the six scores rolled, and declare the character "hopeless." The Game Master should always allow the player to scrap a character with less than 9 in the first four scores (since all four classes would be unavailable to that character). However, you as the Game Master might choose to allow the player to reroll a character with scores that are overall below average even if the character isn't as "hopeless" as this.

Here's a suggestion: Sum up the Ability Score bonuses or penalties that apply to the character. If the total is negative, consider the character below average, and allow the player to scratch the entire set of scores and reroll. If the total is zero, the character is "average," and the player probably should go ahead and play the character as rolled. Obviously, if the total is greater than zero, the character should be played as rolled.

As an alternative, a player who rolls a set of ability scores where the total of all the bonuses and penalties is negative may be allowed to "flip" the scores by subtracting all the scores (not just the "bad" ones) from 21. This makes a 3 into an 18, for example, and will result in a total of bonuses and penalties that is positive if the total was previously negative.

### Acquisition of Spells

Clerics have an obvious advantage over Magic-Users, in that, in theory, they have access to any spell of any level which they can cast. However, note that Clerics are limited in their spell selection based on their deity, faith or ethos; for instance, a Cleric of the goddess of healing should not be surprised that his or her deity refuses to grant reversed healing spells. If a Cleric prays for a spell that is not allowed, the Game Master may choose to grant the character a different spell, or optionally (if the deity is angered) no spell at all for that "slot."

Magic-Users begin play knowing two spells, **read magic** plus one other (unless the GM grants more starting spells). Each time the character gains a level, he or she gains the ability to cast more spells; in addition, every other level the Magic-User gains access to the next higher level spells (until all levels are available). However, gaining the ability to cast these spells does not necessarily mean the Magic-User instantly learns new spells.

Magic-Users may learn spells by being taught by another Magic-User, or by studying another Magic-User's spellbook. If being taught, a spell can be learned in a single day; researching another Magic-User's spellbook takes one day per spell level. In either case, the spell learned must be transcribed into the Magic-User's own spellbook, at a cost of 500 gp per spell level transcribed.

A Magic-User may add a new spell of any level he or she may cast at any point; however, spells of higher levels may not be learned or added to the Magic-User's spellbook. The Magic-User must find a teacher or acquire a reference work (such as another Magic-User's spellbook) in order to learn new spells, and the cost of such is in addition to the costs given above. Often a Magic-User will maintain a relationship with his or her original master, who will teach the character new spells either for free or in return for services. Sometimes two Magic-Users will agree to exchange known spells. In many cases the only option available to a Magic-User will be to pay another Magic-User (often an NPC) anywhere from 100 gp to 1000 gp per spell level in return for such training.

Magic-Users may also create entirely new spells (or alter existing spells); see the Magic Research rules, below, for details.

### Weapon and Armor Restrictions

Several races and classes have weapon and/or armor restrictions applied to them. What happens when a player declares that his or her character is going to use a prohibited weapon or wear prohibited armor?

**Clerics:** The prohibition against edged weapons is a matter of faith for Clerics. Therefore, if a Cleric uses a prohibited weapon, he or she immediately loses access to his or her spells as well as the power to Turn the Undead. A higher-level NPC Cleric of the same faith must assign some quest to the miscreant which must be completed in order for the fallen Cleric to atone and regain his or her powers. If unrepentant, the character is changed permanently from a Cleric to a Fighter. Refigure the character's level, applying the current XP total to the Fighter table to determine this. Hit points and attack bonus remain the same; change the attack bonus only after a new level is gained as a Fighter, and roll Fighter hit dice as normal when levels are gained.

**Magic-Users:** These characters are simply untrained in any weapon other than those normally allowed to them, and should suffer a -5 attack penalty when using any prohibited weapon. A Magic-User in armor can't cast spells at all; any such attempt fails, and the spell is lost.

**Thieves:** Wearing armor heavier, more restrictive and/or noisier than leather armor prevents the use of any Thief ability, including the Sneak Attack ability. Thieves may choose to wear such armor, but this only makes them a poor excuse for a Fighter.

**Dwarves and Halflings:** These characters are prohibited from using large weapons, mainly due to their small stature and relatively low weight. It's hard to swing a weapon when the weapon is trying to swing you. If such a character tries to use a prohibited weapon, the Game Master may either apply a -5 attack penalty based on the difficulty of using the weapon, or alternately declare the attempt unsuccessful, at his or her option.

### Judging Wishes

Wishes are one of the most potentially unbalancing things in the game. With a carefully worded wish, a player character can make sweeping, dramatic changes in the game world, possibly even rewriting history. Before allowing the player characters in your game access to even one wish, think about how you will deal with it.

Wishes are granted by a variety of beings. Even when a wish comes from a device (a ring or a sword, for instance), some extradimensional being, god or devil or whatever, has placed that wish in the device. A wish will tend to further the goals of the granting being; if the granter is an evil efreeti, for instance, it will attempt to twist the meaning or intent of the wish so that it does not really accomplish what the player character wants. On the other hand, if the granter is one of the good powers, it will grant the wish as intended so long at the player character isn't being greedy or spiteful.

Game balance is the main issue that must be considered. Using a wish to heal the entire party, teleport everyone without error to a distant location, or to avoid or redo a catastrophic battle, is reasonable. A wish that a character be restored to life and health is reasonable, but a wish that not only restores but also improves the character is not.

In general, a wish is granted with at least literal accuracy... the words of the wish must be fulfilled. The exception is wishes that are unreasonable for game balance purposes; they are still at least literally interpreted, but may be only partially granted. In the last example above, for instance, the granting power would likely restore the character to life and health but ignore the "improvements" wished for.

## Optional Rules

### Death and Dying

The rules state that, at zero hit points, the character is dead. If this is too harsh for you, here are several approaches to changing the situation:

**Raise Dead:** The first approach doesn't change the rules a bit. Arrange matters so that characters killed in an adventure can be easily **raised** (but at a substantial cost). This not only "deals" with the mortality issue, it also soaks up excess treasure, preventing the player characters from becoming too rich to be interested in adventuring. It also tends to reward the cautious (since they get to keep their gold more often).

What if the characters don't have enough money when they die to afford to be **raised**? Allow the local religious establishment to **raise** dead adventurers in return for their indenture... that is, the adventurers, upon being restored to life, owe the church or temple the money it would have cost to be **raised**, *or an equivalent service*. Thus, the local religious leaders would have a ready pool of adventurers to undertake dangerous missions for them.

But the adventurer(s) are dead... how can they agree to the indenture? There are two options: the priests can use **speak with dead** to attain agreement, or the adventurers can sign an agreement with the church before leaving on the potentially dangerous adventure. The latter might even be considered a standard procedure in some places.

**Save vs. Death:** The first actual rule alteration is to allow characters reduced to zero hit points to save vs. Death Ray to avoid death. If the save is failed, the character is immediately dead, just as in the normal rules. If the save is made, the character remains alive for 2d10 rounds; if the character's wounds are bound (or he or she receives healing magic) within this time frame, death is averted. The character remains unconscious for the full 2d10 rounds rolled, either dying if left untreated or awakening if his or her wounds are bound.

Binding the wounds of the dying character stabilizes him or her at zero hit points. Non-magical healing will require a full week to restore the first hit point; after this, healing proceeds at the normal rate.

Magical healing will restore the character to whatever total is rolled on the healing die roll (up to the usual maximum of course).

Note that any spellcaster reduced to zero hit points who subsequently survives loses all remaining prepared spells.

This rule might be combined with the suggestions under Raise Dead, above.

**Negative Hit Points:** Instead of stopping at zero hit points, keep track of the current negative figure. At the end of each round after he or she falls, the character loses an additional hit point. If a total of -10 is reached, the character is dead. Before this point is reached, the character may have his or her wounds bound and/or receive magical healing, which will stabilize the character. The injured character may not move more than a few feet without help, nor fight, nor cast spells, until his or her hit points are again greater than zero. This rule should *not* be combined with the Save vs. Death option.

Just as with the **Save vs. Death** rule, spellcasters who survive being reduced to zero or negative hit points lose all currently prepared spells.

As a further option, the GM may choose to use a negative number equal to the character's Constitution score rather than a straight -10.

### "Save or Die" Poison

Poisons, as described in the Encounter and Monster sections, kill characters instantly. Game Masters may find this makes the mortality rate of player characters a bit too high. On the other hand, poisons **should**be scary. Here's an optional rule which may make things a bit easier without entirely removing the fear from poison:

Where a "save or die" poison is indicated, the victim must make a save vs. Poison or suffer 1d6 damage per round for 6 rounds, starting the round following the exposure to the poison; this is an average of 21 points of damage, but even a first level character might survive with a combination of luck and healing magic. The GM may create poisons which vary from these figures, of course. If the **Negative Hit Points** optional rule is being used, it is suggested to increase the poison duration to 10 rounds (an average 35 points).

### Awarding Experience Points for Treasure Gained

style="position: absolute; top: 0in; left: 0in" The Game Master may also assign experience points for treasure gained, at a rate of 1 GP = 1 XP. This is optional; GMs wishing to advance their players to higher levels more quickly may choose to do this, while those preferring a more leisurely pace should omit it. If experience is awarded for treasure, it should be awarded only for treasure acquired and returned to a place of safety. Alternately, the GM may require treasure to be spent on training in order to count it for experience. This is a highly effective way to remove excess treasure from the campaign.

### Ability Rolls

There will be times when a player character tries to do something in the game that seems to have no rule covering it. In some of those cases, the only attribute the PC has that seems appropriate may be an Ability Score. Here is a suggested method for making rolls against Ability Scores that still gives better odds to higher level characters:

The player rolls 1d20 and adds his or her Ability Bonus for the score the GM thinks is most appropriate, as well as any situational bonus or penalty the GM assigns. Consult the following table. If the total rolled is equal to or higher than the given Target number, the roll is a success.

| **Level** | **Target** |
|------|-------|
| NM or 1 | 17 |
| 2-3 | 16 |
| 4-5 | 15 |
| 6-7 | 14 |
| 8-9 | 13 |
| 10-11 | 12 |
| 12-13 | 11 |
| 14-15 | 10 |
| 16-17 | 9 |
| 18-19 | 8 |
| 20 | 7 |

### Preparing Spells from Memory

Sometimes a Magic-User will want to prepare spells, but his or her spellbook may be unavailable; this includes when the book has been destroyed or stolen as well as times when the Magic-User has been captured or trapped.

A Magic-User can always prepare **read magic** from memory. Other spells require an Intelligence ability roll, as described above, with the spell level as a penalty on the die roll.

Failure exhausts the spell slot being prepared, just as if it had been successfully prepared and then cast; so if a 5^th^ level Magic-User attempts to prepare **fireball** from memory, and fails, he or she will have no 3^rd^ level spells for the day.

### Thief Abilities

Some players of Thieves may wish to have more control over their Thief abilities. If you study the Thief Abilities table, you'll discover its secret: from levels 2-9, the Thief improves 30 percentiles (total) each level; from levels 10-15, 20 percentiles; and from level 16 on, 10 percentiles. If you wish to allow Thief customization, simply let the player allocate these points as he or she wishes rather than following the table. Allow no more than 10 percentiles to be added to any single Thief ability per level gain. Note also that no Thief ability may be raised above 99 percent.

## Magical Research

### General Rules for Research

At some point a Magic-User or Cleric may wish to start creating magic items or inventing spells. This is termed **magical research**. For any research, Magic-User must have a tower or laboratory, while a Cleric requires a properly consecrated temple or church of his or her faith. In addition, there will be a cost for the creation of each item, a minimum time required to create it, and a given chance of success. If the roll fails, generally the time and money are wasted and the procedure must be started again from the beginning; however, consult the detailed rules below for exceptions.

*In almost all cases, the Game Master should make this roll in secret.* There are many situations where the character (or the player) should not know whether the roll has actually failed, or whether the GM has decided the research is impossible for the character. The GM may decide to tell the player that the research is impossible if the roll succeeds; if the roll is a failure, that is all the player should be told.

In general, Clerics may only create magic items reproducing the effects of Clerical spells; Clerics may also make enchanted weapons and armor, even those sorts which they may not use themselves (since they may be creating weapons or armor for other followers of their faith). Magic-Users may create any sort of magic item except for those reproducing Clerical spells for which no equivalent Magic-User spell exists.

Time spent doing magical research must be eight-hour workdays with interruptions lasting no more than two days. Longer interruptions result in automatic failure of the project.

The GM may, if he or she so desires, grant Experience Points to characters who successfully complete magical research. It is suggested that the rate of such awards be 1 XP per 10 gp spent on the research. This award may be granted for all research, or only for creation of magic items, or not at all if the GM prefers to emphasize adventuring for advancement purposes.

### Spell Research

Researching new spells is the most common type of magical research. A Magic-User may research a standard spell, removing the need for a teacher or reference; alternately, a Cleric or Magic-User may research an entirely new spell. Of course, no character may invent or research a spell of a level higher than he or she can cast.

If the character is inventing a spell outright, the GM must determine the spell's level and judge whether or not the spell is possible "as is." The GM does not have to tell the player whether the spell is possible, and in fact this may be preferable.

The cost to research a spell is 1,000 gp per spell level for "standard" spells, or 2,000 gp per spell level for newly invented spells; in either case, one week is required per spell level to complete the research. The chance of success is 25%, plus 5% per level of the character, minus 10% per level of the spell; the maximum chance of success is 95%.

If the research roll is successful, the character may add the spell to his or her spellbook (if a Magic-User) or may subsequently pray for the spell (if a Cleric). On a failure, the money and time are spent to no avail. Clerics of the same deity, faith or ethos may teach each other the prayers required to access new spells; this takes one hour per spell level. The procedure to exchange spells with other Magic-Users has already been explained (under Acquisition of Spells, above).

As mentioned above, the GM may decide that a proposed new spell is not "correct" for his or her campaign; too powerful, too low in level, etc. Rather than tell the player this, there are two strategies that may be used.

First, the Game Master may decide to revise the spell. If the roll is a success, the GM then presents the player with a revised writeup of the spell, adjusted however the GM feels necessary for game balance purposes.

The alternative, more appropriate when the GM believes the spell should be higher level than the player character can cast, is to make the roll anyway. If the roll fails, that is all the player needs to know; but if it succeeds, the GM should then show the player the revised version of the spell and explain that the character may try again when he or she attains a high enough level to cast it. In this case, the GM may allow the character to reduce either the time or the cost by half when the research is attempted again at the higher level.

### Magic Item Research

Any character who wishes to create magical items must know all (if any) spells to be imbued in the item. Items that produce effects not matching any known spell may require additional research (to devise the unknown spell) if the GM so desires.

Some magic items require one or more special components that cannot usually be bought. Special components can only be used once on such a project. For example, the GM might require the skin of a displacer to create a **cloak of displacement**, or red dragon saliva to create a **wand of fireballs**. Note that there are specific rules for components under Other Magic Items, below.

Special component requirements are entirely at the option of the Game Master, and are usually employed to slow the creation of powerful magic items that might tend to unbalance the campaign. It's also a good way to lead the spellcaster (and his party) into dangerous adventures.

### Chance of Success

Unless given differently below, the base chance of success creating a magic item is 15% plus 5% per level of the spellcaster, plus the spellcaster's full Intelligence (if a Magic-User) or Wisdom (if a Cleric). Thus, a 9^th^ level spellcaster with a 15 Prime Requisite has a base chance of 75%.

### Spell Scrolls

A spellcaster may create a scroll containing any spell he or she has access to (for a Magic-User, spells in his or her spellbook; for a Cleric, any spell the character might successfully pray for). The cost is 500 gp per spell level, and the time required is 1 day per spell level.

Reduce the chance of success based on the level of the spell being inscribed, at a rate of -10% per level.

If the roll fails, the enchantment of the scroll has failed; however, if the caster tries again to inscribe the same spell, either the cost or the time is reduced by half (at the character's option).

### Other Single-Use Items

Scrolls (other than spell scrolls), potions, and a few other items (such as the **rod of cancellation**) are single-use items. These items may be created by Magic-Users or Clerics of the 7^th^ level or higher.

The chance of success is as given for scrolls, above, when the item being created reproduces a known spell (or when the GM decides a spell must be created, as described above). For other types of items, the GM should assign a spell level as he or she sees fit, and the cost and time required is doubled (making up for the spell research or knowledge required for spell-reproducing items). The time required is one week plus one day per spell level (or equivalent), and the cost to enchant the item is 50 gp per spell level, per day.

Potions are a special case; the character creating a potion may create a large batch, consisting of several doses, which may be bottled in separate vials or combined in a larger flask. For each additional dose created at the same time, reduce the chance of success by 5% and increase the time required by one day. Note that increasing the time required will directly increase the cost. If the roll to create the item fails, the entire batch is spoiled.

### Permanent Magic Items

Creating permanent magic items (rings, weapons, wands, staves, and most miscellaneous magic items) requires a Magic-User or Cleric of the 9^th^ level or higher.

When enchanting an item with multiple abilities, each ability of the item requires a separate roll for success; the first failed roll ends the enchantment process. Such an item will still perform the powers or effects already successfully enchanted into it, but no further enchantment is possible.

Permanent magic items, including weapons (described in detail below), must be created from high-quality items. The cost of such items will generally be ten times the normal cost for such an item.

### Enchanting Weapons

The base cost of enchanting a weapon or armor is 1,000 gp per point of bonus. For weapons with two bonuses, divide the larger bonus in half (don't round) and add the smaller bonus; thus, a **sword +1, +3 vs. dragons** would cost 2,500 gp to enchant. Enchanting a weapon takes one week plus two days per point of bonus; thus, the sword described would require twelve days to enchant.

Reduce the chance of success by 10% times the bonus; so, a **sword +1** would reduce the base chance 10%, while the **sword +1, +3 vs. dragons** described above would reduce the base chance 25%. Further, the chance of success may be increased 25% by doubling the cost and time required (this decision must be announced before the roll is made).

For weapons having additional powers, combine the rules above with the rules for creating permanent items. All enchantments must be applied in a single enchantment "session."

### Other Magic Items

Magic items can have several **features**. Each feature added to a magic item increases the cost and the time required, and decreases the chance of success. The features are as follows:

**Creates a spell or spell-like effect**: This is the basic feature of all non-weapon magic items. The base cost of this enchantment is 500 gp per spell level; time required is five days plus two days per level. If the magic item has multiple spell or spell-like effects, add the cost and time figures together. The chance of success is reduced 5% per spell level.

**Has multiple charges**: This includes, of course, wands and staffs, but several other magic items would also have charges. Each spell or spell-like effect normally has a separate pool of charges (but see next). The table below shows the various maximum charge levels and the associated cost, time and chance adjustments:

| Charge Level | Cost per Charge | Charges per Day | Chance |
|-------|--------|-------|-------|
| 2-3 | +150 gp | 1 | - 5% |
| 4-7 | +125 gp | 2 | - 10% |
| 8-20 | +100 gp | 3 | - 20% |
| 21-30 | +75 gp | 4 | - 30% |

When using the table above, don't count the first charge for cost or time purposes. Note that each separate pool of charges in the item must be figured separately.

**Item can be recharged:** Figure the additional cost and time, and the penalty to the chance of success, for rechargeable items as being exactly twice the figures from the table above; so, creating a rechargeable item with 3 charges costs 600 gp more rather than 300 gp more, and takes two days per charge (or four extra days); the chance of success is lowered 10% rather than 5%.

**Item recharges itself:** Creating a self-recharging item is expensive; apply the following adjustments to the charge cost, time and chance for items that recharge automatically. Note that self-recharging items are never "rechargeable" in that they may not be recharged other than by themselves.

| Charging Rate | Cost | Time | Chance |
|-------|--------|-------|-------|
| 1 per day | x 3 | x 2 | - 10% |
| All per day | x 5 | x 3 | - 30% |
| All per week | x 4 | x 2 | - 20% |

**Charges are generic:** This means that all the effects of the item draw power from the same pool of charges; most Magic-User staffs are in this category. Items with generic charges are automatically rechargeable; don't apply the normal adjustments for this feature. Instead, combine the normal costs for the charge pools of each effect (which must all have the same number of charges), and then divide the charge cost, time and chance adjustments by two. Thus, two effects sharing one pool costs the same as a single effect with a single pool.

**Item may be used by any class:** By default, magic items may only be used by the class that created them; so a **wand of fireballs** is normally usable only by Magic-Users, or a **staff of healing** only by Clerics. This feature allows the item to be used by any class of character, and involves assigning simple command words and gestures to the item. Adding this feature costs 1,000 gp per effect. Note that all the item's effects do not have to be covered; it is possible to create an item where some effects may be used by any class, but other effects may only be used by the creator's class.

**Item operates continuously or automatically:** This feature supersedes both the charges and item use features. The item works whenever properly worn, or activates automatically when required. A **ring of fire resistance** is a good example; also, the **ring of invisibility** is in this category. Adding this feature multiplies the final cost and time figures by five and applies a 40% penalty to the chance of success.

Each feature above applied to a magic item will require a valuable, rare and/or magical material to support the enchantment. For example, a wand of fireballs has a spell effect that is powered by charges; these are two relatively ordinary features, so the Magic-User creating the item proposes a rare wood for the shaft and a 1,000 gp value ruby for the tip. The GM may, of course, require something more rare or valuable if the magic item is particularly powerful.

The base cost of a spell effect feature can be reduced by 25% by applying limits to the ability. For example, a **ring of charm dryad** is an example of limited **charm person** spell effect, which would qualify for the deduction. This does not affect the chance of success or the time required.

Weapons which are to be enchanted with additional powers other than the normal bonus require combining the standard weapon enchantment rules with the rules given above. Perform the weapon enchantment first; if it is successful, then the character enchanting the weapon must immediately (within two days, as previously explained) begin the spell or spell-like power enchantment process. Failure of the second procedure does not spoil the weapon enchantment.

### Cursed Items

Some cursed items, such as cursed scrolls, are created that way specifically by the spellcaster. The difficulty of creating such an item is roughly the same as the difficulty of creating a spell scroll of **bestow curse**.

Other cursed magic items may be the result of a failed attempt to create a useful item. The GM must decide whether or not a failed research project will actually create a cursed item.
