# Crafting Adventures


## Designing a Dungeon Adventure

### 1\. Think About Why

When creating a dungeon, the first question you must answer is: Why will your player characters risk going into this dangerous dungeon full of monsters and traps?

Here are some possible scenarios:

**To Explore the Unknown:** This is common in pulp fiction. One or more of the player characters has heard of some ancient site, and wishes to explore purely for knowledge. Possibly some of the other player characters are involved for other reasons.

**To Battle An Evil Incursion:** Goblins are raiding farms in the area, and the Baron has offered a reward for stopping the raids; the player characters are happy to help.

**To Rescue A Kidnapped Victim:** Some friend of the player characters has been kidnapped, and they must sneak into or storm the villain's tower/cave/dungeon to rescue the victim. Or, perhaps, the victim is the son or daughter of the local Baron or a wealthy merchant who offers a reward for the safe return of his or her offspring.

**To Fulfill A Quest:** The local church, to whom the player characters owe a favor, would like an ancient relic recovered from a lost mountain fortress, and the High Priest asks them to look into it; or some similar task might be assigned, depending on who the player characters owe a favor.

**To Get Loot:** This is a surprisingly common scenario (well, perhaps not so surprising). The dungeon is rumored to contain a hidden treasure of great value, and the first characters to find it will be rich! Of course, the treasure might not be *that* huge, and might be guarded by any number of horrific monsters...

**To Escape Confinement:** The player characters have been captured by an enemy, and find themselves incarcerated without their weapons, armor, or equipment. This scenario must be used with care, as the GM must not be seen to be "railroading" the characters into the adventure.

There are many other possible scenarios, and each has many variations. Knowing the answer to this question will make the next questions easier to answer.

### 2\. What Kind Of Setting Is It?

Is the dungeon beneath a ruined fortress, or an ancient wizard's tower? Or perhaps it's a natural cave, which has been expanded by kobolds... or the tomb of an ancient barbarian warlord, guarded by undead monsters... there are many possibilities.

### 3\. Choose Special Monsters

Now you know why the player characters want to go there (or why they will, when they learn of the dungeon), and you know what sort of place it is. Next, decide what special monsters you will place within. For instance, the natural cave expanded by kobolds contains kobolds, obviously, while the warlord's tomb contains some undead, zombies and skeletons perhaps.

### 4\. Draw The Dungeon Map

Dungeon maps can be drawn on graph paper in pencil, or created on the computer with any of a broad variety of dungeon-drawing programs. (If you like the design of the maps in the official Basic Fantasy RPG adventure modules, be sure to visit www.basicfantasy.org and try out our map designer, MapMatic +2.) When creating a dungeon for personal use, there is certainly no good reason not to use pencil and paper. Below is an example of a hand-drawn dungeon map, with the various symbols noted:

### 5\. Stock The Dungeon

"Stocking" the dungeon refers to assigning contents to each room. There are several possibilities; a room might contain a monster (which might or might not have treasure), a trap (which might guard a treasure, or might not), an "unguarded" treasure, a "special" (something other than a monster, trap, or treasure; often a puzzle of some sort), or be "empty."

The GM may choose the contents of any room, or may roll on the table below:

| d% | Contents |
|-----|-------|
| 01-16 | Empty |
| 17-20 | Unguarded Treasure |
| 21-60 | Monster |
| 61-84 | Monster with Treasure |
| 85-88 | Special |
| 89-96 | Trap |
| 97-00 | Trap with Treasure|

An **unguarded treasure** will generally be hidden (such as in a secret room, inside an unusual container, etc.) or protected by a trap (a poison needle in the lock of a chest, or a poison gas canister that explodes if the container is opened, or something similar); such a treasure might even be hidden **and** trapped! Again, some sort of saving throw should be allowed if a trap is used. It's not a bad idea to hide a treasure so well that the player characters are unlikely to find it; don't be concerned if they don't. If you give away the location of all your unguarded treasures, your players will not appreciate it properly when they manage to find one by cleverness or luck.

A **monster** might be selected by the GM or rolled on the random encounter tables. It's traditional that the first level (below ground) contains monsters of 1 hit die or less, the second level contains monsters of around 2 hit dice, and so on, but the GM may choose to arrange his or her dungeon in any way desired.

A **monster with treasure** might indicate a lair, or it might be a group of monsters carrying loot, possibly camping for some reason before moving on.

A **trap** is, obviously, some sort of device intended to harm the player characters, including such things as pendulum blades, hidden pits, spear-chucking devices, and so forth. A **trap with treasure** is such a trap protecting a treasure, which might be in the room beyond the trap or actually within it (such as in a pit). See the Traps section, below, for more information.

A **special** might be a puzzle of some sort, such as a door that can only be opened by a combination (hidden elsewhere in the dungeon); or perhaps an oracle that answers questions about the dungeon (but possibly it lies). The classic "magic fountain" that randomly changes the ability scores of the drinker is another possibility; if this is done, some sort of limit should be imposed (such as, the device only affects a given creature once, or the device causes harm more often than it gives aid) to prevent abuse. In general, a "special" room is any room containing something that either interests or obstructs the player characters but is not a monster, trap, or unguarded treasure.

**Empty** rooms contain no monsters, traps, unguarded treasures, or specials. This does not mean that they are truly "empty;" a room might contain a fireplace, upholstered chairs, side tables, torch sconces, and curtains, and still be considered empty. Hide a treasure in a secret drawer in a side table, and it becomes an unguarded treasure room; in other words, to be empty there has to be basically nothing of serious interest to the player characters in the room.

### 6\. Finishing Touches

The GM may wish to create one or more custom wandering monster tables for the dungeon; monster patrols, if any, may need to be described; and possibly some locations may have unusual sounds, smells, graffiti, etc. which need to be noted. Don't spend too much time on this, though.

Remember, if you only detail the "interesting" things, your players will begin to guess what might be in a room. Some extra description will help make things uncertain for the players. For instance, a room with an unguarded treasure:

Game Master:* This room contains a chest, centered against the far wall.*

Player 1:* We look for monsters, and if we don't see any, the thief will check the chest for traps.*

Kind of boring, right? This might be better:

Game Master: *In this room you see a comfortable-looking upholstered chair, a side table and a foot stool. Two burned-out torches are held by sconces on each wall.*

Player 1: *If we don't see any monsters, the thief will check the table and the footstool for traps and see if anything is hidden inside them, while the rest of us check for secret doors... one of those sconces might open one.*

A little extra detail can add a lot to the adventure.

### Traps

Some suggestions of typical traps are listed below, to assist the GM. Deadlier traps can be created by combining simple traps, by making their effects harder to avoid, or by making them capable of dealing more damage.

Traps are not necessarily reliable; the GM may choose to make a roll of some sort for each potential victim until the trap is sprung (say, 1-2 on 1d6). Or, a trap door might not open until a given weight is placed on it, so that a lightly loaded thief might cross without difficulty, only to see his heavily armored warrior ally fall victim to it.

**Alarm:** Everyone within a 30' radius must save vs Spells or be deafened for 1d8 turns by the loud noise. The GM should check immediately for wandering monsters, which, if indicated, will arrive in 2d10 rounds.

**Arrow Trap:** A hidden, mounted crossbow attacks at AB +1, doing 1d6+1 points of damage on a successful hit.

**Chute:** These are usually covered with a hidden trap door. The triggering character must save vs. Death Ray (with Dexterity bonus added) or tumble down to lower level of the dungeon. Chutes usually do little or no damage to the victim.

**Falling stones or bricks:** Rocks fall from the ceiling. The triggering character must save vs. Paralysis or Petrify (with Dexterity bonus added) or take 1d10 points of damage.

**Flashing Light:** With a loud snap, a bright light goes off in the face of the character that triggered the trap. That character, and anyone else looking directly at it, must save vs. Spells or be blinded for 1d8 turns.

**Monster-Attracting Spray:** A strong-smelling but harmless liquid is sprayed on the triggering character. The smell attracts predatory creatures, doubling the chances of wandering monsters for 1d6 hours or until washed off.

**Oil Slick:** Oil is sprayed onto the floor of the room. Anyone trying to walk through the oil must save vs Death Ray (with Dexterity bonus added) or fall prone. Oil is highly flammable and may be ignited by torches or other flame sources held by characters who slip and fall into it.

**Pit Trap:** Usually hidden with a breakable cover, trap door, or illusion. The victim must save vs Death Ray (with Dexterity bonus added) or fall into the pit, taking damage according to the distance fallen (see "Falling Damage"). A pit trap can be made deadlier by placing spikes, acid, or dangerous creatures at the bottom, or partly filling it with water to represent a drowning hazard.

**Poison Dart Trap:** A spring-loaded dart launcher attacks at AB +1 for 1d4 points of damage, and the victim must save vs. Poison or die.

**Poison Gas:** Gas emerges from vents to fill the room. All within the affected area must save vs. Poison or die. Poison gases are sometimes highly flammable and may be ignited by torches or other flame sources, doing perhaps 1d6 points of damage to each character in the area of effect (with a save vs. Dragon Breath allowed to avoid the damage).

**Poison Needle Trap:** A tiny, spring-loaded needle pops out of a keyhole or other small aperture and injects poison into the finger of the character who triggered the trap (most likely, a Thief trying to pick the lock), who must save vs. Poison or die.

**Portcullis:** A falling gate blocks the passage. The character who triggered the trap must save vs Death Ray or take 3d6 points of damage.

**Rolling Boulder Trap:** A spherical or cylindrical rock rolls down a slanting corridor. Anyone in its path must save vs. Death Ray (with Dexterity bonus added) or take 2d6 points of damage. Alternately, if the corridor has no other place for the character to escape to (that is, no room for the character to step out of the path of the rock), it may be necessary to outrun the rock to avoid the damage.

**Blade Trap:** A blade or spear drops down from the ceiling or pops out of the wall and attacks at AB +1 for 1d8 points of damage. Particularly large blades might attack everyone along a 10' or 20' line.

**Triggered Spell:** When activated, a spell of the GM's choice is cast, targeting or centered on the character who triggered it. Popular choices include curses, illusions, or a **wall of fire**.

## Designing a Wilderness Adventure

### 1\. Think About Why

This is much the same task as was described above. The player characters may enter a particular area looking for a town to resupply from, a church or temple to provide healing services, or for many other reasons. Once in the area, the Game Master can make the player characters aware of adventuring opportunities in the area, by means of rumors, posted bounties (such as for raiding humanoids), quests offered by local clergy, and so forth.

### 2\. What Kind Of Setting Is It?

Decide whether the area is deep in the wilderness, or in more inhabited territories, what sort of climate will be found there, how many towns, and of what size, are present, and so on.

You may choose to design a new territory based on the goals of the player characters in your campaign. For example, if the player characters decide to seek their fortunes in the richest city in the world, you could decide where this is and begin to describe it by providing rumors of its wealth and splendor told by far-wandering merchants. If these descriptions intrigue the characters and they travel toward the city, you will have time to decide what terrain -- and dangers -- lie in their path.

On the other hand, your setting should make sense, which will help players make meaningful choices when traveling. For example, areas under human control will be settled, with signs of civilization such as cleared land for agriculture, roads, strongholds, etc. Areas dominated by humanoid monsters, or which are being raided by wandering humanoids, will be battle-scarred and will not have food or other goods available. A valley that was settled many years ago but abandoned after a dragon attacked could contain ruined buildings, their walls likely still bearing the marks of flame and claw, and fields grown high with saplings.

### 3\. Draw An Area Map

Now it's time to draw the area map. Some Game Masters prefer to draw maps freehand, while others like to use hex or graph paper; of course, programs are available to create maps on a computer as well. It is a good idea to provide a **scale** for the map, which can be whatever best fits the map and the area you want to depict. A scale of 18 miles per square or hex is a good choice for a large-scale map, as this is the distance that a group of humans can cover in a day in clear terrain (see **Wilderness Movement Rates**), which makes it easy to determine travel times.

Rivers and coastline, hills and mountains, forests and plains must be clear on the map. All of these areas should have an appropriate climate: for example, the windward side of a mountain range will usually receive a great deal of rain, while the other side will be dry. You may choose to create an area with abnormal weather for its location, such as a sandy desert in the midst of a rain forest, but this should be unusual, a tip to observant players that strange magic is involved.

Go ahead and place any interesting sites such as towns, ruins, and significant monster lairs. Remember, in most cases your party of adventurers will need some base of operations, be it a city, town, village, or border fortress.

### 4\. Detail Interesting Sites And People

Describe at least the base town, and the dungeon you expect the party to visit first. Also detail any set or placed encounters you laid out in the step above. There is lots of room for creativity here: a distant, unfamiliar town may have different laws, traditions, or currency. You should also describe key NPCs and their connections to each other. NPCs have their own goals and plans, which may or may not involve the PCs, and the actions of player characters toward one person will often influence how others treat them. Don't go overboard trying to detail every single place on the map... leave some room for expansion later, after you have a feel for your players and their characters.

### 5\. Create Encounter Tables

When designing a wilderness area, one touch that will really set it apart is a custom encounter table. Choose those monsters that seem most appropriate to the area, using the standard encounter tables as a guide. If you have placed humanoid lairs or encampments, you may wish to include their patrols on the custom table.

Another alternative is to roll six or eight or ten random encounters using the "generic" encounter table for the relevant terrain type, and use that list as your random encounter table for the area. When doing this, you probably should re-roll duplicates.

## Strongholds

Many player characters, upon reaching higher levels, choose to settle down and build a **stronghold**. Generally this is allowed when a character reaches 9^th^ level or higher. The player character must obtain land on which to build; in some lands, frontier territory may be made available to any freeman (or freewoman) who can tame it; in others, land may be available for someone with enough gold; while in other cases the character will need to petition the local Count, Duke or King for a land grant.

Usually, Fighters build **castles,** Magic-Users build **towers**, Clerics build **temples** and Thieves build **guildhouses**, but this is not always so. Any character who builds a stronghold suitable to his or her class will attract 1^st^ level followers of the same class as follows:

| **Class** | **Number of Followers** |
|------|---------|
| Fighter | 3d6 |
| Magic-User | 1d8 |
| Cleric | 2d8 |
| Thief | 2d6 |

These followers will assist the character, but will not go on adventures away from the stronghold in most cases (especially dangerous dungeon adventures). They live from the income generated by the stronghold. The primary sources of this income are taxes on peasants for castles, fees for magical services and students' tuition for towers, tithing from the faithful for temples, and criminal activities for guildhouses. A stronghold must have 200 square feet of living space for each follower, as well as quarters for guests, stables for horses, and so on.

A player who wants to build a stronghold should draw its floor plan. Each story is usually 10' tall. The construction costs for the stronghold are determined by the square footage of its walls, floors and roofs, the materials used, and the thickness of the walls.

Make sure not to double-count corners on walls that are 5' thick or thicker -- count the length of only one face. When determining wall length for round walls and towers, approximate *pi* by 3, since the inner face of the wall has a shorter circumference. The table below gives costs in gp for each 10' square section of wall. The number by the material is its *hardness*, which is deducted from damage to the wall.

|   |  | |   |   |
|---------|-------|--------|-----|-----
| **Wall material** | **1' thick** | **5' thick** | **10' thick** | **15' thick** |
| **Maximum height** | **40'** | **60'** | **80'** | **100'** |
| **Wood (H 6)** | 10 gp | n/a | n/a | n/a |
| **Brick (H 8)** | 20 gp | 50 gp | n/a | n/a |
| **Soft stone (H 12)** | 30 gp | 70 gp | 200 gp | n/a |
| **Hard stone (H 16)** | 40 gp | 90 gp | 260 gp | 350 gp |

A 1' thick wall is made of solid pieces of material held with mortar (or pegs and ropes for wooden walls); such walls may be at most 40' tall. A 5' thick wall consists of two 1' thick walls sandwiching 3' of earth and rubble; such a wall may be at most 60' tall. A 10' thick wall consists of a 4' thick outer wall and a 2' thick inner wall sandwiching 4' of earth and rubble, and may be built up to 80' tall. A 15' thick wall consists of a 6' thick outer wall and a 2' thick inner wall sandwiching 7' of earth and rubble; these walls may be built up to 100' tall. To attain the maximum height, thinner walls can be used on upper stories. For example, an 80 ft. tower must have at least 20' of 10' thick walls at the base, but more could be used.

The character will have to pay engineering costs for designing the stronghold, and tall structures are more difficult to design and to build. For each portion of the stronghold (wall, tower, and so on), each 10' of height adds 10% to the costs in both time and money. The GM should feel free to add a multiplier to reflect the difficulties of building in a remote area, obtaining materials, etc. In particular, if materials need to be transported, they require 1 ton of cargo space per 5 gp of wood or stone construction. (The increased weight of stone compensates for its compactness compared to wood.)

A building over 40' high must have a solid foundation, and if over 60' high, it must rest on bedrock.

A stronghold requires one worker-day of construction labor for every gp it costs to build. Adding more workers reduces construction time, but the time cannot be reduced below the square root of the time for one worker to build the stronghold. Assume that there are 140 working days per year (seven months of 20 working days each) in temperate climates.

Floors and thatched roofs cost as much and take as long to build as it would take to build the square footage of their bases of 1' thick wood walls. Wood-shingled roofs cost twice this amount and take twice as long to build, while slate-shingled roofs cost four times as much and take four times as long. (You don't need to calculate the greater surface area of a pitched roof, since the increased height increases construction costs enough to cover this.)

These costs include normal features of construction such as stairs, doors and windows. Interior walls are not included; they are usually 1' thick. **Parapets**, which provide cover for defenders atop castle walls and towers, are usually 1' thick and 5' high (so they are half-cost).

Note that guildhouses are almost always built in cities and thus are usually built with 1' thick exterior walls, but they cost twice as much to build due to the traps and secret passageways that are designed into them. A Magic-User's tower costs three times as much to build, due to the need for ancient books, alchemical equipment, and other supplies for conducting research.

For example, Sir Percy, a 9^th^-level Fighter, desires to build a 60' tall square keep (50' walls with a 10' peaked slate-shingled roof) that is 50' square. The keep will have four stories and an attic, and the first story, which will contain the great hall, will be 20' high. Sir Percy wishes his keep to be strongly built, so he tells his architect to build with hard stone and use 10' thick walls for the first two stories and 5' thick walls for the rest. The first and second floors will thus be 30' square or 900 square feet, and the third and fourth floors will be 40' square or 1,600 square feet. With a total floor area of 5,000 square feet, Sir Percy's keep will house him and up to 24 other people (or animals such as horses, which during an attack may be stabled in the great hall!) in acceptable comfort. Its floor plans are shown on the next page.

The first floor has 30 (= 5 [for 50' length] x 2 [for 20' height] x 4 walls, minus 8 sections double-counted at the corners and 2 sections for the entrance) 10' square sections of 10' thick hard stone walls, which cost 7,800 gp, and 9 10' square sections of floor, which cost 90 gp, for a total cost of 7,890 gp. The second floor is the same as the first, except that the walls are 10' high and there is no deduction for an entrance, giving a cost of 4,250 gp. The third and fourth floors each require 18 sections of 5' thick hard stone walls, costing 1,620 gp, and 16 sections of floor, costing 160 gp, for a total of 1,780 gp per floor. The 50' square roof costs 4 x 25 x 10 = 1,000 gp, and the 40' square attic floor adds 160 gp. The design calls for a total of 770' of 1' thick interior walls and doors, which would cost 30,800 gp if made of hard stone; Sir Percy uses wood, which costs only 7,700 gp. These costs total 24,560 gp, but since the keep is 60' high, its cost is increased by 60% to 39,296 gp. The keep will require 39,296 worker-days. Sir Percy may employ up to 198 workers to build the keep, in which case it will take 198 working days to build, or a year and three months' time. Keep in mind what might happen in this time, given that the area is dangerous enough to warrant building a castle.

**Dungeons:** A stronghold may also have a dungeon excavated under it. A dungeon is an excellent place to store perishable supplies, a good shelter if the castle is overrun, and often incorporates an escape route if all is lost for the castle's defenders or a secret way out for raids is desired. Magic-Users sometimes encourage monsters to take up residence in their dungeons, as they provide a convenient source of supplies for magical research and help keep away unwanted guests. Use the following figures for skilled workers, such as dwarves or goblins, to create dungeons; double the times for less skilled miners.

| **Material** | **Time for one worker to** **excavate a 5' cube** |
|---|----|
| Earth | 5 days (supports are required) |
| Soft stone | 10 days |
| Hard stone | 20 days |

**Structural strength and breaches:** A section of stronghold wall has as many hit points as its base cost in gp (for example, a section of 10' thick soft stone wall has 200 hit points). Stone and brick walls only take damage from crushing blows, while wood walls are also affected by fire and chopping attacks. If a given section of wall loses all of its hit points, it is breached, allowing attackers to pass through. If a breach occurs on a lower course of wall, there is a 40% chance that the 10' section above it will be breached by collapse, and a 20% chance that the section below it will be breached. These secondary breaches have the same chances of affecting the next 10' section above or below them, and so on until the top or bottom course of wall is reached. If a breach occurs on a right or acute corner (90 degrees or less), the chances of breaches double in each direction.

**Attacking a Castle:** Siege engines are difficult to aim, but as castles don't dodge around, each successive shot by a given siege engine with a given crew has an increasing chance of hitting. To reflect this, the first attack on a castle's walls is made against Armor Class 20; each subsequent attack by that weapon, fired by that crew, at that same point in the wall, is made against an Armor Class one lower than the previous shot, to a minimum AC of 11.

Attacks on a castle's defenders are at -4 on the attack roll if they are standing on the parapets, and at -10 if they are behind arrow slits. Since characters defending the castle do move around, the odds of hitting them with a siege engine do not improve from shot to shot. There is an additional -2 on the attack roll for missile attacks if the defenders are more than 20' higher than the attackers; this is not specifically due to altitude, but rather because the defenders can use more of the wall for cover. The defenders can take advantage of their height by dropping objects on attackers near the castle's base; these missiles do 2d10 points of damage, but they have a -2 attack penalty if dropped from a height of 30' or more.

Siege engines can damage several adjacent characters; roll damage separately for each character in the 10' square hit by the missile. Of course, the attack roll must be high enough to damage each one; a roll of 19 against characters having Armor Classes of 18 and 20 would hit the former but not the latter.

A castle may also be attacked by **mining**. This method of attack involves tunneling under the castle wall, then setting fire to the supports of the tunnel to cause the wall to collapse. It is also slow, and if the castle has a moat, the tunnel must avoid it, which requires that it be dug deeper, requiring twice the time. A mine is dug like a dungeon, and once its supports are fired, the wall above is breached; if the mine is only 5' wide, there is only a 50% chance of causing a breach.

Finally, a **screw** may be used to attack a stronghold. This device, which costs 200 gp, is used to bore through castle walls. A crew of at least eight is required to operate it. It is only used at the base of a wall, and it is usually operated under a **sow**, or portable roof, as it is slow. (A sow typically costs about 100 gp.) The device does 1d8 points of damage per turn, but it ignores hardness. A breach caused by a screw is small, so it has only half the usual chance of spreading to the next course of wall, unless widened by miners.