# Preface {.unnumbered}

**Copyright © 2006-2023 Chris Gonnerman – All Rights Reserved**

**Basic Fantasy Role-Playing Game**: 
4th Edition, Release 128

All textual materials in this document, as well as all maps, floorplans, diagrams, charts, and forms included herein, are distributed under the terms of the **Creative Commons Attribution-ShareAlike 4.0 International License**. Most other artwork presented is property of the original artist and is used with permission. Note that you may not publish or otherwise distribute this work as is without
permission of the original artists; you must remove all non-licensed artwork before doing so. The full license text can be viewed at:

https://creativecommons.org/licenses/by-sa/4.0/

Some text used in the development of this document was retrieved from Wikipedia, and was originally licensed under the Creative Commons Attribution-ShareAlike 3.0 license.

Credits from the PDF:

::: {.column-screen-inset-right}

|     |    |
|:----|:----|
| Contributors: | Ray Allen, William D. Smith, Jr., Nick Bogan, Evan Moore, Stuart Marshall, Emiliano Marchetti, Antonio Eleuteri, Luigi Castellani, Michael Hensley, Nazim N. Karaca, Arthur Reyes, Todd Roe, Jim Bobb, R. Kevin Smoot, Rachel Ghoul, Tom Hoyt, James Michael Spahn, Matt Sluis, Russ Westbrook, Martin Serena, Joe Ludlum, Aaron G. Motta, and Gabe Fua | 
| Cover Art: | Erik Wilson |
| Artwork: | Erik Wilson, Steve Zieser, Matt Finch, Dan Dalton, Luigi Castellani, Nick Bogan, Mike Hill, Kevin Cook, Sean Stone, Brian "Glad" Thomas, Tomas Arfert, Andy "ATOM" Taylor, Jason Braun, Martin "Wulfgarn" Siesto, Brian DeClercq, Martin Serena, Cory "Shonuff" Gelnett, Alexander Cook, Bruce Ripple, Gabe Fua, John Simcoe, LuckyCrafts, Jeremy Putnam, Francisco Chavez, William Henry Dvorak, Tony Grant Gittoes, Jose Kercado, Jody Claunch, Terance Crosby, S. Ender Thiel, Colin Richards, John Fredericks, Piotr Klimkowicz, Evan Griffiths, Hadrien Riel-Salvatore, and Benedikt Noir | 
| Proofreading: | Tonya Allen, Daryl Burns, James Roberts, Serge Petitclerc, Benedict Wolf, Onno Tasler, Peter Cook, Derrick "Omote" Landwehr, Wes Brown, Troy Gravil, Garrett Rooney, K. David Ladage, James Lemon, Martin Serena, Joe Carruthers, Jonathan Nichol, Alister Fa, Joel Davis, Hadrien Riel-Salvatore, Mark Mealman, Alan Vetter, Jim Michnowicz, Timothy P. Fox, Piotr Klimkowicz, Daniel Collins, Thorin Schmidt, and feveredmonk | 
| Playtesters: | Taylor Gonnerman, Alan Jett, Mike Brantner, Steve Zieser, Allan Zieser, Jonathon Foster, Adam Young, Michael Young, Jason Schmidt, Doug Wilson, Jessica Abramson, Tonya Allen, Bryan Christian, Chuck Schoonover, Natalie Schoonover, Brianna Schoonover, Jason Brentlinger, Chris Wolfmeyer, Josh Eaton, Audra Brentlinger, Tim McAfee, Ike Borden, Cody Drebenstedt, Joseph BierFauble, Emily Drebenstedt, John Lopez, Pedro Pablo Miron Pozo, Robert Odom, Sergio I. Nemirovsky, Will E. Sanders, Brian Scalise, Timothy J. Kuhn, and Jeanne Mayer Mitchell |

: {tbl-colwidths="[25,75]"}
:::

Some tools to check out: 

- [Monster Index](monstersTab.qmd)
- [Interactive Tools](appendix_interactive.qmd)
- [Dungeon Maker](appendixMapmaker.qmd)
- Simple [Character Sheet](char_sheet.qmd) tool that comes along with this SRD
- Another awesome [Character Sheet](https://codex.quest/) tool created by J. Garrett Vorbeck. 

This website was created by John Atom (jmhimara). All its code and unique content are also distributed under the **Creative Commons Attribution-ShareAlike 4.0 International License**. 