# Magic Items

Determine the sort of item found by rolling on the following table:

```{ojs}

import {generalTableSelect, highlightTableRow} from "./custom.js"

viewof form = Inputs.form(
  {
    button1: Inputs.button("Any", {value: 0, 
        reduce: () => highlightTableRow("#armor-weapon-table", 
            generalTableSelect([1,100,0],[[1,25],[26,35],[36,55],[56,85],[86,90],[91,95],[96,100]]))}),
    button2: Inputs.button("Weapon or Armor", {value: 0, 
        reduce: () => highlightTableRow("#armor-weapon-table", 
            generalTableSelect([1,100,0],[[1,70], [71,100]]))}),
    button3: Inputs.button("Any Except Weapon", {value: 0, 
        reduce: () => highlightTableRow("#armor-weapon-table", 
            generalTableSelect([1,100,0],[[-2,-1],[1,12],[13,40],[41,79],[80,86],[87,93],[94,100]]))}),
  }, 
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 15% 30% 30%;
         column-gap: 10px
       ">
         ${Object.values(formParts)}
       </div>
     </div>`
  })


```

::: {#armor-weapon-table}

| **Any** | **Weapon or Armor** | **Any Except Weapons** | **Type of Item** |
|----|----|----|----| 
| 01-25 | 01-70 |  | Weapon |
| 26-35 | 71-00 | 01-12 | Armor |
| 36-55 |  | 13-40 | Potion |
| 56-85 |  | 41-79 | Scroll |
| 86-90 |  | 80-86 | Ring |
| 91-95 |  | 87-93 | Wand, Staff, or Rod |
| 96-00 |  | 94-00 | Miscellaneous Magic |

:::

## Magic Weapons

First, roll d% on the following table to determine the weapon type:

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#weapon-type-table", 
generalTableSelect([1,100,0],[[1,2],[3,9],[10,11],[12,19],[20,27],[28,31],[32,35],[36,43],[44,47],[48,59],[60,65],[66,79],[80,81],[82,83],[84,86],[87,94],[95,95],[96,96],[97,97],[98,100]]))})

```

:::{#weapon-type-table}

| **d%** | **Weapon Type** |
|----|-----|
| 01-02 | Great Axe |
| 03-09 | Battle Axe |
| 10-11 | Hand Axe |
| 12-19 | Shortbow |
| 20-27 | Shortbow Arrow |
| 28-31 | Longbow |
| 32-35 | Longbow Arrow |
| 36-43 | Light Quarrel |
| 44-47 | Heavy Quarrel |
| 48-59 | Dagger |
| 60-65 | Shortsword |
| 66-79 | Longsword |
| 80-81 | Scimitar |
| 82-83 | Two-Handed Sword |
| 84-86 | Warhammer |
| 87-94 | Mace |
| 95 | Maul |
| 96 | Pole Arm |
| 97 | Sling Bullet |
| 98-00 | Spear |

:::

Next, roll on the Weapon Bonus tables. Follow the directions given if a roll on the Special Enemy or Special Ability tables are indicated; generally multiple rolls on the Special Ability table should be ignored when rolled.

```{ojs}

Inputs.form(
  {
    button1: Inputs.button("d% Melee", {value: 0, 
        reduce: () => highlightTableRow("#melee-missile-weapon", 
            generalTableSelect([1,100,0],[[1,40],[41,50],[51,55],[56,57],[58,58],[59,75],[76,85],[86,95],[96,98],[99,100]]))}),
    button2: Inputs.button("d% Missile", {value: 0, 
        reduce: () => highlightTableRow("#melee-missile-weapon", 
            generalTableSelect([1,100,0],[[1,40],[47,58],[59,64],[-2,-1],[-2,-1],[65,82],[83,94],[-2,-1],[95,98],[99,100]]))}),
  }, 
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 30% 30% ;
         column-gap: 10px
       ">
         ${Object.values(formParts)}
       </div>
     </div>`
  })

```

:::{#melee-missile-weapon}

| **d% Melee** | **d% Missile** | **Weapon Bonus**             |
|--------------|----------------|------------------------------|
| 01-40        | 01-46          | +1                           |
| 41-50        | 47-58          | +2                           |
| 51-55        | 59-64          | +3                           |
| 56-57        |                | +4                           |
| 58           |                | +5                           |
| 59-75        | 65-82          | +1, +2 vs. Special Enemy     |
| 76-85        | 83-94          | +1, +3 vs. Special Enemy     |
| 86-95        |                | Roll Again + Special Ability |
| 96-98        | 95-98          | Cursed, -1*                  |
| 99-00        | 99-00          | Cursed, -2*                  |


:::

\* If cursed weapons are rolled along with special abilities, ignore the special ability roll.

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#special-enemy-table", 
generalTableSelect([1,6,0],[[1,1],[2,2],[3,3],[4,4],[5,5],[6,6]]))})

```

:::{#special-enemy-table}

| **1d6** | **Special Enemy** |
|---------|-------------------|
| 1       | Dragons           |
| 2       | Enchanted         |
| 3       | Lycanthropes      |
| 4       | Regenerators      |
| 5       | Spell Users       |
| 6       | Undead            |


:::

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#special-ability-table", 
generalTableSelect([1,20,0],[[1,9],[10,11],[12,12],[13,16],[17,19],[20,20]]))})

```

:::{#special-ability-table}

| **1d20** | **Special Ability** |
|----|----|
| 01-09 | Casts Light on Command |
| 10-11 | Charm Person |
| 12 | Drains Energy |
| 13-16 | Flames on Command |
| 17-19 | Locate Objects |
| 20 | Wishes |

:::

## Magic Armor

Generate the type and bonus of each item of magic armor on the tables below.

```{ojs}

Inputs.form(
  {
    button1: Inputs.button("d% Armor Type", {value: 0, 
        reduce: () => highlightTableRow("#magic-armor-table", 
            generalTableSelect([1,100,0],[[1,9],[10,28],[29,43],[44,100]]))}),
    button2: Inputs.button("d% Armor Bonus", {value: 0, 
        reduce: () => highlightTableRow("#magic-armor-table", 
            generalTableSelect([1,100,0],[[1,50],[51,80],[81,90],[91,95],[92,100]]))}),
  }, 
  {
    template: (formParts) => htl.html`
     <div>
       <div style="
         display: grid;
         grid-template-columns: 40% 40% ;
         column-gap: 10px
       ">
         ${Object.values(formParts)}
       </div>
     </div>`
  })

```

:::{#magic-armor-table}

| **d%** | **Armor Type** | **d%** | **Armor Bonus**  |
|--------|----------------|--------|------------------|
| 01-09  | Leather Armor  | 01-50  | +1               |
| 10-28  | Chain Mail     | 51-80  | +2               |
| 29-43  | Plate Mail     | 81-90  | +3               |
| 44-00  | Shield         | 91-95  | Cursed *         |
|        |                | 96-00  | Cursed, AC 11 ** |

:::

\* If Cursed armor is rolled, roll again and reverse the bonus (e.g., -1 instead of +1).

** This armor has AC 11 but appears to be +1 when tested.

## Potions

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#potions-random-table", 
generalTableSelect([1,100,0],[[1,3], [4,6], [7,8], [9,11], [12,13], [14,16], [17,19], [20,22], [23,25], [26,32], [33,35], [36,39], [40,43], [44,47], [48,51], [52,55], [56,59], [60,63], [64,68], [69,72], [73,76], [77,80], [81,84], [85,86], [87,89], [90,97], [98,100]]))})

```

:::{#potions-random-table}

| **d%** | **Type**         |
|--------|------------------|
| 01-03  | Clairaudience    |
| 04-06  | Clairvoyance     |
| 07-08  | Cold Resistance  |
| 09-11  | Control Animal   |
| 12-13  | Control Dragon   |
| 14-16  | Control Giant    |
| 17-19  | Control Human    |
| 20-22  | Control Plant    |
| 23-25  | Control Undead   |
| 26-32  | Delusion         |
| 33-35  | Diminution       |
| 36-39  | Fire Resistance  |
| 40-43  | Flying           |
| 44-47  | Gaseous Form     |
| 48-51  | Giant Strength   |
| 52-55  | Growth           |
| 56-59  | Healing          |
| 60-63  | Heroism          |
| 64-68  | Invisibility     |
| 69-72  | Invulnerability  |
| 73-76  | Levitation       |
| 77-80  | Longevity        |
| 81-84  | Mind Reading     |
| 85-86  | Poison           |
| 87-89  | Polymorph Self   |
| 90-97  | Speed            |
| 98-00  | Treasure Finding |

:::

## Scrolls

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#scrolls-table", 
generalTableSelect([1,100,0],[[1,3], [4,6], [7,8], [9,9 ], [10,15], [16,20], [21,25], [26,29], [30,32], [33,34], [35,35  ], [36,40], [41,46], [47,56], [57,61], [62,75], [76,85], [86,89], [90,92], [93,100]]))})

```

:::{#scrolls-table}

| **d%** | **General Type** |
|----|----|
| 01-03 | Cleric Spell Scroll (1 Spell) |
| 04-06 | Cleric Spell Scroll (2 Spells) |
| 07-08 | Cleric Spell Scroll (3 Spells) |
| 09 | Cleric Spell Scroll (4 Spells) |
| 10-15 | Magic-User Spell Scroll (1 Spell) |
| 16-20 | Magic-User Spell Scroll (2 Spells) |
| 21-25 | Magic-User Spell Scroll (3 Spells) |
| 26-29 | Magic-User Spell Scroll (4 Spells) |
| 30-32 | Magic-User Spell Scroll (5 Spells) |
| 33-34 | Magic-User Spell Scroll (6 Spells) |
| 35 | Magic-User Spell Scroll (7 Spells) |
| 36-40 | Cursed Scroll |
| 41-46 | Protection from Elementals |
| 47-56 | Protection from Lycanthropes |
| 57-61 | Protection from Magic |
| 62-75 | Protection from Undead |
| 76-85 | Map to Treasure Type A |
| 86-89 | Map to Treasure Type E |
| 90-92 | Map to Treasure Type G |
| 93-00 | Map to 1d4 Magic Items |

:::

## Rings

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#rings-table", 
generalTableSelect([1,100,0],[[1,6],[7,12],[13,19],[20,30],[31,33],[34,44],[45,57],[58,66],[67,70],[71,71],[72,73],[74,75],[76,81],[82,83],[84,90],[91,97],[98,98],[99,100]]))})

```

:::{#rings-table}

| **d%** | **Type** |
|----|----|
| 01-06 | Control Animal |
| 07-12 | Control Human |
| 13-19 | Control Plant |
| 20-30 | Delusion |
| 31-33 | Djinni Summoning |
| 34-44 | Fire Resistance |
| 45-57 | Invisibility |
| 58-66 | Protection +1 |
| 67-70 | Protection +2 |
| 71 | Protection +3 |
| 72-73 | Regeneration |
| 74-75 | Spell Storing |
| 76-81 | Spell Turning |
| 82-83 | Telekinesis |
| 84-90 | Water Walking |
| 91-97 | Weakness |
| 98 | Wishes |
| 99-00 | X-Ray Vision |

:::

## Wands, Staves and Rods

```{ojs}

Inputs.button("Roll on Table", 
{value: 0, 
reduce: () => highlightTableRow("#wands-table", 
generalTableSelect([1,100,0],[[1,8],[9,13],[14,17],[18,28],[29,30],[31,34],[35,35],[36,40],[41,45],[46,50],[51,55],[56,60],[61,65],[66,73],[74,79],[80,84],[85,92],[93,100]]))})

```

:::{#wands-table}

| **d%** | **Type** |
|----|----|
| 01-08 | Rod of Cancellation |
| 09-13 | Snake Staff |
| 14-17 | Staff of Commanding |
| 18-28 | Staff of Healing |
| 29-30 | Staff of Power |
| 31-34 | Staff of Striking |
| 35 | Staff of Wizardry |
| 36-40 | Wand of Cold |
| 41-45 | Wand of Enemy Detection |
| 46-50 | Wand of Fear |
| 51-55 | Wand of Fireballs |
| 56-60 | Wand of Illusion |
| 61-65 | Wand of Lightning Bolts |
| 66-73 | Wand of Magic Detection |
| 74-79 | Wand of Paralyzation |
| 80-84 | Wand of Polymorph |
| 85-92 | Wand of Secret Door Detection |
| 93-00 | Wand of Trap Detection |

:::

## Miscellaneous Magic Items

Effect Subtables
d%
Subtable
01-57
Effect Subtable 1
58-00
Effect Subtable 2

### **Effect Subtables**

| d%    | Subtable          |
|-------|-------------------|
| 01-57 | Effect Subtable 1 |
| 58-00 | Effect Subtable 2 |

### **Effect Subtable 1**

| d%    | Effect             | Form |
|-------|--------------------|------|
| 01    | Blasting           | G    |
| 02-05 | Blending           | F    |
| 06-13 | Cold Resistance    | F    |
| 14-17 | Comprehension      | E    |
| 18-22 | Control Animal     | C    |
| 23-29 | Control Human      | C    |
| 30-35 | Control Plant      | C    |
| 36-37 | Courage            | G    |
| 38-40 | Deception          | F    |
| 41-52 | Delusion           | A    |
| 53-55 | Djinni Summoning   | C    |
| 56    | Doom               | G    |
| 57-67 | Fire Resistance    | F    |
| 68-80 | Invisibility       | F    |
| 81-85 | Levitation         | B    |
| 86-95 | Mind Reading       | C    |
| 96-97 | Panic              | G    |
| 98-00 | Penetrating Vision | D    |

### **Effect Subtable 2**

| d%    | Effect                       | Form |
|-------|------------------------------|------|
| 01-07 | Protection +1                | F    |
| 08-10 | Protection +2                | F    |
| 11    | Protection +3                | F    |
| 12-14 | Protection from Energy Drain | F    |
| 15-20 | Protection from Scrying      | F    |
| 21-23 | Regeneration                 | C    |
| 24-29 | Scrying                      | H    |
| 30-32 | Scrying, Superior            | H    |
| 33-39 | Speed                        | B    |
| 40-42 | Spell Storing                | C    |
| 43-50 | Spell Turning                | F    |
| 51-69 | Stealth                      | B    |
| 70-72 | Telekinesis                  | C    |
| 73-74 | Telepathy                    | C    |
| 75-76 | Teleportation                | C    |
| 77-78 | True Seeing                  | D    |
| 79-88 | Water Walking                | B    |
| 89-99 | Weakness                     | C    |
| 00    | Wishes                       | C    |


Roll on the first table above to select a subtable, then
roll again on the selected subtable to determine the
exact effect. Finally, roll on the specified column of the
Form table to determine the physical form of the item.

### Form of Item

::: {.table-responsive .column-screen-right}

|                     | A     | B     | C     | D     | E     | F     | G     | H     |
|---------------------|-------|-------|-------|-------|-------|-------|-------|-------|
| Bell (or Chime)     | 01-02 |       |       |       |       |       | 01-17 |       |
| Belt or Girdle      | 03-05 |       |       |       |       | 01-07 |       |       |
| Boots               | 06-13 | 01-25 |       |       |       |       |       |       |
| Bowl                | 14-15 |       |       |       |       |       |       | 01-17 |
| Cloak               | 16-28 |       |       |       |       | 08-38 |       |       |
| Crystal Ball or Orb | 29-31 |       |       |       |       |       |       | 18-67 |
| Drums               | 32-33 |       |       |       |       |       | 18-50 |       |
| Helm                | 34-38 |       |       |       | 01-40 |       |       |       |
| Horn                | 39-43 |       |       |       |       |       | 51-00 |       |
| Lens                | 44-46 |       |       | 01-17 |       |       |       |       |
| Mirror              | 47-49 |       |       | 18-17 |       |       |       | 68-00 |
| Pendant             | 50-67 | 26-50 | 01-40 | 18-50 | 41-80 | 39-50 |       |       |
| Ring                | 68-00 | 51-00 | 41-00 | 51-00 | 81-00 | 51-00 |       |       |

:::

### Rare Items 

| d%    | Type                                       |
|-------|--------------------------------------------|
| 01-05 | Bag of Devouring                           |
| 06-20 | Bag of Holding                             |
| 21-32 | Boots of Traveling and Leaping             |
| 33-47 | Broom of Flying                            |
| 48-57 | Device of Summoning Elementals (see below) |
| 58-59 | Efreeti Bottle                             |
| 60-64 | Flying Carpet                              |
| 65-81 | Gauntlets of Ogre Power                    |
| 82-86 | Girdle of Giant Strength                   |
| 87-88 | Mirror of Imprisonment                     |
| 89-00 | Rope of Climbing                           |


## Devices of Summoning Elementals

Review the information for [Elementals](monstersAll.qmd#elemental) 
before randomly selecting any of these items, as you
may not wish to allow all types of elementals in your
campaign.

| 1d8 | Type                                      |
|-----|-------------------------------------------|
| 1   | Bowl of Summoning Water Elementals        |
| 2   | Brazier of Summoning Fire Elementals      |
| 3   | Censer of Summoning Air Elementals        |
| 4   | Crucible of Summoning Metal Elementals    |
| 5   | Mallet of Summoning Wood Elementals       |
| 6   | Marble Plate of Summoning Cold Elementals |
| 7   | Rod of Summoning Lightning Elementals     |
| 8   | Stone of Summoning Earth Elementals       |


## Explanation of Magic Items

### Using Magic Items

To use a magic item, it must be activated, although sometimes activation simply means putting a ring on your finger. Some items, once donned, function constantly.

Many items are activated just by using them. For instance, a character has to drink a potion, swing a sword, interpose a shield to deflect a blow in combat, wear a ring, or don a cloak. Activation of these items is generally straightforward and self-explanatory. This doesn't mean that if you use such an item, you automatically know what it can do. You must know (or at least guess) what the item can do and then use the item in order to activate it, unless the benefit of the item comes automatically, such as from drinking a potion or swinging a sword.

If no activation method is suggested either in the magic item description or by the nature of the item, assume that a command word is needed to activate it. Command word activation means that a character speaks the word and the item activates. No other special knowledge is needed.

A command word can be a real word, but when this is the case, the holder of the item runs the risk of activating the item accidentally by speaking the word in normal conversation. More often, the command word is some seemingly nonsensical word, or a word or phrase from an ancient language no longer in common use. Note that many magic items must be held in the hand (or otherwise specially handled or worn) to be used; the risk of accidental activation is less significant for such items.

Learning the command word for an item may be easy (sometimes the word is actually inscribed on the item) or it may be difficult, requiring the services of a powerful wizard or sage, or some other means of discovery.

Only the character holding or wearing a magic item may activate it. A character who has been gagged or silenced may not activate a magic item which requires a command word.

When an article of magic armor, clothing or jewelry (including a ring) is discovered, size is not usually an issue. Such items magically adjust themselves for wearers from as small as Halflings to as large as Humans. This effect is called **accommodation**. The GM may create "primitive" items lacking this power if he or she wishes.

Generally only one magical item of a given type may be worn at the same time. For example, a character can normally only wear one suit of armor, wear one necklace and carry one shield at a time. In the case of rings, a character may wear one magical ring per hand. If a character wears more items of a given type than would normally be practical, the items will usually fail to function due to interference with one another; for instance, wearing two rings on the same hand normally results in both rings failing to operate. **Note, however,** that this limitation cannot be used to disable cursed magic items. For example, wearing a cursed ring would prevent another magic ring from being worn and used on that hand, but the curse would not be lifted by donning a second magic ring.

### Magic Weapons

Magic weapons are created with a variety of powers and will usually aid the wielder in combat. A magical weapon's bonus is applied to all attack and damage rolls made with the weapon.

**Casts Light on Command:** By drawing the weapon and uttering a command word, the wielder may cause it to glow; it will then shed light with the same radius as a **light** spell. Sheathing or laying down the weapon, or speaking the command word again, dispels the effect. This power may be used as often as desired.

**Charm Person:** This power allows the wielder to cast **charm person** once per day, as if by an 8^th^ level Magic-User, by brandishing the weapon, speaking a command word and gazing at the target creature. (The wielder's gaze does not have to be met for the spell to be cast.) The target creature is allowed saving throws just as described in the spell description.

**Drains Energy:** A weapon with this power drains one life energy level on a hit, as described under **Energy Drain** in the **Encounter** section; up to 2d4 levels can be drained by a weapon with this power, after which time the weapon loses this power but retains any other magical effects or bonuses.

**Flames on Command:** Upon command, the weapon will be sheathed in fire. The fire does not harm the wielder. The effect remains until the command is given again, or until the weapon is dropped or sheathed. While it flames, all damage done by the weapon is treated as fire damage, and an additional +1 bonus (in addition to the weapon's normal bonus) is added to damage when fighting trolls, treants, and other creatures especially vulnerable to fire. It casts light and burns just as if it were a torch.

**Locate Objects:** This power allows the wielder to cast the spell **locate object** once per day, as if by an 8^th^ level Magic-User.

**Special Enemy:** These weapons are created to combat a specific sort of creature, as rolled on the Special Ability table. When used against that specific enemy, the second listed bonus applies instead of the first; so a sword +1, +3 vs. Undead would provide +1 attack and damage against giant rats, but +3 attack and damage rolls against zombies.

**Wishes:** Weapons with this power have the ability to grant 1d4 wishes. The GM must adjudicate all wishes, and instructions are given in the **Game Master** section regarding this. After these wishes have been made, the weapon loses this power, but retains any other bonuses and powers.

**Cursed Weapons** inflict a penalty to the wielder's attack rolls, as rolled on the Weapon Bonus table. The curse causes the afflicted character to be unable to get rid of the weapon. There are two possible forms the curse may take: Obsession and Affliction. The GM may decide which to use at his or her option.

**Obsession:** Regardless of how severe the penalty is, the character wielding the weapon will believe it is a bonus and refuse to use any other weapon in combat. A **remove curse** spell is the only way to rid a character of such a weapon; but as he or she will believe the weapon is the best magical weapon ever, the character receives a saving throw vs. Spells to resist.

**Affliction:** The character knows the weapon is cursed as soon as he or she uses it in combat; however, any attempt to throw it away fails, as the weapon magically appears back in the character's hand whenever he or she tries to draw any other weapon. In this case, the **remove curse** spell needed to rid the character of the weapon will be unopposed (i.e. no saving throw).

### Magic Armor

Magic armor (including shields) offers improved, magical protection to the wearer. In general, magic armor grants the normal Armor Class for its type, plus the magical armor bonus, as rolled on the Magic Armor table; for example, Plate Mail +2 provides an Armor Class of 19.

There are two varieties of **cursed armor**: Cursed Armor -1 and Cursed Armor AC 11. The first variety's AC is reduced by the rolled penalty; for example, Plate Mail -1 grants Armor Class 16. The second type is much worse, for regardless of the type, it only provides Armor Class 11. Dexterity and shield bonuses still apply.

Cursed armor cannot be removed from the wearer once the curse is proven, that is, once the wearer is hit in combat. Once the curse has taken effect, only a **remove curse** spell, or some more powerful magic (such as a wish), will enable the wearer to remove it. The armor will detect as magical, like any other magic armor; the curse cannot be detected by any means other than wearing the armor in combat.

### Potions

A potion is an elixir concocted with a spell-like effect that affects only the drinker. Unless otherwise noted, a potion grants its benefits for 1d6+6 turns (even if the duration of an associated spell is longer or shorter).

**Clairaudience:** This potion enables the drinker to hear sounds in another area through the ears of a living creature in that area, up to a maximum 60' away. This effect otherwise functions just as the spell **clairvoyance**.

**Clairvoyance:** This potion grants the imbiber the effect of the **clairvoyance**spell.

**Cold Resistance:** This potion grants the imbiber the power of the spell **resist cold**.

**Control Animal:** This potion functions like a **control human** potion, but affects only normal, non-magical animals.

**Control Dragon:** This potion functions like a **control human** potion, but affects only dragons.

**Control Giant:** This potion functions like a **control human** potion, but affects only giants.

**Control Human:** This potion allows the drinker to charm a human, demi-human, or humanoid by gazing at them. The effect functions like the **charm person** spell. If the charm is resisted, the drinker can attempt to charm up to two more targets before the potion's benefit is exhausted.

**Control Plant:** This potion grants the drinker control over one or more plants or plant creatures within a 10' square area up to 50' away. Normal plants become animated, having a movement rate of 10', and obey the drinker's commands. If ordered to attack, only the largest plants can do any real harm, attacking with a +0 attack bonus and inflicting 1d4 points of damage per hit. Affected plant creatures (who fail to save vs. Spells) can understand the drinker, and behave as if under a **charm monster** spell.

**Control Undead:** This potion grants the drinker command of 3d6 hit dice of undead monsters. A save vs. Spells is allowed to resist the effect. Mindless undead follow the drinker's commands exactly; free-willed undead act as if under a **charm person** spell.

**Delusion:** This cursed potion will appear, if tested or analyzed, to be one of the other potions (other than poison). When imbibed, the drinker will briefly believe he has received the benefits of the "other" potion, but the illusion will be swiftly exposed...

**Diminution:** This potion reduces the drinker and all items worn or carried to one-twelfth of his or her original height (so that a 6' tall character becomes 6" tall). The drinker's weight is divided by 1,728; this makes an armed warrior weigh less than 2.5 ounces. The affected creature cannot make an effective attack against any creature bigger than a house cat, but may be able to slip under doors or into cracks and has a 90% chance of moving about undetected (both in terms of sound and vision).

**Fire Resistance:** This potion grants the imbiber the power of the spell **resist fire**.

**Flying:** This spell grants the power of the spell **fly**.

**Gaseous Form:** The drinker and all of his or her gear become insubstantial, misty, and translucent. He or she becomes immune to non-magical weapons, and has an Armor Class of 22 vs. magical weapons. The imbiber can't attack or cast spells while in gaseous form. The drinker also loses supernatural abilities while in gaseous form. A gaseous creature can fly at a speed of 10', and can pass through small holes or narrow openings, even mere cracks, as long as the potion persists. The gaseous creature is subject to the effects of wind, and can't enter water or other liquid. Objects cannot be manipulated in this form, even those brought along when the potion was imbibed. The drinker cannot resume material form at will, but must wait for the potion to expire; however, the potion may be quaffed in thirds, in which case each drink lasts 1d4+1 turns.

**Giant Strength:** This potion grants the imbiber the Strength of a giant. For the duration, the drinker gains a bonus of +5 on attack and damage rolls with melee or thrown weapons, and can throw large stones just as a stone giant can.

**Growth:** The drinker of this potion (with all equipment worn or carried) becomes twice normal height and eight times normal weight. The enlarged character is treated as having the Strength of a Stone Giant (but without the rock-throwing ability), gaining +5 on attack and damage rolls.

**Healing:** The imbiber of this potion receives 1d6+1 hit points of healing (as the spell **cure light wounds**).

**Heroism:** This potion improves the fighting ability of the drinker. Fighters of less than 3^rd^ level gain +3 to attack bonus as well as gaining 3 hit dice. Fighters of 4^th^ to 5^th^ level gain +2 to attack bonus and 2 hit dice. Fighters of 6^th^ or 7^th^ level gain +1 to attack bonus and 1 hit die. Fighters of 8^th^ level or higher, as well as non-Fighter class characters, gain no hit dice, but still receive +1 to attack bonus. Hit dice gained are only temporary, and damage received is deducted from those hit dice first; any that remain when the potion expires are simply lost.

**Invisibility:** This potion makes the imbiber invisible (as the spell). This potion may be quaffed in thirds, in which case each drink lasts 1d4+1 turns.

**Invulnerability:** This potion grants a bonus of +2 to Armor Class.

**Levitation:** This potion grants the power of the spell **levitate**.

**Longevity:** The drinker of this potion becomes younger by 1d10 years.

**Mind Reading**: This potion grants the power of the spell of the same name.

**Poison:** This isn't a potion at all, it's a trap. The drinker must save vs. Poison or die, even if only a sip was imbibed.

**Polymorph Self:** This potion grants the power of the spell of the same name.

**Speed:** This potion gives the drinker the benefits of the spell **haste**.

**Treasure Finding:** The imbiber of this potion will immediately know the direction and approximate distance to the largest treasure hoard in a 300' spherical radius. This potion specifically detects platinum, gold, electrum, silver, and copper; gemstones and magic items are not detected.

### Scrolls

Most scrolls contain some sort of magic which is activated when read, and which may only be used once; the characters burn away as the words are read.

**Spell Scrolls** are enchanted with one or more Cleric or Magic-User spells (never both sorts on the same scroll). Each spell can be used just once, though of course the same spell may appear multiple times on a single scroll. Use the table below to determine the spell level of each spell on a scroll. Only a Cleric can use a Clerical scroll, and only a Magic-User can use a Magic-User scroll.

Magic-Users must cast **read magic** on a spell scroll before being able to use it; each scroll needs to be treated in this way just once, and the effect lasts indefinitely thereafter. If a Magic-User attempts to cast a spell from a scroll, and he or she does not know that spell, there is a 10% chance the spell will fail. If a spell on a scroll is of higher level than the highest level spell the Magic-User can cast, for each spell level of difference, add 10% to the chance of failure. For example, Aura the 3^rd^ level Magic-User attempts to cast **polymorph self** from a scroll. Aura is able to cast, at most, 2^nd^ level spells. **Polymorph self** is a 4^th^ level spell, so Aura has a chance of failure of 10% (she doesn't know the spell) plus 20% (2^nd^ level maximum vs. 4^th^ level spell), for a total of 30%.

Clerical scrolls are written in a normal language (being just specially enchanted prayers), so the Cleric merely needs to know the language in which the scroll is written in order to use it. Clerics suffer the same chance of failure as do Magic-Users, save that the 10% penalty assigned for not knowing the spell does not apply.

#### Spell Scrolls: Spell Level

| **d%** | **Level of Spell** |
|---|----|
| 01-30 | 1st |
| 31-55 | 2nd |
| 56-75 | 3rd |
| 76-88 | 4th |
| 89-97 | 5th |
| 98-00 | 6th |

A **Cursed Scroll** inflicts some curse upon whoever reads it. It need not be read completely; in fact, merely glancing at the text is enough to inflict the curse. A saving throw may or may not be allowed, as determined by the GM (though a save vs. Spells should usually be allowed). The GM is encouraged to be creative when creating curses; the spell **bestow curse** (the reverse of **remove curse**) can be used for inspiration, but cursed scrolls can contain more powerful or inventive curses at the GM's discretion.

**Protection Scrolls** can be read by any character class, assuming the character can read the language the scroll is written in (see the notes under **Language** in the **Character** section for details). When read, a protection scroll creates a 10' radius protective circle around the reader; preventing the warded creatures from entering. The circle moves with the reader. Any creature other than the sort the scroll wards may enter, including of course the allies of the scroll-reader, who are themselves protected so long as they remain entirely within the circle. If any creature within the circle performs a melee attack against any of the warded creatures, the circle is broken and the warded creatures may freely attack. Normal protection scrolls last for 2 turns after being read.

**Protection from Magic** scrolls are special, as they protect against magic spells and items rather than creatures. No magical effect can cross the 10' circle of protection in either direction for 1d4 turns. As with the other protection scrolls, the circle created by this scroll moves with the reader.

**Treasure Maps** are generally non-magical. They must be created by the GM, although he or she may delay creating the map until the characters can actually use it. The treasure indicated on the map will normally be guarded by some sort of monster, determined by the GM as desired.

### Rings

A ring is a circular metal band worn on the finger (no more than one ring per hand) that has a spell-like power (often a constant effect that affects the wearer).

**Control Animal:** The wearer of this ring can charm up to 6 hit dice of animals. The effect works much like a **charm person** spell, but only affects animals (including giant-sized animals, but excluding fantastic creatures as well as anything more intelligent than a dog or cat). The wearer can activate the power at will, targeting any animal within 60' that he or she can see. The wearer may choose to end the effect for one or more controlled creatures at any time, in order to "free" enough hit dice to control a new target.

**Control Human:** The wearer of this ring may cast the spell **charm person** at any target he or she can see within 60'. The wearer can use this power once per round, at will, but cannot control more than 6 hit dice of creatures at a time; however, the wearer may choose to end the effect for one or more controlled creatures at any time, in order to "free" enough hit dice to control a new target.

**Control Plant:** The wearer of this ring may create an effect equivalent to a **potion of plant control** at will, affecting plants or plant creatures within 60' that he or she can see. The effect lasts as long as the wearer remains within 60' of the plants or plant creatures. A saving throw is allowed just as for the potion.

**Delusion:** This ring appears to be some other sort of ring (roll again on the rings table to determine what sort). Whoever wears it believes it is working, and behaves thus (so a character who believes he is wearing a **ring of invisibility** will believe himself to actually be invisible). Unlike the potion of the same name, the ring's effect is not dispelled by the wearer taking damage; in fact, the only way to rid a character of this cursed item is with the spell **remove curse**.

**Djinni Summoning:** This ring serves as a special gate by means of which a specific djinni can be called from the Elemental Plane of Air. When the ring is rubbed, the djinni appears on the next round. The djinni faithfully obeys and serves the wearer of the ring, but never for more than 1 hour per day. If the djinni of the ring is ever killed, the ring becomes non-magical and worthless.

**Fire Resistance:** The wearer of this ring receives protection as the spell **resist fire**, but the protection works continually.

**Invisibility:** By activating this simple silver ring, the wearer can benefit from **invisibility**, as the spell. If the invisibility is dispelled (as described for the spell), the ring may not be reactivated for one full turn. The invisibility effect otherwise lasts for 24 hours.

**Protection:** This ring offers continual magical protection in the form of a bonus to the Armor Class of the wearer (varying from +1 to +3 as shown on the table). This bonus is also applied to the wearer's saving throw die rolls.

**Regeneration:** This ring grants the wearer the power of regeneration, exactly as described in the description of the troll, including the weakness with respect to acid and fire damage. However, only damage taken while wearing the ring is regenerated.

**Spell Storing:** A ring of spell storing contains a number of Magic-User spells that the wearer can cast. Each spell has a caster level equal to the minimum level needed to cast that spell. Any class may wear and use this ring, but it can only be recharged by a Magic-User casting the appropriate spell into it. A table is provided below to determine how many spells, and what levels they are. A ring of spell storing must be recharged with the same spells that were placed into it when it was made; so a ring of two spell storing containing **fireball** and **fly** can only be recharged with those two spells. The ring magically imparts to the wearer the names of all spells stored within it. A ring found in a treasure hoard may be completely charged, or discharged, or partially charged, at the GM's option.

| **d%** | **# of Spells**   | **d%** | **Level of Spell** |
|----|----|----|----|
| 01-24 | 1   | 01-30 | 1st |
| 25-48 | 2   | 31-55 | 2nd |
| 49-67 | 3  | 56-75 | 3rd |
| 68-81 | 4   | 76-85 | 4th |
| 82-91 | 5   | 86-97 | 5th |
| 92-96 | 6   | 98-00 | 6th |
| 97-00 | 7   |  |  |

**Spell Turning:** This ring reflects spells cast directly at the wearer, but not area effect spells, back at the caster; so a **hold person** spell would be reflected, but not a **fireball**. It will reflect up to 2d6 spells before its power is exhausted.

**Telekinesis:** The wearer of this ring can use the power of the spell **telekinesis**, as if cast by a 12^th^ level Magic-User. The effect may be used as many times per day as the wearer wishes, but lasts only as long as the wearer concentrates on it.

**Water Walking:** This ring allows the wearer to walk on any liquid as if it were firm ground. Mud, oil, snow, quicksand, running water, ice, and even lava can be traversed easily, since the wearer's feet hover an inch or two above the surface. Molten lava will still cause the wearer damage from the heat since he or she is still near it. The wearer can walk, run, or otherwise move across the surface as if it were normal ground.

**Weakness:** Whoever puts this ring on is cursed; his or her Strength score is reduced immediately to 3. The ring can only be removed with **remove curse**.

**Wishes:** A ring of wishes contains the power to grant wishes to the wearer. 1d4 wishes will remain within the ring when it is found. The GM must adjudicate all wishes, and instructions are given in the **Game Master** section regarding this.

**X-Ray Vision:** On command, this ring gives its possessor the ability to see into and through solid matter. Vision range is 20 feet, with the viewer seeing as if he were looking at something in normal light even if there is no illumination. X-ray vision can penetrate 1 foot of stone, 1 inch of common metal, or up to 3 feet of wood or dirt. Thicker substances or a thin sheet of lead or gold blocks the vision. The ring may be used three times per day, and each use lasts at most one turn (or until the wearer ceases to concentrate upon it).

### Wands, Staves and Rods

A wand is a short stick, generally 12 to 18 inches long, imbued with the power to cast a specific spell or spell-like effect. A newly created wand has 20 charges, and each use of the wand depletes one of those charges; a wand found in a treasure hoard will have 2d10 charges remaining. If a wand generates an effect equivalent to a spell, assume the spell functions as if cast by a 6^th^ level caster, or the lowest level caster who could cast that spell (whichever is higher), unless otherwise noted. Wands are generally usable only by Magic-Users. Saving throws are rolled as normal, but on the Magic Wands column rather than the Spells column.

A staff has a number of different (but often related) spell effects. A newly created staff has 30 charges, and each use of the staff depletes one or more of those charges. A staff found in a treasure hoard will have 3d10 charges remaining. Spell effects generated by a staff operate at 8^th^ level, or the lowest caster level the spell could be cast by, whichever is higher, unless otherwise stated. Staves are usable only by Magic-Users, except where noted. Saving throws against magic from a staff are rolled on the Spells column.

A rod is a scepter-like item with a special power unlike that of any known spell. Rods are normally usable by any class.

**Rod of Cancellation:** This dreaded rod is a bane to magic items, for its touch drains an item of all magical properties. If the item is held by a creature, an attack roll is needed to touch it. Upon draining an item, the rod itself becomes brittle and cannot be used again. Drained items are only restorable by a **wish**.

**Snake Staff:** This item is a walking staff +1. When used by a Cleric, the user may command the staff to transform into a constrictor snake (instead of causing damage) on a successful hit. The snake will wrap around a target up to man sized and hold him or her fast for 1d4 turns, unless a save vs. Spells is made. The snake does not attack in any other way, nor cause any damage. The snake may be recalled by the user at any point, in which case it returns to his or her hand and returns to staff form. It also returns in this way when the duration expires, or if the save is made. The snake has Armor Class 15, moves 20' per round and has 20 hit points; any hit points of damage taken are healed completely when the snake returns to staff form; if killed in snake form, the magic is destroyed and it turns into a broken stick. The staff may be used any number of times per day, and neither has nor uses charges.

**Staff of Commanding:** This staff can cast **charm person** and **charm monster** spells, and can grant a power equivalent to a **potion of plant control**. Each function uses one charge.

**Staff of Healing:** This staff can heal 1d6+1 hit points per charge expended, as the spell **cure light wounds**. Alternately, with an expenditure of two charges, the staff can cast **cure disease**. This staff is only usable by a Cleric.

**Staff of Power:** This is a very potent magic item, with offensive and defensive abilities. It is usually topped with a glistening gem, its shaft straight and smooth. It has the following powers costing one charge per use: **lightning bolt**(6d6 damage), **fireball** (6d6 damage), **cone of cold** (as the wand, for 6d6 damage), **continual light**, and **telekinesis** (as the ring, lasting at most 1d6 turns). The staff is also a +2 walking staff, and can be used exactly as a **staff of striking**. A staff of power can be used for a retributive strike, requiring it to be broken by its wielder. All charges currently in the staff are instantly released in a 30' radius, doing 1d6 damage per charge remaining (save vs. Spells for half damage). All within the area, including the wielder, are affected by this.

After all charges are used up from the staff, it remains a +2 walking staff. Once empty of charges, it cannot be used for a retributive strike.

**Staff of Striking:** This staff has no attack bonus, but is treated as a +1 weapon with respect to what sorts of monsters it can hit (and is usable by any class in that mode). This staff's primary power may only be used if wielded by a Cleric: By uttering a command word, the Cleric may create an effect similar to the spell **striking**. Expenditure of one charge adds 1d6 damage to the weapon's next strike; expenditure of two charges adds 2d6, and expenditure of three charges adds 3d6 damage. If the weapon is not successfully used after the command word has been spoken, the effect dissipates after one turn.

**Staff of Wizardry:** This staff is equivalent to the** staff of power**, above, and has the following powers as well: **invisibility**, **passwall**, **web**, and **conjure elementals** (as the spell, but conjuring staff elementals as described in the **Monsters** section). These powers each use one charge when activated.

**Wand of Cold:** This wand generates a conical blast of cold doing 6d8 damage (save vs. Magic Wands for half damage). The cone spreads from the tip of the wand to a width of 30' at a distance of 40' away.

**Wand of Enemy Detection:** The effect of this wand is to make all enemies of the user within 60' glow with a greenish white light for one round. Even hidden or invisible enemies glow in this way, revealing them, but enemies completely out of sight (such as behind a wall) may not be seen by the user. An "enemy" is any creature which is thinking of or otherwise intending to harm the user; also, all undead monsters and animated constructs within range will glow in this way regardless of intent or thoughts (or lack thereof).

**Wand of Fear:** This wand generates the effect of the spell **cause fear** (the reverse of the spell **remove fear**).

**Wand of Fireballs:** This wand generates **fireball**s, exactly as the spell, doing 6d6 damage.

**Wand of Illusion:** This wand allows the user to create illusions equivalent to the spell **phantasmal force**.

**Wand of Lightning Bolts:** This wand generates **lightning bolts**, exactly as the spell, doing 6d6 damage.

**Wand of Magic Detection:** This wand grants the user a power equivalent to the spell **detect magic**.

**Wand of Paralyzation:** This wand creates the effect of the spell **hold person**.

**Wand of Polymorph:** This wand can be used to cast either **polymorph self** or **polymorph other**.

**Wand of Secret Door Detection:** This wand grants the user a power similar to the spell **find traps**, but which reveals secret doors rather than traps.

**Wand of Trap Detection:** This wand grants the user a power equivalent to the spell **find traps**.

### Miscellaneous Items

These items may take any of several forms, and have a
variety of effects; when randomly rolled, the effect is
determined first (as explained with the tables above)
and then the form is rolled on a separate table.
Generally, such an item is written as a [**Form**] of
[**Effect**], for example, a **Cloak of Fire Resistance**.

Items with forms meant to be worn are limited in that
only a normal number may be used at one time: at
most two rings (one on each hand), one cloak, a pair of
boots, one helm, and one pendant. If a character is
wearing two items that grant the same continuous
effect, such as **Cold Resistance** or **Protection**, only
one such item will function. If the items have differing
levels of effect, such as a **Cloak of Protection +1** and a
**Ring of Protection +3**, only the more powerful item
will operate (in this case, the ring).

While the tables on page 167 provide standard forms
for miscellaneous items, the Game Master is in no way
limited to what appears on the Form of Item table;
items may be created with forms not normally allowed
there, or indeed even in forms that are not there at all.

### Miscellaneous Item Effects

**Blasting**: When this device is played (as appropriate
for its form), it creates a powerful blast of sound filling a
cone 10’ long and 2’ wide at the base. Those within
the area of effect suffer 2d6 points of damage and are
deafened for 1 full turn. A successful saving throw vs.
Death Ray reduces damage by half and reduces the
period of deafness to a single round.

The device can also be used to damage or destroy
buildings, fortifications, etc. Double the damage listed
above when this item is used against a structure. The
[Stronghold](gm02.qmd#strongholds) rules in the Game Master section contains
further guidance on this.

**Blending**: The wearer of this item becomes nearly
invisible, granting an 80% chance that the wearer can
move about unnoticed. If detected by onlookers, the
wearer can be attacked without significant penalty.

**Cold Resistance**: The wearer of this device receives
protection as the spell resist cold, but the protection
works continually.

**Comprehension**: The wearer of this device is granted
the ability to read any language, including any form of
magical script. Being able to read magic does not
confer magical abilities upon the wearer, but if worn by
a magic-user it grants the effects of **read magic**
constantly. Note that when reading non-magical texts,
the limitations described under the spell **read languages** apply to this device also.

**Control Animal**: The wearer of this device can charm
up to 6 hit dice of animals. The effect works much like
a [charm person](allSpells.qmd#charm-animal) spell, but only affects animals
(including giant-sized animals, but excluding fantastic
creatures as well as anything more intelligent than a dog
or cat). The wearer can activate the power at will,
targeting any animal within 60' that they can see. The
wearer may choose to end the effect for one or more
controlled creatures at any time, in order to "free"
enough hit dice to control a new target.

**Control Human**: The wearer of this device may cast
the spell [charm person](allSpells.qmd#charm-person) at any target they can see
within 60'. The wearer can use this power once per
round, at will. If more than one humanoid is to be
affected, the wearer cannot control more than 6 hit dice
or levels of humanoids at a time; however, the wearer
may choose to end the effect for one or more
controlled creatures at any time, in order to "free"
enough hit dice or levels to control a new target.

**Control Plant**: The wearer of this device may create
an effect equivalent to a **Potion of Plant Control** at
will, affecting plants or plant creatures within 60' that
they can see. The effect lasts as long as the wearer
remains within 60' of the plants or plant creatures. A
saving throw is allowed just as for the potion.

**Courage**: When this device is played, all characters
and creatures friendly to the user within 60 feet are
affected as by the spell [remove fear](allSpells.qmd#remove-fear).

Deception: This device grants to the wearer the power
of the Deceiver (as described on page 75). Any
attacker will believe the wearer is 3 feet from their true
location, and the attacker's first strike will always miss.
Thereafter, the attacker suffers a penalty of -2 on all
attack rolls. This ring does not affect mindless
creatures, constructs such as golems or living statues, or
any sort of undead. Living creatures which are not
mindless will be affected even if they do not use sight to
target the wearer.

Delusion: Whoever wears this device believes it is
some other form of useful magical device, and behaves
thus (so for example, if Darion believes he is wearing a
**Ring of Invisibility** he will believe himself to actually be
invisible). Unlike the potion of the same name, the
device's effect is not dispelled by the wearer suffering
damage; in fact, the only way to rid a character of this
cursed item is with the spell [remove curse](allSpells.qmd#remove-curse).

**Djinni Summoning**: Each device of this type has a
specific djinni bound to it, which will be summoned to
the wearer's location when they rub the device while
wearing it. The djinni appears in the next round and
protects, serves, and obeys the wearer. The djinni will
serve at most 1 hour per day, and can be summoned at
most once per day. If the djinni bound to a device is
ever slain, the ring loses all magical properties.

**Doom**: When this device is played (as appropriate for
its form), this device will create animated skeletons or
zombies as if by the spell [animate dead](allSpells.qmd#animate-dead). Up to 3d6 hit
dice of undead monsters will be so created from
remains within a 60' radius of the character who
activated the device. If both skeletal and fleshy remains
are available in the area of effect, skeletons will be
animated in preference over zombies. If the user is a
magic-user or cleric, the created undead may be
controlled so long as that character retains the device.
If played by a fighter or thief, the undead created will
be uncontrolled, and will attack any living creatures
nearby. The device may be used once per day, but no
more than 18 hit dice of undead created by it may exist
at any one time.

**Fire Resistance**: The wearer of this device receives
protection as the spell [resist fire](allSpells.qmd#resist-fire), but the protection
works continually.

**Invisibility**: The wearer of this device can become
invisible (as the spell [invisibility](allSpells.qmd#invisibility)) on command. If the
invisibility is dispelled (as described for the spell), the
device may not be reactivated for one full turn. The
invisibility effect otherwise lasts for 24 hours.
Levitation: The wearer of this device may levitate (as
the spell) at will by concentrating. There is no limit to
how long this device may be used.

**Mind Reading**: Whoever wears this device has access
to a permanent form of the spell [mind reading](allSpells.qmd#mind-reading); it is
always available but only activates when the wearer
spends a full round concentrating upon it, and persists
until the wearer ceases to use it. The effect can be
activated as many times per day as the wearer wants.

**Panic**: When this device is played (as appropriate for
its form), all creatures more than 20 feet from the user
but not over 120 feet away must save vs. Spells or be
affected as by the spell [cause fear](allSpells.qmd#remove-fear).

**Penetrating Vision**: On command, and for so long
thereafter that the wearer concentrates on it, this device
confers the power to see through solid matter as if it
were transparent as glass. The effect extends at most
20 feet, and the wearer sees as if in normal light even if
they are in fact in total darkness.

This effect is blocked by certain materials; the wearer
can see through at most 3 feet of wood or soil, 1 foot of
stone, or 1 inch of most metals. Gold or lead no thicker
than foil will completely block the effect.

The device may be used three times per day, and each
use lasts at most one turn.

**Protection**: The wearer of an item with this power
receives the listed benefit (from +1 to +3) to their
Armor Class for so long as the ring is worn. This bonus
is also applied to the wearer's saving throw die rolls.

**Protection from Energy Drain**: This device has the
power to absorb and neutralize energy-draining attacks,
death spells or effects (such as slay living), and curses
that would otherwise affect the wearer. The device has
2d6 charges when found, and each negative level,
curse, or spell absorbed consumes one charge. When
the device's charges are exhausted it disintegrates into
golden sparkles and disappears.

**Protection from Scrying**: The wearer of this item is
immune to all forms of scrying (including crystal balls,
clairvoyance, clairaudience, and any other means of
location or spying at a distance) as well as any form of
mind reading. Other characters who are within 30' of
the wearer are also immune to scrying, but not to mind
reading

**Regeneration**: This device grants the wearer the
power of regeneration, exactly as described in the
description of the Troll on page 151, including the
weakness with respect to acid and fire damage. Note
that this device will only heal damage suffered while it is
worn; pre-existing damage is not healed by putting on
the device.

**Scrying**: This device can be used to spy upon other
people or locations, regardless of distance. A scrying
device may only be used by Magic-Users. It can be
used three times per day, for up to a turn each time.
The chance of success when using a scrying device is as
shown below. Total chances equal to or greater than
100% do not require a roll.

| **Knowledge and Connection** | **Chance** |
|----|-----|
| Secondhand Knowledge (heard of) | 25% |
| Firsthand Knowledge (seen briefly) | 55% |
| Familiar (known well) | 95% |
| Possession or garment | +25% |
| Body part, lock of hair, bit of nail, etc. | +50% |

The user of the device is the only one who will see the
image. No sound will be heard normally. **Detect magic, detect evil, and mind reading** have a 3%
chance per level of the caster of operating correctly if
used with a scrying device.

**Scrying, Superior**: This item works exactly like a
standard scrying device, as described above, but also
allows the user to hear any sounds in the location
viewed as if they were there.

**Speed**: The wearer of this device can activate it with a
command word (or by clicking their heels together, if
the item takes the form of boots) and gain the effect of
a [haste](allSpells.qmd#haste) spell, and can end the effect the same way.
The effect can be used for a total of 10 rounds each
day.

**Spell Storing**: These much sought-after devices each
contain a number of spells which can be cast by the
wearer. Most of them contain Magic-User spells, but 1
in 10 contains Clerical spells instead. *No device may contain spells of both types*! Each spell stored in the device is cast as if by the lowest-level character who
could normally cast the spell, but not less than 6th level
in any case.

Any class may wear and use this device, but it can only
be recharged by casting the appropriate spell into it. A
table is provided below to determine how many spells,
and what levels they are. A spell storing device must be
recharged with the same spells that were placed into it
when it was made; so a **Pendant of Two Spell Storing**
containing fireball and fly can only be recharged with
those two spells.

The wearer of one of these devices automatically knows
the names of the spells stored within it, but is not
granted detailed knowledge of how each spell works. If
the wearer is not a magic-user and no such character is
available to advise the wearer, there may be some
difficulty in using it successfully (and safely).

A device of this type found in a treasure hoard may be
completely charged, or discharged, or partially charged,
at the GM's option.

| d%    | no of Spells | d%    | Level of Spell |
|-------|--------------|-------|----------------|
| 01-24 | 1            | 01-30 | 1st            |
| 25-48 | 2            | 31-55 | 2nd            |
| 49-67 | 3            | 56-75 | 3rd            |
| 68-81 | 4            | 76-85 | 4th            |
| 82-91 | 5            | 86-97 | 5th            |
| 92-96 | 6            | 98-00 | 6th            |
| 97-00 | 7            |       |                |

**Spell Turning**: This device reflects spells cast directly
at the wearer, but not area effect spells, back at the
caster; so a [hold person](allSpells.qmd#hold-person) spell would be reflected, but
not a [fireball](allSpells.qmd#fireball). It will reflect up to 2d6 spells before its
power is exhausted.

**Stealth**: The wearer of this device can move quietly in
virtually any surroundings, granting a 90% chance of
success when moving silently (as the Thief ability of the
same name).

**Telekinesis**: The wearer of this device can use the
power of the spell [telekinesis](allSpells.qmd#telekinesis), as if cast by a 12th level
Magic-User. The effect may be used as many times per
day as the wearer wishes, but lasts only as long as the
wearer concentrates on it.

**Telepathy**: Three times per day this item can be
activated by use of its command word, at which point it
will grant the wearer the power of a special version of
the [mind reading](allSpells.qmd#mind-reading) spell which has a range of 90 feet
and lasts for 1 turn. During this time the wearer can
send thoughts to the mind of any creature whose
thoughts the wearer is already reading, allowing
communication.

**Teleportation**: Upon command the wearer of this item
may cast the spell [teleportation](allSpells.qmd#teleport) as if by a wizard of the
12th level of ability. This power can be used up to 3
times per day.

**True Seeing**: Three times per day this device can grant
the user the power of the spell [true seeing](allSpells.qmd#true-seeing). Each use
lasts at most one turn.

**Water Walking**: This device allows the wearer to walk
on any liquid as if it were firm ground. Mud, oil, snow,
quicksand, running water, ice, and even lava can be
traversed easily, since the wearer’s feet hover an inch or
two above the surface. Molten lava will still cause the
wearer damage from the heat since they are still near it.
The wearer can walk, run, or otherwise move across
the surface as if it were normal ground.

**Weakness**: Whoever puts this device on is cursed;
their Strength score is reduced immediately to 3. The
device can only be removed with remove curse.

**Wishes**: This device contains the power to grant
wishes to the wearer. 1d4 wishes will remain within the
ring when it is found. The GM must adjudicate all
wishes, and instructions are given in the **Game Master**
section regarding this.

### Rare Items

**Bag of Devouring**: This device appears, to all tests, to
be a normal **Bag of Holding**, and in fact it performs
exactly like one at first. However, all items placed
within disappear forever 1d6+6 turns later. The bag
continues to weigh whatever it did after the items were
placed within it (that is, one-tenth the total weight of the
items), until it is opened and discovered to be empty.

**Bag of Holding**: This device is a bag which appears to
be about 2 feet wide and 4 feet deep. It opens into an
extradimensional space, and is able to hold more than
should be possible: up to 500 pounds of weight, and up
to 70 cubic feet of volume. The bag weighs one-tenth
as much as the total of the objects held within. Any
object to be stored in the bag must fit through the
opening, which has a circumference of 4 feet.

Puncturing or tearing the bag will destroy its magic and
cause all contents to be lost forever. If this item is
turned inside out all contents are dumped. The bag is
unharmed, but it will no longer work until it is turned
right side out again. If living creatures are placed inside
they will suffocate within a turn (with exceptions for
creatures resistant to suffocation as determined by the
GM). The bag's volume cannot be overfilled (as excess
items simply cannot be put inside), but if overloaded
above 500 pounds and then lifted it will be torn.

Getting any particular item from the bag requires the
bearer to spend a round searching during which no
movement may be made.

**Boots of Traveling and Leaping**: These boots allow
the wearer to make great leaps, jumping up to 10' high
and/or 30' across. They improve the wearer's
movement so greatly that they also increase their
movement rate on land by an additional 10' per round.

**Broom of Flying**: This broom is able to fly through the
air for up to 9 hours per day (split up as its owner
desires). The broom can carry 200 pounds and fly at a
speed of 40 feet, or up to 400 pounds at a speed at 30
feet. In addition, the broom can travel alone to any
destination named by the owner as long as they have a
good idea of the location and layout of that destination.
It comes to its owner from as far away as 300 yards
when the command word is spoken.

**Efreeti Bottle**: This item may appear as an ornate
bottle, or sometimes as a magic lamp. It can be
activated once per day, by opening it if it takes the form
of a bottle or by rubbing it if it takes the form of a lamp.
When activated, smoke pours out and forms into an
efreeti.

The efreeti released was trapped in the bottle and
forced to serve whoever activates it. However, an
efreeti who has spent too long in a bottle may have lost
its mind, and if this happens the efreeti will begin a
frenzied attack upon whoever activated the bottle,
disappearing when either the user of the bottle or the
efreeti is dead. There is, fortunately, only a 1 in 10
chance this will happen.

On the other hand, there is also a 1 in 10 chance that
the efreeti of the bottle is able to grant three wishes to
the user. If this is the case, the efreeti will perform no
other service, and cannot return to the bottle after it is
activated until the user makes a wish. Subsequent
wishes require additional activations, and upon the final
wish being granted the efreeti disappears for good.

Roll 1d10 when the bottle is first activated; on a roll of
1, the efreeti is insane, while on a roll of 0 the efreeti
has three wishes to grant. If neither of these results is
rolled, the efreeti will serve the user for up to one hour
per day for 101 days, after which time it is freed and
will disappear. Note that after the first activation, every
day that passes is counted toward the 101 days
whether or not the user activates the bottle.

**Flying Carpet**: This item appears to be a fancy rug of
the sort found in the castle of a king. It has the power
to fly, carrying those upon it as if they stand upon a
solid surface. A flying carpet is typically 5' x 8' in size
and can carry up to 500 pounds at a movement rate of
100' per round, or up to 1,000 pounds (its maximum
capacity) at a rate of 50' per round. A flying carpet can
fly at any speed up to its maximum, and can hover on
command.

**Gauntlets of Ogre Power**: These thick leather gloves
grant the wearer a Strength bonus of +4 (instead of
their own Strength bonus). Both gauntlets must be
worn for the magic to be effective.

**Girdle of Giant Strength**: This broad leather belt
grants the wearer the strength of a giant. For so long as
it is worn, the wearer gains a Strength bonus of +5
(instead of their own Strength bonus), and can throw
large stones just as a stone giant does.

**Mirror of Imprisonment**: This item can appear as any
style of full-length or larger mirror. It is a form of
magical trap, which can be set or deactivated by
speaking a command word followed by "activate" or
"deactivate."

When in its active state, any character or creature who
stands within 30 feet of the mirror and sees its reflection
must save vs. Spells or be drawn bodily into the mirror,
including all items worn or carried. The victim is placed
within one of 20 metaphysical cells inside the mirror.
Those trapped in the mirror are mere reflections and
are unable to take any action. The last character who
spoke the command word to the mirror is immune to its
power, as are undead, constructs, and any creature that
lacks eyes.

A character who speaks the command word and then
calls the number of a cell will cause the reflection of the
occupant of that cell to appear in the mirror. The
trapped creature can move and speak, but cannot cast
spells or take any other real action. The controlling
character may interrogate the trapped victim if desired,
though the mirror does not compel the victim to
respond or to be truthful. The controller may at any
time speak the command word again and say "return"
and the victim will be returned to its cell; or, the
controller can say the command word followed by
"come out" to free the victim, who appears standing
beside the controller.

Should all cells be full when a creature is drawn inside,
one cell chosen at random will be emptied with the
freed creature appearing where the trapped one had
been standing. The freed creature is safe from the
mirror for one turn thereafter before it can again be
trapped. All victims will be freed instantly if the mirror
is broken.

**Rope of Climbing**: This 50 foot long rope is about ½
inch in diameter, but is capable of supporting up to
3,000 pounds if tied to a secure anchor point. When
the user holds one end of the rope and speaks the
command word, the rope animates, moving like a
snake at a rate of 10' per round in whatever direction
the user commands. The rope is even able to move
into a completely vertical position if so ordered. It can
be commanded to tie itself to any anchor point within
reach (since the user must continue holding one end of
the rope, it can reach no more than 50 feet from that
point). The rope has no real strength and thus cannot
lift or support any weight if not tied to an anchor point.

### Devices for Summoning Elementals

These devices all grant the power to summon and
control an elemental. As noted, the GM is likely to
choose to allow only certain types of Elementals, so not
all of these devices may be available in your campaign.

When one of these devices is activated in accordance
with the summoning rules described for the Elemental
monster entry on page 88, an appropriate elemental
appears and follows the summoner's commands.

**Bowl of Summoning Water Elementals**: This device
is about the size of a punch bowl, and will be made of
precious metals set with jewels. To activate this device,
it must be filled with fresh water (at least a quart) and
the command words inscribed around its rim must be
spoken, which requires a full round to complete.

**Brazier of Summoning Fire Elementals**: This device
appears to be a small brazier, a metal bowl with legs
and cage-like sides which stands about a 1½ feet tall.
Braziers are meant to hold fire. To activate this device,
a fire must be built in this brazier and the command
words inscribed around its rim-band must be spoken,
which requires a full round to complete.

**Censer of Summoning Air Elementals**: This device
appears to be an ornate but ordinary censer, a kind of
bowl with a perforated lid and a chain which is used to
lift and swing the device. These are normally used in
worship, but this device is made for a different purpose.
To activate this device, incense must be placed in the
bowl, lit, and covered, and the command words
inscribed around the edge of the lid must be spoken,
which requires a full round to complete.

**Crucible of Summoning Metal Elementals**: This
device appears to be a small crucible, an open-topped
vessel used for melting metal. To activate this device, it
must be placed on a solid, adequately heat-resistant
surface and the command words inscribed around the
edge of the lid must be spoken, which requires a full
round to complete.

The crucible becomes very hot while the metal
elemental is present, causing 2d8 points of damage to
any character who dares to touch it barehanded and
2d6 points even if wearing armor or ordinary fabric or
leather gloves. The crucible requires a full turn to cool
after use.

**Mallet of Summoning Wood Elementals**: This is a
wooden mallet of the sort used by builders to drive in
pegs; though it could be used as a weapon, it is a poor
excuse for one as it does just 1d4 points of damage on
a hit and is not treated as a magic weapon. To activate
this device, it must be held in the hand and the
command words inscribed on one side of the hammer-
head must then be spoken, which requires a full round
to complete.

**Marble Plate of Summoning Cold Elementals**: This
device is a circular plate of marble about 9 inches in
diameter and about ¾ of an inch thick. To activate this
device, it must be placed level on a solid, stable surface
and a full skin of fresh water must be poured upon it; as
the water touches the base it magically freezes into a
small sculpture of a cold elemental. The command
words inscribed around the rim of the plate must then
be spoken, which requires a full round to complete.

**Rod of Summoning Lightning Elementals**: This
device appears as a copper rod about ¾ inch thick and
2 feet long, tipped with a polished ball of amber. The
rod will have a smooth, polished green surface (a thin
coating of verdigris) but will not be pitted or damaged
by the corrosion. To activate this device it must be held
in the hand and the command words inscribed on the
length of the rod must then be spoken, which requires a
full round to complete.

**Stone of Summoning Earth Elementals**: This device
is a roughly-cut but highly-polished stone in which a
vein or cluster of precious or semi-precious stones is
visible. To activate this device, it must be held in the
user's hands and the command words inscribed on the
smoothest area of the stone must be spoken, which
requires a full round to complete.