# Monsters Intro

## Terms

**Name:** The first thing given for each monster is its name (or its most common name, if the monster is known by more than one). If an asterisk appears after the monster's name, it indicates that the monster is only able to be hit by special weapons (such as silver or magical weapons, or creatures affected only by fire, etc.) which makes the monster harder to defeat.

**Armor Class:** This line gives the creature's AC for normal combat. If the monster customarily wears armor, the first listed AC value is with that armor, and the second, in parentheses, is unarmored. Some monsters are only able to be hit (damaged) by silver or magical weapons; these are indicated with (s); some monsters may only be hit with magical weapons, indicated by (m)

**Hit Dice:** This is the creature’s number of hit dice,
including any bonus hit points. Monsters always roll
eight sided dice (d8) for hit points, unless otherwise
noted. So for example, a creature with 3+2 hit dice
rolls 3d8 and adds 2 points to the total. A few monsters
may be marked as having ½ hit dice; this means 1d4
points, and the creature has "less than one hit die" for
attack bonus purposes

One or two asterisks (*) may appear after the hit dice figure; where present, they indicate a Special Ability Bonus to experience points (XP) awarded for the monster. See [Character Advancement](advancement.qmd#advancement).

If the monster's **Attack Bonus** (see @tbl-attacking-bonus) is different than its number of Hit Dice, for convenience the Attack Bonus will be listed in parentheses after the Hit Dice figure.

**Movement:** This line gives the monster's movement rate, or rates for those monsters able to move in more than one fashion. For example, Bugbears have a normal walking movement of 30', and this is all that is listed for them. Mermaids can only move about in the water, and so their movement is given as **Swim 40'**. Pegasi can both walk and fly, so their movement is listed as **80' Fly 160'**.

In addition, a distance may appear in parentheses after a movement figure; this is the creature's [turning distance](combat.qmd#maneuverability). If a turning distance is not listed, assume 5'.

**Attacks:** The number (and sometimes type or types) of attacks the monster can perform. For example, Goblins may attack once with a weapon, so they are marked **1 weapon**. Ghouls are marked **2 claws/1 bite** as they can attack with both claws and also bite in one round. Some monsters have alternate
attacks, such as the triceratops with an attack of 1 gore
or 1 trample which means that the creature can do a
gore attack or a trample attack, but not both in the
same round.

**Damage:** The damage figures caused by successful attacks by the monster. Generally this will be defined in terms of one or more die rolls.

**No. Appearing:** This is given in terms of one or more die rolls. Monsters that only appear underground and have no lairs will have a single die roll; those that have lairs and/or those that can be found in the wilderness will be noted appropriately. For example, a monster noted as "1d6, Wild 2d6, Lair 3d6" is encountered in groups of 1d6 individuals in a dungeon setting, 2d6 individuals in the wilderness, or 3d6 individuals in a lair.

Note that number appearing applies to combatants. Non-combatant monsters (juveniles, and sometimes females) do not count in this number. The text of the monster description should explain this in detail where it matters, but the GM is always the final arbiter.

**Save As:** The character class and level the monster uses for saving throws. Most monsters save as Fighters of a level equal to their hit dice.

**Morale:** The number that must be rolled equal to or less than on 2d6 for the monster to pass a [Morale Check](combat.qmd#morale). Monsters having a Morale of 12 never fail morale checks, and fight until destroyed (or until they have no enemies left). 

**Treasure Type:** This line reflects how much wealth the creature owns. See the [Treasure](treasure.qmd#treasure-types) section for more details. In most cases, a creature keeps valuables in its home or lair and has no treasure with it when it travels. Intelligent creatures that own useful, portable treasure (such as magic items) tend to carry and use these, leaving bulky items at home.

**XP**: The number of experience points awarded for defeating this monster. In some cases, the figure will vary; for instance, Dragons of different age categories will have different XP values. Review the [Experience Points](advancement.qmd#experience-points-xp) awards table in the **Adventure** section, to calculate the correct figure in these cases.


## Beasts of Burden


::: {.table-responsive}

|      | **Camel**    | **Donkey** | **Horse, Draft** | **Horse, Riding** |**Horse, War** | **Mule** | **Pony** | 
|----|-----|----|---|---|-----|----|---|
| Armor Class: | 13 | 13 | 13 | 13 | 13 | 13 | 13 | 
| Hit Dice: | 2 | 2 | 3 | 2 | 3 | 2 | 1 | 
| \# of Attacks: | 1 bite/1 hoof | 1 bite | 2 hooves | 2 hooves | 2 hooves | 1 kick or 1 bite | 1 bite | 
| Damage: | 1/1d4 | 1d2 | 1d4/1d4 | 1d4/1d4 | 1d6/1d6 | 1d4 or 1d2 | 1d4 | 
| Movement: | 50'(10') [40'(10')] | 40' (10') | 60' (10') | 80' (10') | 60' (10') | 40' (10') | 40' (10') | 
| No. Appearing: | Wild 2d4 | Wild 2d4 | domestic only | Wild 10d10 | domestic only | domestic only | domestic only | 
| Save As: | Fighter: 2 | Fighter: 2 | Fighter: 3 | Fighter: 2 | Fighter: 3 | Fighter: 2 | Fighter: 1 | 
| Morale: | 7 | 7 | 7 | 7 | 9 | 7 | 6 (9) | 
| XP: | 75 | 75 | 145 | 75 | 145 | 75 | 25 | 

:::


For convenience, animals commonly used to carry loads and/or characters are listed here together. Such creatures obviously have no treasure.

**Camels** are large animals found in arid environments
that bear distinctive fatty deposits known as "humps" on
their backs. There are two relevant species of camel
described here: the far more common one-humped
dromedary, and the two-humped Bactrian camel.
Statistics presented above are for the dromedary; the
Bactrian camel is slower and its movement is given in
brackets. A light load for a camel is up to 400 pounds;
a heavy load, up to 800 pounds.

**Donkeys** are hoofed mammals in the same family as
the horse. They are smaller, but are strong and hardy.
Burros are a similar species, and the statistics herein can
be used for either; both varieties are capable of being
taken into dungeons as pack animals. A light load for a
donkey is up to 70 pounds; a heavy load, up to 140
pounds.

**Draft Horses** are large horses bred to be working
animals doing hard tasks such as plowing and other
farm labor. There are a number of breeds, with varying
characteristics, but all share common traits of strength,
patience, and a docile temperament. A light load for a
draft horse is up to 350 pounds; a heavy load, up to
700 pounds.

**Riding Horses** are smaller horses bred and trained for
riding. They cannot effectively fight while the rider is
mounted. A light load for a riding horse is up to 250
pounds; a heavy load, up to 500 pounds.

**War Horses** are large, powerful horses which are both
bred for their size, strength, and combat ability and
trained to tolerate the sounds and stresses of battle.
They are able to attack while the rider is mounted due
to their training. A light load for a warhorse is up to
350 pounds; a heavy load, up to 700 pounds

**Mules** are a domestic equine hybrid between a donkey
and a horse. Mules vary widely in size, and may be of
any color. They are more patient, hardier and longer-
lived than horses, and are perceived as less obstinate
and more intelligent than donkeys. Like donkeys, they
are capable of being taken into dungeons as pack
animals. A light load for a mule is up to 300 pounds; a
heavy load, up to 600 pounds.

A **Pony** is a variety of small horse. Compared to a
larger horse, a pony may have a thicker coat, mane and
tail, with proportionally shorter legs, a wider barrel,
heavier bone, a thicker neck and a shorter, broader
head. Ponies can be trained for war, and the morale in
parentheses above is for a war pony; this does not
allow them to fight while a rider is mounted, however.
A light load for a pony is up to 275 pounds; a heavy
load, up to 550 pounds.