---
title: "Spells"
---

The number of spells of each level which a Cleric or Magic-User may cast per day is shown on the appropriate table in the [Classes](class.qmd#character-classes) section. Each day, usually in the morning, spellcasters prepare spells to replace those they have used. Clerics do this through prayer, while Magic-Users must study their spellbooks. Spells prepared but not used persist from day to day; only those actually cast must be replaced. A spellcaster may always choose to dismiss a prepared spell (without casting it) in order to prepare a different spell of that level.

Spellcasters must have at least one hand free, and be able to speak, in order to cast spells; thus, binding and gagging a spellcaster is an effective means of preventing him or her from casting spells. In combat, casting a spell usually takes the same time as making an attack. If a spellcaster is attacked (even if not hit) or must make a saving throw (whether successful or not) on the Initiative number on which he or she is casting a spell, the spell is spoiled and lost. As a specific exception, two spell casters releasing their spells at each other on the same Initiative number will both succeed in their casting; one caster may disrupt another with a spell only if he or she has a better Initiative, and chooses to delay casting the spell until *right before* the other caster.

Some spells are reversible; such spells are shown with an asterisk after the name.

# Cleric Spells

Clerics receive their spells through faith and prayer. Each day, generally in the morning, a Cleric must pray for at least three turns in order to prepare spells. Of course, the Cleric may be expected to pray more than this in order to remain in his or her deity's good graces.

Because they gain their spells through prayer, a Cleric may prepare any spell of any level he or she is able to cast. However, in some cases the Cleric's deity may limit the availability of certain spells; for instance, a deity devoted to healing may refuse to grant reversed healing spells.


::: {.callout-tip icon=false collapse=true}

## Level 1, Clerical

::: {.callout-note icon=false collapse=true}

## Cure Light Wounds*

Cleric 1

Range: touch

Duration: instantaneous

With this spell the caster heals 1d6+1 hit points of damage by laying his or her hand upon the injured creature.

The reverse form of this spell, **cause light wounds**, causes 1d6+1 damage to the creature affected by it. A successful attack roll is required in this case.

Undead are affected by this spell and its reverse in opposite fashion; they are injured by **cure light wounds** and healed by **cause light wounds**.

:::

::: {.callout-note icon=false collapse=true}

## Detect Evil*

Range: 60'

Cleric 1, Magic-User 2

Duration: 1 round/level

This spell allows the caster to detect evil; specifically, the caster can detect creatures with evil intentions, magic items with evil enchantments, and possibly extraplanar creatures of evil nature. Normal characters, even “bad” characters, cannot be detected by this spell, as only overwhelming evil is detectable. The caster sees the “evil” creatures or objects with a definite glow around them, but the glow cannot be seen by anyone else.

The exact definition of evil is left for the GM to decide. Note that items such as ordinary traps or poisons are not “evil,” and thus not detectable by this spell.

Reversed, this spell becomes **detect good**, which works just as described above with respect to detecting “good” enchantments, angelic creatures, and so on.

:::

::: {.callout-note icon=false collapse=true}

## Detect Magic

Range: 60'

Cleric 1, Magic-User 1

Duration: 2 turns

The caster of this spell is able to detect enchanted or enspelled objects or creatures within the given range by sight, seeing them surrounded by a pale glowing light. Only the caster sees the glow. Invisible creatures or objects are not detected by this spell, but the emanations of the invisibility magic will be seen as an amorphous glowing fog, possibly allowing the caster (only) to attack the invisible creature at an attack penalty of only -2.

:::

::: {.callout-note icon=false collapse=true}

## Light*

Range: 120'

Cleric 1, Magic-User 1

Duration: 6 turns + 1/level

This spell creates a light equal to torchlight which illuminates a 30' radius area (and provides dim light for an additional 20') around the target location or object. The effect is immobile if cast into an area, but it can be cast on a movable object. Light taken into an area of magical darkness does not function.

Reversed, **light** becomes **darkness**, creating an area of darkness just as described above. This darkness blocks out Darkvision and negates mundane light sources.

A light spell may be cast to counter and dispel the darkness spell of an equal or lower level caster (and vice versa). Doing so causes both spells to instantly cease, restoring the existing ambient light level.

Either version of this spell may be used to blind an opponent by means of casting it on the target's ocular organs. The target is allowed a saving throw vs. Death Ray to avoid the effect, and if the save is made, the spell does not take effect at all. A **light** or **darkness** spell cast to blind does not have the given area of effect (that is, no light or darkness is shed around the victim).

:::

::: {.callout-note icon=false collapse=true}

## Protection from Evil*

Cleric 1, Magic-User 1

Range: touch

Duration: 1 turn/level

This spell wards a creature from attacks by evil creatures, from mental control, and from summoned creatures. It creates a magical barrier around the subject at a distance of 1 foot. The barrier moves with the subject and has three major effects.

First, the subject gains a +2 bonus to AC and a +2 bonus on saves. Both these bonuses apply against attacks made or effects created by evil creatures. Note that the definition of "evil" is left to the individual GM to decide.

Second, the barrier blocks any attempt to possess the warded creature (by a magic jar attack, for example) or to exercise mental control over the creature (including charm spells or effects). The protection does not prevent such effects from targeting the protected creature, but it suppresses the effect for the duration of the protection from evil effect. If the protection from evil effect ends before the effect granting control does, the would-be controller would then be able to command the controlled creature. Likewise, the barrier keeps out a possessing life force but does not expel one if it is in place before the spell is cast.

Third, the spell prevents bodily contact by summoned creatures (regardless of whether they are "evil" or not). This causes the natural weapon attacks of such creatures to fail and the creatures to recoil if such attacks require touching the warded creature. The protection against contact by summoned creatures ends if the warded creature makes an attack against or tries to force the barrier against the blocked creature.

Reversed, this spell becomes **protection from good**. It functions in all ways as described above, save that "good" creatures are kept away, rather than "evil" creatures.

:::

::: {.callout-note icon=false collapse=true}

## Purify Food and Water

Cleric 1

Range: 10'

Duration: instantaneous

This spell makes spoiled, rotten, poisonous, or otherwise contaminated food and water pure and suitable for eating and drinking. This spell does not prevent subsequent natural decay or spoilage. Unholy water and similar food and drink of significance is spoiled by purify food and drink, but the spell has no effect on creatures of any type nor upon magic potions.

:::

::: {.callout-note icon=false collapse=true}

## Remove Fear*

Range: touch (120')

Cleric 1

Duration: instantaneous

(2 turns)

This spell will calm the creature touched. If the target creature is currently subject to any sort of magical fear, it is allowed a new save vs. Spells to resist that fear, at a bonus of +1 per level of the caster.

The reverse of this spell, **cause fear**, causes one target creature within 120' to become frightened; if the target fails to save vs. Spells, it flees for 2 turns. Creatures with 6 or more hit dice are immune to this effect.

:::

::: {.callout-note icon=false collapse=true}

## Resist Cold

Range: touch

Cleric 1

Duration: 1 round/level

This abjuration grants a creature temporary immunity to cold. Minor cold (such as exposure to winter weather in inadequate clothing) is ignored by the affected creature. Against more significant cold (such as the breath of a White Dragon), the affected creature gains a bonus of +3 on saving throws, and all damage from such attacks is reduced by half (round up).

:::

:::

::: {.callout-tip icon=false collapse=true}

## Level 2, Clerical

::: {.callout-note icon=false collapse=true}

## Bless*

Range: 50' radius

Cleric 2

Duration: 1 minute/level

This spell gives the caster and his or her allies (within a 50' radius of the caster) a bonus of +1 on attack rolls, morale checks (for monsters or NPCs allied with the caster), and saving throws against magical **fear**.

The reverse of **bless** is called **bane**. It fills the caster's enemies (within a 50' radius) with fear and doubt, causing each affected creature to suffer a --1 penalty on attack rolls, morale checks, and saving throws against magical **fear**.

:::
 
::: {.callout-note icon=false collapse=true}

## Charm Animal

Range: 60'

Cleric 2

Duration: level+1d4 rounds

This spell allows the caster to charm one or more animals, in much the same fashion as **charm person**, at a rate of 1 hit die per caster level. The caster may decide which individual animals out of a mixed group are to be affected first; excess hit dice of effect are ignored. No saving throw is allowed, either for normal or giant-sized animals, but creatures of more fantastic nature (as determined by the GM) are allowed a save vs. Spells to resist. When the duration expires, the animals will resume normal activity immediately.

This spell does not grant the caster any special means of communication with the affected animals; if combined with **speak with animals**, this spell becomes significantly more useful.

:::

::: {.callout-note icon=false collapse=true}

## Find Traps

Range: 30'

Cleric 2

Duration: 3 turns

This spell permits the caster to detect a variety of traps, both mechanical and magical. When the caster moves within 30’ of a trap, he or she will see it glow with a faint greenish-blue aura. The caster is not, however, able to detect certain natural hazards such as quicksand, a sinkhole, or unsafe walls of natural rock. The spell also does not bestow the caster with the knowledge needed to disarm the trap, nor any details about its type or nature.

:::

::: {.callout-note icon=false collapse=true}

## Hold Person

Range: 180'

Cleric 2, Magic-User 3

Duration: 2d8 turns

This spell will render any living (not undead) human, demi-human or humanoid creature paralyzed. Creatures larger than ogres will not be affected by this spell. Targets of the spell are aware, and breathe normally, but cannot take any actions, including speech. A successful save vs. Spells will negate the effect. The spell may be cast at a single person, who makes his or her save at -2, or at a group, in which case 1d4 of the creatures in the group may be affected.

A winged creature which is paralyzed cannot flap its wings and falls (if in flight at the time). A paralyzed swimmer can’t swim and may drown.

:::

::: {.callout-note icon=false collapse=true}

## Resist Fire

Range: touch

Cleric 2

Duration: 1 round/level

This abjuration grants a creature temporary immunity to fire and heat. Minor heat or fire (such as exposure to normal flames) is ignored by the affected creature. Against more significant heat or fire (such as a **fireball**), the affected creature gains a bonus of +3 on saving throws, and all damage from such attacks is reduced by half (round up).

:::

::: {.callout-note icon=false collapse=true}

## Silence 15' Radius

Cleric 2

Range: 360'

Duration: 2 rounds/level

Upon the casting of this spell, complete silence prevails within a 15' radius around the target. All sound is stopped: Conversation is impossible, spells cannot be cast, and no noise whatsoever issues from, enters, or passes through the area. The spell can be cast on a point in space, making the effect stationary, or it may be cast on a mobile object. The spell can be centered on a creature, and the effect then radiates from the creature and moves as it moves. An unwilling creature receives a save vs. Spells to negate the spell. If an item in another creature’s possession is targeted, that creature also receives a save vs. Spells to negate. This spell provides a defense against sonic or language-based attacks or spells.

:::

::: {.callout-note icon=false collapse=true}

## Speak with Animals

Cleric 2

Range: special

Duration: 1 turn/4 levels

The caster can comprehend and communicate with any one animal (normal or giant sized, but not magical or monstrous) that is in sight of the caster and able to hear him or her. The caster may change which animal he or she is speaking with at will, once per round. The spell doesn’t alter the animal’s reaction or attitude towards the caster; a standard reaction roll should be made to determine this. Furthermore, more intelligent animals are likely to be terse and evasive, while less intelligent ones make inane comments. However, if an animal is friendly toward the caster, it may be willing to grant some favor or service.

:::

::: {.callout-note icon=false collapse=true}

## Spiritual Hammer

Range: 30'

Cleric 2

Duration: 1 round/level

This spell causes a warhammer made of pure force to spring into existence, attacking any foe chosen by the Cleric within range once per round. It deals 1d6 hit points of damage per strike, +1 point per three caster levels (maximum of +5). It uses the caster's normal attack bonus, striking as a magical weapon, and thus can inflict damage upon creatures that are only hit by magic weapons. If the hammer goes beyond the spell range, the Cleric loses sight of it, or the caster ceases to direct it, the hammer disappears. The hammer cannot be attacked or harmed by physical attacks, but **dispel magic**, **disintegrate**, or a **rod of cancellation** will dispel it.

:::

:::

::: {.callout-tip icon=false collapse=true}

# Level 3, Clerical

::: {.callout-note icon=false collapse=true}

## Continual Light*

Range: 360'

Cleric 3, Magic-User 2

Duration: 1 year/level

This spell creates a spherical region of light, as bright as full daylight up to a 30' radius, with light of lesser intensity to a radius of 60'. Continual light can be cast on an object, into the air, or at a creature, just as with the **light** spell, up to a maximum range of 360' from the caster. The spell remains in effect for one year per level of the caster.

As with **light**, this spell can be used to blind a creature if cast on its visual organs. Creatures targeted by this spell are allowed a save vs. Death Ray; if the save is made, the spell is cast into the air just behind the target creature. A penalty of -4 is applied to the blinded creature's attack rolls if the saving throw fails.

The reversed spell, **continual darkness**, causes complete absence of light in the area of effect, overpowering normal light sources. Continual darkness may be used to blind in the same way as continual light.

:::

::: {.callout-note icon=false collapse=true}

## Cure Blindness

Range: touch

Cleric 3

Duration: instantaneous

With this spell the caster can cure a creature suffering blindness (whether caused by injury or by magic, including **light** or **continual light**). Blindness caused by a curse cannot be cured by this spell.

:::

::: {.callout-note icon=false collapse=true}

## Cure Disease*

Range: touch

Cleric 3

Duration: instantaneous

Cure disease cures all diseases that the subject is suffering from. The spell also kills parasites afflicting the target creature. Certain special diseases may not be countered by this spell or may be countered only by a caster of a certain level or higher.

Note: This spell does not prevent reinfection after a new exposure to the same disease.

:::

::: {.callout-note icon=false collapse=true}

## Growth of Animals

Cleric 3

Range: 60'+10'/level

Duration: 1 turn/level

This spell causes an animal to grow to twice its normal size and eight times its normal weight. The affected creature will do double normal damage with all physical attacks, and its existing natural Armor Class increases by 2. The animal's carrying capacity is also doubled. Unfriendly animals may save vs. Spells to resist this spell; normally, domesticated animals will not attempt to resist it, though they may become confused or panicky afterward (at the GM's discretion).

All equipment worn or carried by an animal is similarly enlarged by the spell, though this change has no effect on the magical properties of any such equipment. Any enlarged item that leaves the enlarged creature’s possession instantly returns to its normal size.

The spell gives no means of command or influence over the enlarged animals.

:::

::: {.callout-note icon=false collapse=true}

## Locate Object

Range: 360'

Cleric 3, Magic-User 2

Duration: 1 round/level

This spell allows the caster to sense the direction of a well-known or clearly visualized object. He or she can search for general items, in which case the nearest one of its kind is located if more than one is within range. The caster cannot specify a unique item unless he or she has observed that particular item firsthand (not merely through divination such as **clairvoyance** or a **crystal ball**). The spell is blocked by even a thin sheet of lead or gold. Creatures cannot be found by this spell.

:::

::: {.callout-note icon=false collapse=true}

## Remove Curse*

Range: 30'

Cleric 3, Magic-User 4

Duration: instantaneous

Remove curse instantaneously removes all curses on an object or a creature. Remove curse does not remove the curse from a cursed shield, weapon, or suit of armor, although the spell typically enables the creature afflicted with any such cursed item to remove and get rid of it. Certain special curses may not be countered by this spell or may be removed only by a caster of a certain level.

The reverse of this spell, **bestow curse**, allows the caster to place a curse on the subject. A save vs. Spells is allowed to resist. The caster must choose one of the following three effects:

--4 decrease to an ability score (minimum 1).

--4 penalty on attack rolls and saves.

Each round of combat, the target has a 50% chance to act normally; otherwise, it takes no action.

The caster may also invent his or her own curse, but it should be no more powerful than those described above. The curse thus bestowed cannot be dispelled, but it can be removed with a **remove curse** spell.

:::

::: {.callout-note icon=false collapse=true}

## Speak with Dead

Range: 10'

Cleric 3

Duration: 3 rounds/level

This spell grants the semblance of life and intellect to a corpse, allowing it to answer several questions that the caster puts to it. The caster may ask one question per two caster levels. Unasked questions are wasted if the duration expires. The corpse’s knowledge is limited to what the creature knew during life, including the languages it spoke (if any). Answers are often brief, cryptic, or repetitive.

If the corpse has been subject to speak with dead within the past week, the new spell fails. The caster can cast this spell on a corpse that has been deceased for any amount of time, but the body must be mostly intact to be able to respond. A damaged corpse may be able to give partial answers or partially correct answers, but it must at least have a mouth in order to speak at all.

This spell does not let the caster actually speak to the person (whose soul has departed). It instead draws on the imprinted knowledge “stored” in the corpse. The partially animated body retains the imprint of the soul that once inhabited it, and thus it can speak with all the knowledge that the creature had while alive. The corpse, however, cannot learn new information. Indeed, it can’t even remember being questioned.

This spell does not affect a corpse that has been turned into an undead creature.

:::

::: {.callout-note icon=false collapse=true}

## Striking

Range: touch

Cleric 3

Duration: 1 round/level

This spell bestows upon one weapon the ability to deal 1d6 points of additional damage. This extra damage is applied on each successful attack for the duration of the spell. It provides no attack bonus, but if cast on a normal weapon, the spell allows monsters only hit by magical weapons to be affected; only the 1d6 points of magical damage applies to such a monster, however.

:::

:::

::: {.callout-tip icon=false collapse=true}

# Level 4, Clerical

::: {.callout-note icon=false collapse=true}

## Animate Dead

Range: touch

Cleric 4, Magic-User 5

Duration: special

This spell turns the bones or bodies of dead creatures into undead skeletons or zombies that follow the caster's spoken commands. They remain animated until they are destroyed. The caster may animate a number of hit dice of undead equal to twice his or her caster level, and no more. Animated skeletons have hit dice equal to the number the creature had in life; for skeletons of humans or demi-humans, this means one hit die, regardless of the character level of the deceased. Zombies have one more hit die than the creature had in life. An animated skeleton can be created only from a mostly intact skeleton; a zombie can be created only from a mostly intact corpse. The caster must touch the remains to be animated. No character may normally control more hit dice of undead than 4 times his or her level, regardless of how many times this spell is cast.

:::

::: {.callout-note icon=false collapse=true}

## Create Water

Range: 10'

Cleric 4

Duration: permanent

This spell creates one gallon of water per caster level. Note that one or more vessels to contain the water must be available at the time of casting. The water created by this spell is just like clean rain water. Note: Water weighs about 8 pounds per gallon, and one cubic foot of water is roughly 8 gallons.

:::

::: {.callout-note icon=false collapse=true}

## Cure Serious Wounds*

Cleric 4

Range: touch

Duration: instantaneous

This spell works exactly like **cure light wounds,** save that it heals 2d6 points of damage, plus 1 point per caster level. The reverse, **cause serious wounds**, also works exactly like **cause light wounds**, except that it inflicts 2d6 + caster level in damage.

:::

::: {.callout-note icon=false collapse=true}

## Dispel Magic

Range: 120'

Cleric 4, Magic-User 3

Duration: instantaneous

The caster can use dispel magic to end ongoing spells that have been cast on a creature or object, or to end ongoing spells (or at least their effects) within a cubic area 20' on a side. The caster must choose whether to dispel magic on a creature or object, or to affect an area.

If dispel magic is targeted at a creature, all spell effects (including ongoing potion effects) may be canceled. If cast upon an area, all such effects within the area may be canceled. Any spell or effect having a caster level equal to or less than the **dispel magic** caster's level is ended automatically. Those created by higher level casters might not be canceled; there is a 5% chance the dispel magic will fail for each level the spell effect exceeds the caster level. For example, a 10^th^ level caster dispelling magic created by a 14^th^ level caster has a 20% chance of failure.

Some spells cannot be ended by dispel magic; this specifically includes any curse, including those created by **bestow curse** (the reverse of **remove curse**) as well as by cursed items.

:::

::: {.callout-note icon=false collapse=true}

## Neutralize Poison*

Range: touch

Cleric 4

Duration: instantaneous

This spell detoxifies any sort of venom in the creature or object touched. A poisoned creature suffers no additional effects from the poison; if cast upon a creature slain by poison in the last 10 rounds, the creature is revived with 1 hit point. If cast upon a poisonous object (weapon, trap, etc.) the poison is rendered permanently ineffective.

Reversed, this spell becomes **poison**. The caster must make a successful attack roll; if the attack is a success, the target must save vs. Poison or die. The caster's touch remains poisonous for 1 round per level of ability, or until discharged (i.e. only one creature can be affected by the reversed spell).

:::

::: {.callout-note icon=false collapse=true}

## Protection from Evil 10' radius*

Spell text 

:::

::: {.callout-note icon=false collapse=true}

## Speak with Plants

Range: 20'

Cleric 4

Duration: 1 turn

The caster can comprehend and communicate with both normal plants and plant creatures. A normal plant’s sense of its surroundings is limited, so it won’t be able to give (or recognize) detailed descriptions of creatures or answer questions about events outside its immediate vicinity. The spell doesn’t alter the plant’s reaction or attitude towards the caster; however, normal plants will generally communicate freely with the caster, as they have nothing else of importance to do. Intelligent plant creatures are more likely to be terse and evasive, behaving in much the same fashion as any other monster. If a plant creature is friendly toward the caster, it may decide to do some favor or service for him or her. Normal plants are usually not animate, and thus cannot generally perform “services” other than to answer questions.

:::

::: {.callout-note icon=false collapse=true}

## Sticks to Snakes

Range: 120'

Cleric 4

Duration: 6 turns

This spell transforms normal wooden sticks into 1d4 hit dice worth of normal (not giant) snakes per every four caster levels. (See the **Monsters** section for details on types of snakes.) The snakes follow the commands of the caster. When slain, dispelled, or the spell expires, the snakes return to their original stick form. Magical “sticks” such as enchanted staves cannot be affected.

:::

:::

::: {.callout-tip icon=false collapse=true}

# Level 5, Clerical

::: {.callout-note icon=false collapse=true}

## Commune

Range: self

Cleric 5

Duration: 1 round/level

This spell puts the caster in contact with his patron deity or an extraplanar servant thereof, who answers one yes-or-no question per caster level. The ritual to cast this spell takes 1 turn to complete. The being contacted may or may not be omniscient, and further, though the being is technically allied with the caster, it may still not answer questions clearly or completely. These details are left to the GM's discretion.

:::

::: {.callout-note icon=false collapse=true}

## Create Food

Range: 10'

Cleric 5

Duration: permanent

The food that this spell creates is simple fare of the caster's choice, highly nourishing, but rather bland. Up to 3 men or one horse per caster level can be fed for one day with this spell. Food so created decays and becomes inedible within 24 hours, although it can be kept fresh for another 24 hours by casting **purify food and water** on it.

:::

::: {.callout-note icon=false collapse=true}

## Dispel Evil

Range: touch

Cleric 5

Duration: 1 round/level

This powerful spell aids the caster in dealing with creatures from the nether planes, hereafter called "evil creatures."

First, the caster gains a +4 bonus to Armor Class against attacks by evil creatures.

Second, the caster can choose to drive an evil creature back to its home plane by touch (requiring a successful attack roll). The creature can negate the effects with a successful save vs. Spells. This use discharges and ends the spell, even if the saving throw succeeds.

Third, with a touch the caster can automatically dispel any one spell cast by an evil creature. Exception: Spells that can't be dispelled by **dispel magic** also can't be dispelled by dispel evil. Saving throws do not apply to this effect. This use also ends the spell.

The exact definition of evil is left for the GM to decide; however, extraplanar creatures that oppose the caster should almost always qualify.

:::

::: {.callout-note icon=false collapse=true}

## Insect Plague

Range: 300'+30'/level

Cleric 5

Duration: 1 round/level

This spell summons one swarm of locusts per three caster levels, to a maximum of six swarms at 18th level. See Insect Swarm in the **Monsters** section for the effects of a swarm. The swarms must be summoned so that each one is adjacent to at least one other swarm (that is, the swarms must fill one contiguous area). The caster may summon the locust swarms so that they share the area of other creatures. Each swarm attacks any creatures occupying its area. The swarms are stationary after being summoned.

:::

::: {.callout-note icon=false collapse=true}

## Quest*

Range: 5'/level

Cleric 5

Duration: special

Quest places a magical command on a creature to carry out some service or to refrain from some action or course of activity, as desired by the caster. The target creature must be able to understand the caster for this spell to take effect. While a quest cannot compel a creature to kill itself or perform acts that would result in certain death, it can cause almost any other course of activity.

A saving throw vs. Spells will allow an unwilling target to resist a quest when it is first cast. However, the target may choose to accept the quest, typically as part of a bargain with the caster to perform some service.

The affected creature must follow the given instructions until the quest is completed, no matter how long it takes.

If the instructions involve some open-ended task that the recipient cannot complete through his own actions the spell remains in effect for a maximum of one day per caster level. A clever recipient can subvert some instructions.

If the subject is prevented from obeying the quest for 24 hours, it takes 3d6 points of damage each day.

A quest (and all effects thereof) can be ended by a **remove curse** spell from a caster two or more levels higher than the caster of the quest, or by a wish, or by the reverse of this spell. **Dispel magic** does not affect a **quest** spell.

:::

::: {.callout-note icon=false collapse=true}

## Raise Dead*

Range: touch

Cleric 5

Duration: instantaneous

This spell restores life to a deceased human, demi-human or humanoid. The caster can raise a creature that has been dead for no longer than one day per caster level. In addition, the subject's soul must be free and willing to return. If the subject's soul is not willing to return, the spell does not work.

Coming back from the dead is an ordeal. The subject of the spell loses one level (or 1 hit die) when it is raised, permanently (i.e. it does not accrue a negative level, but rather loses an actual level, being reduced to the minimum number of experience points required for the previous level). If the subject is 1^st^ level, it loses 1 point of Constitution instead (if this would reduce its Constitution to 0 or less, it can't be raised). This level, hit dice, or Constitution loss cannot be repaired by any means, though of course the character may gain levels and hit dice in the normal fashion.

Also note, a character who died with spells prepared has none prepared upon being raised.

A raised creature has a number of hit points equal to its current hit dice. Normal poison and normal disease are cured in the process of raising the subject, but magical diseases and curses are not undone. While the spell closes mortal wounds and repairs lethal damage of most kinds, the body of the creature to be raised must be whole. Otherwise, missing parts are still missing when the creature is brought back to life. None of the dead creature's equipment or possessions are affected in any way by this spell.

A creature which has become undead can't be raised by this spell. Constructs and elementals cannot be raised. The spell cannot bring back a creature that has died of old age.

The reverse of this spell, **slay living**, will kill instantly the creature touched (which may be of any sort, not just a human, demi-human or humanoid) unless a save vs. Spells is made. If the saving throw is successful, 2d6 damage is dealt to the victim instead. An attack roll is required to apply this spell in combat.

:::

::: {.callout-note icon=false collapse=true}

## True Seeing

Range: touch

Cleric 5

Duration: 1 round/level

This spell confers on the target the ability to see all things as they actually are. The subject sees through normal and magical darkness, notices secret doors, sees the exact locations of displaced creatures or objects, sees through normal or magical disguises, sees invisible creatures or objects normally, sees through illusions, and sees the true form of polymorphed, changed, or transmuted things. The range of true seeing conferred is 120 feet.

True seeing, however, does not penetrate solid objects. It in no way confers X-ray vision or its equivalent. It does not negate concealment, including that caused by fog and the like. In addition, the spell effects cannot be further enhanced with known magic, so one cannot use true seeing through a **crystal ball** or in conjunction with **clairvoyance**.

:::

::: {.callout-note icon=false collapse=true}

## Wall of Fire

Range: 180'

Cleric 5, Magic-User 4

Duration: 1 round/level

(or special)

An immobile, blazing curtain of shimmering violet fire springs into existence. One side of the wall, selected by the caster, sends forth waves of heat, dealing 2d4 points of fire damage to creatures within 10 feet and 1d4 points of fire damage to those beyond 10 feet but within 20 feet. The wall deals this damage when it appears and on the caster's turn each round to all creatures in the area. In addition, the wall deals 2d6 points +1 point per caster level of fire damage to any creature passing through it. The wall deals double damage to undead creatures.

The wall is either a sheet of flame up to 20' in length per caster level, or a ring with a radius up to 5' per caster level. The caster may choose to make the wall smaller if desired. The wall may be up to 20' tall (as desired by the caster and/or constrained by the ceiling).

If the caster evokes the wall so that it appears where creatures are, each creature takes damage as if passing through the wall; a save vs. Spells is allowed, with success indicating that damage is rolled as if the creature is within 10' of the wall.

The caster may choose to maintain the spell indefinitely (within reasonable limits of endurance) by concentration, or may cast it with the standard duration of 1 round per level, at his or her option.

:::

:::

::: {.callout-tip icon=false collapse=true}

# Level 6, Clerical

::: {.callout-note icon=false collapse=true}

## Animate Objects

Range: 100'+10'/level

Cleric 6

Duration: 1 round/level

This spell imbues inanimate objects with mobility and a semblance of life. The animated objects then attack whomever or whatever the caster designates. This spell cannot animate objects carried or worn by a creature. An animated object can be of any non-magical material. The caster can animate one object per level, up to a maximum of 25 lbs. per caster level (i.e. 300 lbs. at 12th level, 325 lbs. at 13th level, and so on).

The GM must rule on the effectiveness of animated objects in combat. In general, animated objects attack using the same attack bonus as the caster. Small or lightweight objects do no more than 1d4 damage per hit, while larger and/or heavier objects do 1d6 or 1d8 (at the GM's discretion). As a special case, weapons which are animated do damage using the normal die roll for the type, but only up to a maximum 1d8. Animated objects have a movement rate of 10', and generally must move in contact with the ground (walking, hopping, slithering, or bouncing, however seems most appropriate to the GM).

:::

::: {.callout-note icon=false collapse=true}

## Blade Barrier

Range: 90'

Cleric 6

Duration: 1 round/level

This spell creates a wall of whirling blades up to 20' long per caster level, or a ringed wall of whirling blades with a radius of up to 5' per two levels. Either form will be up to 20 ft. high (as allowed by available space). Any creature passing through the wall takes 1d6 points of damage per caster level (maximum 15d6), with a save vs. Death Ray reducing damage to half.

If the caster evokes the barrier so that it appears where creatures are, each creature takes damage as if passing through the wall. Each such creature can avoid the wall (ending up on the side of its choice) and thus take no damage by making a successful save vs. Death Ray.

A blade barrier provides cover (+4 bonus to Armor Class) against attacks made through it.

:::

::: {.callout-note icon=false collapse=true}

## Find the Path

Range: touch

Cleric 6

Duration: 1 turn/level

The recipient of this spell can find the shortest, most direct physical route to a specified destination. The caster must have some knowledge about the location; any location the caster has ever visited can be so located, as well as locations described to the caster. Even knowing the name of a location (if it has a name) is enough for this spell to function.

The locale can be outdoors or underground. **Find the path** works with respect to locations, not objects or creatures. The location must be on the same plane as the caster at the time of casting.

The spell enables the subject to sense the correct direction that will eventually lead it to its destination, indicating at appropriate times the exact path to follow or physical actions to take. For example, the spell enables the subject to detect secret doors and to know any passwords required. The spell ends when the destination is reached or the duration expires, whichever comes first.

:::

::: {.callout-note icon=false collapse=true}

## Heal*

Range: touch

Cleric 6

Duration: permanent

Heal enables the caster to wipe away injury and afflictions. It immediately ends any and all of the following adverse conditions affecting the target: ability damage, blindness, confusion, deafness, disease, exhaustion or fatigue, **feeblemind**, insanity, nausea, and poison. It also restores all but 1d4 of the target's hit points. Heal does not remove negative levels or restore permanently drained ability score points.

The reversed spell, **harm**, injures the creature touched so horribly that it is left with only 1d4 hit points. The caster must succeed at a normal attack roll in this case; failure means the spell is wasted. Note that, if the victim has fewer hit points remaining than the number rolled, he or she will take at least one point of damage (and this is the only case in which **harm** may kill a creature).

Generally, both **heal** and** harm** only affect living creatures. If used against an undead creature, heal instead acts like harm; likewise, harm affects undead like heal. Constructs such as golems are unaffected by either spell.

:::

::: {.callout-note icon=false collapse=true}

## Regenerate

Range: touch

Cleric 6

Duration: permanent

This spell causes the subject’s severed body members (fingers, toes, hands, feet, arms, legs, tails, or even heads of multiheaded creatures), broken bones, and ruined organs to grow back. After the spell is cast, the physical regeneration is complete in 1 round if the severed members are present and touching the creature. Otherwise, a full turn is required for the regeneration to complete.

This spell also heals 3d8 points of damage. Regenerate has no effect on nonliving creatures or constructs (including undead).

:::

::: {.callout-note icon=false collapse=true}

## Restoration

Range: touch

Cleric 6

Duration: permanent

Each casting of the spell removes a single negative level from a creature who has suffered energy drain. At 16th level, two negative levels may be removed. See the rules for Energy Drain (in the **Encounter** section) for more details.

Alternately, this spell can be used to restore drained ability score points. If applied to a character who has suffered temporary loss of ability points, it will restore up to 1d4 lost points to any one drained ability immediately. If applied to a character who has suffered permanent loss of ability points, 1 point can be restored.

Restoration does not restore levels lost due to death (as described for the spell **raise dead**).

:::

::: {.callout-note icon=false collapse=true}

## Speak with Monsters

Cleric 6

Range: special

Duration: 1 turn/5 levels

The caster can comprehend and communicate with any one monster that is in sight of the caster and able to hear him or her. The caster may change which monster he or she is speaking with at will, once per round. Others able to understand the language spoken by the target monster (if any) will be able to understand the caster. The spell doesn’t alter the monster’s reaction or attitude towards the caster. Furthermore, more intelligent monsters are likely to be terse and evasive, while less intelligent ones make inane comments. If a monster is friendly toward the caster, it may decide to do some favor or service for him or her. Mindless monsters, plant creatures and undead are unaffected by this spell.

:::

::: {.callout-note icon=false collapse=true}

## Word of Recall

Range: self (special)

Cleric 6

Duration: instantaneous

Word of recall teleports the caster instantly back to his or her sanctuary when a single word is uttered. The caster must designate the sanctuary when he or she prepares the spell, and it must be a very familiar place. The actual point of arrival is a designated area no larger than 10 feet by 10 feet. The caster can be transported any distance within a plane but cannot travel between planes. The caster can bring along objects or creatures, not to exceed 300 pounds plus 100 pounds per level above 10th. The caster must be in contact with all objects and/or creatures to be transported (although creatures to be transported may be in contact with one another, with at least one of those creatures in contact with the caster).

An unwilling creature can’t be teleported by word of recall. Likewise, a creature’s save vs. Spells prevents items in its possession from being teleported.

:::

:::



# Magic User Spells

Magic-Users cast spells through the exercise of knowledge and will. They prepare spells by study of their spellbooks; each Magic-User has his or her own spellbook containing the magical formulae for each spell the Magic-User has learned. Spellbooks are written in a magical script that can only be read by the one who wrote it, or through the use of the spell **read magic**. All Magic-Users begin play knowing **read magic**, and it is so ingrained that it can be prepared without a spellbook.

A Magic-User may only prepare spells after resting (i.e. a good night's sleep), and needs one turn per each three spell levels to do so (rounding fractions up). Spells prepared but not used on a previous day are not lost. For example, a 3^rd^ level Magic-User preparing all three of his or her available spells (two 1^st^ level and one 2^nd^ level) is preparing a total of 4 levels of spells, and thus needs 2 turns (4 divided by 3 and rounded up).

Rules for the acquisition of new spells are found in the Game Master's section.

::: {.callout-tip icon=false collapse=true}

# Level 1, Magic User

::: {.callout-note icon=false collapse=true}

## Charm Person

Range: 30'

Magic User 1

Duration: special

This spell makes a humanoid creature of 4 hit dice or less regard the caster as its trusted friend and ally. Humans and demi-humans may be affected, regardless of level of ability. A save vs. Spells will negate the effect. If the creature is currently being threatened or attacked by the caster or his or her allies, it receives a +5 bonus on its saving throw. The spell does not enable the caster to control the charmed person as if it were an automaton; rather, it perceives his or her words and actions in the most favorable way. The caster can try to give the subject orders, but it will not do anything it wouldn’t ordinarily do, and further may receive an additional saving throw to overcome the magic (at the GM's discretion). The caster must speak the target's language to communicate any commands, or else be good at pantomiming; of course, if the caster is attacked, the charmed creature will act to protect its “friend” (though that could mean attacking the caster's enemies, or attempting to carry off the caster to a “safe” place). The target receives a new saving throw each day if it has an Intelligence of 13 or greater, every week if its Intelligence is 9-12, or every month if its Intelligence is 8 or less.

:::

::: {.callout-note icon=false collapse=true}

## Detect Magic

Range: 60'

Cleric 1, Magic-User 1

Duration: 2 turns

The caster of this spell is able to detect enchanted or enspelled objects or creatures within the given range by sight, seeing them surrounded by a pale glowing light. Only the caster sees the glow. Invisible creatures or objects are not detected by this spell, but the emanations of the invisibility magic will be seen as an amorphous glowing fog, possibly allowing the caster (only) to attack the invisible creature at an attack penalty of only -2.

:::

::: {.callout-note icon=false collapse=true}

## Floating Disk

Range: 0

Magic User 1

Duration: 5 turns +1/level

This spell creates an invisible, slightly concave circular plane of force for carrying loads. It is about the size of a shield, being 3 feet in diameter and 1 inch deep at its center. It can hold a maximum of 500 pounds of weight. (Note that water weighs about 8 pounds per gallon.) The disc must be loaded so that the items placed upon it are properly supported, or they will (of course) fall off. For example, the disc can support just over 62 gallons of water, but the water must be in a barrel or other reasonable container that can be placed upon the disc. Similarly, a pile of loose coins will tend to slip and slide about, and some will fall off with every step the caster takes; but a large sack full of coins, properly tied, will remain stable.

The disc floats level to the ground, at about the height of the caster's waist. It remains still when within 10' of the caster, and follows at the caster's movement rate if he or she moves away from it. The floating disc can be pushed as needed to position it but will be dispelled if somehow moved more than 10' from the caster. When the spell duration expires, the disc disappears from existence and drops whatever was supported to the surface beneath.

:::

::: {.callout-note icon=false collapse=true}

## Hold Portal

Range: 100'+10'/level

Magic User 1

Duration: 1 round/level

This spell magically holds shut a door, gate, window, or shutter of wood, metal, or stone. The magic affects the portal just as if it were securely closed and normally locked. A **knock** spell or a successful **dispel magic** spell can negate a hold portal spell.

:::

::: {.callout-note icon=false collapse=true}

## Light*

Range: 120'

Cleric 1, Magic-User 1

Duration: 6 turns + 1/level

This spell creates a light equal to torchlight which illuminates a 30' radius area (and provides dim light for an additional 20') around the target location or object. The effect is immobile if cast into an area, but it can be cast on a movable object. Light taken into an area of magical darkness does not function.

Reversed, **light** becomes **darkness**, creating an area of darkness just as described above. This darkness blocks out Darkvision and negates mundane light sources.

A light spell may be cast to counter and dispel the darkness spell of an equal or lower level caster (and vice versa). Doing so causes both spells to instantly cease, restoring the existing ambient light level.

Either version of this spell may be used to blind an opponent by means of casting it on the target's ocular organs. The target is allowed a saving throw vs. Death Ray to avoid the effect, and if the save is made, the spell does not take effect at all. A **light** or **darkness** spell cast to blind does not have the given area of effect (that is, no light or darkness is shed around the victim). 

:::

::: {.callout-note icon=false collapse=true}

## Magic Missile

Range: 100'+10'/level

Magic User 1

Duration: instantaneous

This spell causes a missile of magical energy to dart forth from the caster's fingertip and strike its target, which must be at least partially visible to the caster, dealing 1d6+1 points of damage. The missile strikes unerringly. Specific parts of a creature can’t be singled out. Inanimate objects are not damaged by the spell.

For every three caster levels beyond 1st, an additional missile is fired – two at 4th level, three at 7th, four at 10th, and the maximum of five missiles at 13th level or higher. If the caster fires multiple missiles, he or she can target a single creature or several creatures. A single missile can strike only one creature. Targets must be designated before damage is rolled.

:::

::: {.callout-note icon=false collapse=true}

## Magic Mouth

Range: 30'

Magic User 1

Duration: special

This spell imbues the chosen non-living object with an enchanted mouth that suddenly appears and speaks its message the next time a specified event occurs. The message, which may be up to three words per caster level long, can be in any language known by the caster and can be delivered over a period of 10 minutes, at any volume from a whisper to a yell. The voice will resemble the caster's, but will not be identical. The mouth cannot use command words or activate magical effects. It does, however, move according to the words articulated; if it were placed upon a statue, the mouth of the statue would move and appear to speak. Of course, magic mouth can be placed upon a tree, rock, or any other object.

The spell functions when specific conditions are fulfilled according to the caster's command as set in the spell. Commands can be as general or as detailed as desired, although only visual and audible triggers can be used. Triggers react to what appears to be the case. Disguises and illusions can fool them. Normal darkness does not defeat a visual trigger, but magical darkness or invisibility does. Silent movement or magical silence defeats audible triggers. Audible triggers can be keyed to general types of noises or to a specific noise or spoken word. Actions can serve as triggers if they are visible or audible. A magic mouth cannot distinguish level, hit dice, or class except by external garb.

The range limit of a trigger is 10 feet per caster level, so a 6th-level caster can command a magic mouth to respond to triggers as far as 60 feet away. Regardless of range, the mouth can respond only to visible or audible triggers and actions in line of sight or within hearing distance.

:::

::: {.callout-note icon=false collapse=true}

## Protection from Evil*

Cleric 1, Magic-User 1

Range: touch

Duration: 1 turn/level

This spell wards a creature from attacks by evil creatures, from mental control, and from summoned creatures. It creates a magical barrier around the subject at a distance of 1 foot. The barrier moves with the subject and has three major effects.

First, the subject gains a +2 bonus to AC and a +2 bonus on saves. Both these bonuses apply against attacks made or effects created by evil creatures. Note that the definition of "evil" is left to the individual GM to decide.

Second, the barrier blocks any attempt to possess the warded creature (by a magic jar attack, for example) or to exercise mental control over the creature (including charm spells or effects). The protection does not prevent such effects from targeting the protected creature, but it suppresses the effect for the duration of the protection from evil effect. If the protection from evil effect ends before the effect granting control does, the would-be controller would then be able to command the controlled creature. Likewise, the barrier keeps out a possessing life force but does not expel one if it is in place before the spell is cast.

Third, the spell prevents bodily contact by summoned creatures (regardless of whether they are "evil" or not). This causes the natural weapon attacks of such creatures to fail and the creatures to recoil if such attacks require touching the warded creature. The protection against contact by summoned creatures ends if the warded creature makes an attack against or tries to force the barrier against the blocked creature.

Reversed, this spell becomes **protection from good**. It functions in all ways as described above, save that "good" creatures are kept away, rather than "evil" creatures.

:::

::: {.callout-note icon=false collapse=true}

## Read Languages

Range: 0

Magic User 1

Duration: special

This spell grants the caster the ability to read almost any written language. It may be cast in one of three modes:

In the first mode, the spell allows the caster to read any number of written works in a variety of languages. This mode lasts for 1 turn per caster level.

In the second mode, the spell allows the caster to read any one book or tome; this mode lasts 3 hours per caster level.

In the third mode, the spell allows the caster to read any one non-magical scroll or other single-sheet document; this mode is permanent.

This spell does not work on any sort of magical text, such as spell scrolls or spellbooks; see **read magic**, below, for the correct spell to use in such cases.

The spell grants the ability to read the texts, but does not in any way hasten the reading nor grant understanding of concepts the caster doesn't otherwise have the ability to understand. Also, for this spell to function, there must be at least one living creature that can read the given language somewhere on the same plane. The knowledge is not copied from that creature's mind; rather, it is the existence of the knowledge that enables the spell to function.

:::

::: {.callout-note icon=false collapse=true}
 
## Read Magic
 
Range: 0

Magic User 1

Duration: permanent

When cast upon any magical text, such as a spellbook or magic-user spell scroll, this spell enables the caster to read that text. Casting this spell on a cursed text will generally trigger the curse. All Magic-Users begin play knowing this spell, and it can be prepared even if the Magic-User loses access to his or her spellbook.

:::

::: {.callout-note icon=false collapse=true}

## Shield

Range: self

Magic User 1

Duration: 5 rounds+1/level

Shield creates an invisible, shield-like mobile disk of force that hovers in front of the caster. It negates **magic missile** attacks directed at the caster, and improves the caster's Armor Class by +3 vs. melee attacks and +6 vs. missile weapons. The Armor Class benefits do not apply to attacks originating from behind the caster, but **magic missiles** are warded off from all directions.

:::

::: {.callout-note icon=false collapse=true}
 
## Sleep
 
Range: 90'

Magic User 1

Duration: 5 rounds/level

This spell puts several creatures of 3 or fewer hit dice into a magical slumber. Creatures of 4 or more hit dice are not affected. The caster chooses a point of origin for the spell (within the given range, of course), and those creatures within 30' of the chosen point may be affected. Each creature in the area of effect is allowed a save vs. Spells to resist the effect.

Sleeping creatures are helpless. Slapping or wounding awakens an affected creature, but normal noise does not. Sleep does not affect unconscious creatures, constructs, or undead creatures, and such creatures in the area of effect are ignored.

When the duration elapses, the sleeping creatures normally wake up immediately; however, if they are made very comfortable and the surroundings are quiet, the affected creatures may continue sleeping normally, at the GM's option.

:::

::: {.callout-note icon=false collapse=true}
 
## Ventriloquism
 
Range: 60'

Magic User 1

Duration: 1 turn/level

This spell allows the caster to cause his or her voice to sound from someplace else within range, for example, from a dark alcove or statue.

:::

:::

<!-- -------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# Level 2, Magic User

::: {.callout-note icon=false collapse=true}
 
## Continual Light*
 
Range: 360'

Cleric 3, Magic-User 2

Duration: 1 year/level

This spell creates a spherical region of light, as bright as full daylight up to a 30' radius, with light of lesser intensity to a radius of 60'. Continual light can be cast on an object, into the air, or at a creature, just as with the **light** spell, up to a maximum range of 360' from the caster. The spell remains in effect for one year per level of the caster.

As with **light**, this spell can be used to blind a creature if cast on its visual organs. Creatures targeted by this spell are allowed a save vs. Death Ray; if the save is made, the spell is cast into the air just behind the target creature. A penalty of -4 is applied to the blinded creature's attack rolls if the saving throw fails.

The reversed spell, **continual darkness**, causes complete absence of light in the area of effect, overpowering normal light sources. Continual darkness may be used to blind in the same way as continual light.

:::

::: {.callout-note icon=false collapse=true}
 
## Detect Evil*
 
Range: 60'

Cleric 1, Magic-User 2

Duration: 1 round/level

This spell allows the caster to detect evil; specifically, the caster can detect creatures with evil intentions, magic items with evil enchantments, and possibly extraplanar creatures of evil nature. Normal characters, even “bad” characters, cannot be detected by this spell, as only overwhelming evil is detectable. The caster sees the “evil” creatures or objects with a definite glow around them, but the glow cannot be seen by anyone else.

The exact definition of evil is left for the GM to decide. Note that items such as ordinary traps or poisons are not “evil,” and thus not detectable by this spell.

Reversed, this spell becomes **detect good**, which works just as described above with respect to detecting “good” enchantments, angelic creatures, and so on.

:::

::: {.callout-note icon=false collapse=true}
 
## Detect Invisible
 
Range: 60'

Magic User 2

Duration: 1 turn/level

By means of this spell the caster is able to see invisible characters, creatures or objects within the given range, seeing them as translucent shapes.

:::

::: {.callout-note icon=false collapse=true}
 
## Invisibility
 
Range: touch

Magic User 2

Duration: special

The creature or object touched becomes invisible, vanishing from sight, including Darkvision. If the recipient is a creature carrying gear, that vanishes, too. If the spell is cast on someone else, neither the caster nor his or her allies can see the subject, unless they can normally see invisible things or employ magic to do so.

Items dropped or put down by an invisible creature become visible; items picked up disappear if tucked into the clothing or pouches worn by the creature. Light, however, never becomes invisible, although a source of light can become so (thus, the effect is that of a light with no visible source). Any part of an item that the subject carries but that extends more than 10 feet from it becomes visible. Of course, the subject is not magically silenced, and certain other conditions can render the recipient detectable (such as stepping in a puddle).

The spell ends if the subject attacks any creature or casts any spell. Actions (other than spellcasting) directed at unattended objects do not break the spell. Causing harm indirectly is not an attack. The spell lasts at most 24 hours.

:::

::: {.callout-note icon=false collapse=true}
 
## Knock
 
Range: 30'

Magic User 2

Duration: special

The knock spell opens stuck, barred, locked, **held**, or **wizard locked** doors. It opens secret doors, as well as locked or trick-opening boxes or chests. It also loosens welds, shackles, or chains (provided they serve to hold shut something which can be opened). If used to open a **wizard locked** door, the spell does not remove the **wizard lock** but simply suspends its functioning for one turn. In all other cases, the door does not relock itself or become stuck again on its own. Knock will not raise a portcullis or operate any other similar mechanism, nor will it affect ropes, vines, and the like. Each spell can undo a single means of preventing access.

:::

::: {.callout-note icon=false collapse=true}
 
## Levitate
 
Range: touch

Magic User 2

Duration: 1 turn/level

Levitate allows the caster to move himself or herself, another creature, or an object up and down as desired. A creature must be willing to be levitated, and an object must be unattended or possessed by a willing creature. The caster can mentally direct the recipient to move up or down as much as 20 feet each round, by concentration. The caster cannot move the recipient horizontally, but the recipient could clamber along the face of a cliff, for example, or push against a ceiling to move laterally (generally at half its normal land speed).

A levitating creature that attacks with a weapon finds itself increasingly unstable; the first attack has a –1 attack penalty, the second –2, and so on, to a maximum penalty of –5. A full round spent stabilizing allows the creature to begin again at –1.

:::

::: {.callout-note icon=false collapse=true}
 
## Locate Object
 
Range: 360'

Cleric 3, Magic-User 2

Duration: 1 round/level

This spell allows the caster to sense the direction of a well-known or clearly visualized object. He or she can search for general items, in which case the nearest one of its kind is located if more than one is within range. The caster cannot specify a unique item unless he or she has observed that particular item firsthand (not merely through divination such as **clairvoyance** or a **crystal ball**). The spell is blocked by even a thin sheet of lead or gold. Creatures cannot be found by this spell.

:::

::: {.callout-note icon=false collapse=true}
 
## Mind Reading
 
Range: 60'

Magic User 2

Duration: 1 turn/level

This spell, sometimes incorrectly called ESP, permits the caster to hear (and possibly see, if the target
visualizes anything) the surface thoughts of one or more living creatures within range. The caster must designate a direction or select a visible target, and then concentrate for a turn in order to "hear" the thoughts. Each turn the caster may choose to "listen" in a different direction. The caster may stop listening, then resume again later, so long as the duration has not expired. The target creature is not normally aware of being spied upon in this way, though any creature already under the effect of this spell or any similar form of telepathy will instantly know and be able to sense the direction of the caster.

Rock more than 2 inches thick or a thin coating of lead or gold will block the spell. All undead creatures are immune to this effect, as are mindless creatures such as golems.

:::


::: {.callout-note icon=false collapse=true}
 
## Mirror Image
 
Range: self

Magic User 2

Duration: 1 turn/level

This spell creates several illusory duplicates of the caster. The images move through each other as well as the real caster more or less constantly, making it impossible for most creatures to determine which is real. A total of 1d4 images plus one image per three caster levels (maximum eight images total) are created. These figments separate from the caster and remain in a cluster around him or her. The figments mimic the caster's actions, pretending to cast spells, drink potions, levitate, and so on, just as the caster does. Figments always look exactly like the caster.

Enemies attempting to attack or cast spells upon the caster will always hit a figment instead. Any attack against an image destroys it, whether the attack roll is successful or not; likewise, attack spells cast directly upon a figment will destroy it, with no saving throw allowed. Area-effect spells are not cast directly on the caster, and thus appear to affect all figments exactly as they affect the caster; for instance, if the caster is subjected to a **fireball**, all figments will appear to be injured just as the caster was.

:::

::: {.callout-note icon=false collapse=true}
 
## Phantasmal Force
 
Range: 180'

Magic User 2

Duration: concentration

This spell creates the visual illusion of an object, creature (or small group of creatures), or other effect, as visualized by the caster up to a maximum size of 20'x20'x20'. The illusion does not create sound, smell, texture, or temperature. The caster can animate the image within the limits of the area of effect. The image persists so long as the caster concentrates upon it.

If used to create the illusion of one or more creatures, they will have an Armor Class of 11 and will disappear if hit in combat. Damage done by monsters, spells, etc. simulated by this spell is not real; those “killed” or otherwise apparently disabled will wake up uninjured (at least from this spell) after 2d8 rounds. The illusory damage done will be equivalent to the normal damage for any attack form simulated.

Attempting to animate more creatures than the caster's level grants viewing creatures with at least average Intelligence an immediate save vs. Spells to recognize the creatures as illusions; those making the save will be unaffected by any actions taken by the illusions from that point on. A similar save may be granted by the GM any time he or she feels the illusion is likely to be seen through, especially if the player describes an illusion which seems improbable or otherwise poorly conceived.

:::

::: {.callout-note icon=false collapse=true}
 
## Web
 
Range: 10' per level

Magic User 2

Duration: 2 turns/level

Web creates a many-layered mass of strong, sticky strands, filling a volume of 8,000 cubic feet (equivalent to eight 10'x10'x10' cubes). The strands are similar to spider webs but far larger and tougher. These masses must be anchored to two or more solid and diametrically opposed points or else the web collapses upon itself and disappears; within this limitation, the caster may choose any arrangement of webs he or she wishes, up to the limit of range and the given 8,000 cubic foot volume. The caster may choose to create a smaller volume if he or she wishes. Creatures caught within a web become entangled among the gluey fibers. Attacking a creature in a web won’t cause the attacker to become entangled, but moving through the affected area will.

Anyone in the area of effect when the spell is cast must make a save vs. Death Ray. If this save succeeds, the creature is entangled, but not prevented from moving, though moving is reduced to one-half normal movement rate. Such entangled creatures may not cast spells or perform normal attacks; whether other actions are possible is left to the GM to decide. Once an entangled creature leaves the area of effect of the web, it will be able to act normally again.

If the save fails, the creature is entangled and can’t move or perform any other physical action. Speech remains possible, however. Creatures with Strength of 13 or higher (or 4 or more hit dice) may be able to break loose, however; each round, such creatures are allowed another save vs. Death Ray with results as given above. Creatures failing the initial save and having Strength of 12 or less (or fewer than 4 hit dice) are trapped until the duration expires or the webs are otherwise removed.

The strands of a web spell are flammable. Any fire can set the webs alight and burn away a 10' cube in 1 round; the fire will spread to adjacent 10' cubes each round until all the webbing is consumed (or the fire is put out by some means). All creatures within flaming webs take 2d4 points of fire damage from the flames, but if they survive they are completely free afterwards.

:::

::: {.callout-note icon=false collapse=true}
 
## Wizard Lock
 
Range: 20'

Magic User 2

Duration: permanent

A **wizard lock** spell cast upon a door, chest, or portal magically locks it. The caster can freely pass his or her own wizard lock without affecting it, as can any Magic-User 3 or more levels higher than the caster of the wizard lock; otherwise, a door or object secured with this spell can be opened only by breaking in or with a successful **dispel magic** or **knock** spell.

:::

:::

<!-- ------------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# Level 3, Magic User

::: {.callout-note icon=false collapse=true}
 
## Clairvoyance
 
Range: 60'

Magic User 3

Duration: 12 turns

This spell enables the caster to see into another area through the eyes of a living creature in that area. The caster must specify the direction and approximate distance, up to a maximum of 60' away. If there is no appropriate creature in that area, the spell fails. No saving throw is allowed, and the target creature is unaware that it is being so used. The caster may choose another subject creature after at least a turn has passed, enabling multiple locations to be viewed. If the subject creature moves out of range, contact is lost, though the caster may be able to choose another target in this case.

:::

::: {.callout-note icon=false collapse=true}
 
## Darkvision
 
Range: touch

Magic User 3

Duration: 1 hour/level

The subject receives Darkvision with a range of 60' for the duration of the spell. (See page 37 for details.)

:::

::: {.callout-note icon=false collapse=true}
 
## Dispel Magic
 
Range: 120'

Cleric 4, Magic-User 3

Duration: instantaneous

The caster can use dispel magic to end ongoing spells that have been cast on a creature or object, or to end ongoing spells (or at least their effects) within a cubic area 20' on a side. The caster must choose whether to dispel magic on a creature or object, or to affect an area.

If dispel magic is targeted at a creature, all spell effects (including ongoing potion effects) may be canceled. If cast upon an area, all such effects within the area may be canceled. Any spell or effect having a caster level equal to or less than the **dispel magic** caster's level is ended automatically. Those created by higher level casters might not be canceled; there is a 5% chance the dispel magic will fail for each level the spell effect exceeds the caster level. For example, a 10^th^ level caster dispelling magic created by a 14^th^ level caster has a 20% chance of failure.

Some spells cannot be ended by dispel magic; this specifically includes any curse, including those created by **bestow curse** (the reverse of **remove curse**) as well as by cursed items.

:::

::: {.callout-note icon=false collapse=true}
 
## Fireball
 
Range: 100'+10'/level

Magic User 3

Duration: instantaneous

A fireball spell creates an explosion of flame that detonates with a low roar and deals 1d6 points of fire damage per caster level to every creature within a spherical volume having a 20' radius. A save vs. Spells for half damage is allowed. The explosion creates almost no pressure.

The caster points a finger and determines the range (distance and height) at which the fireball is to burst. A glowing, pea-sized bead streaks from the pointing digit and, unless it impacts upon a material body or solid barrier prior to attaining the prescribed range, blossoms into the fireball at that point. (An early impact results in an early detonation.) If the caster attempts to send the bead through a narrow passage, such as through an arrow slit, he or she must roll a missile attack (without range adjustments) to hit the opening, or else the bead strikes the barrier and detonates prematurely.

The fireball sets fire to combustibles and damages objects in the area. It can melt metals with low melting points, such as lead, gold, copper, silver, and bronze. If the damage caused to an interposing barrier shatters or breaks through it, the fireball may continue beyond the barrier in order to attain its full volume.

:::

::: {.callout-note icon=false collapse=true}
 
## Fly
 
Range: touch

Magic User 3

Duration: 1 turn/level

The subject of this spell can fly at a speed equal to his or her normal ground movement rate (as adjusted by encumbrance). The subject can ascend at half speed and descend at double speed, with the same maneuverability as the subject has when moving on the ground. Flying under the effect of this spell requires only as much concentration as walking, so the subject can attack or cast spells normally. The subject of a fly spell can neither charge nor run, nor carry aloft more weight than his or her maximum load.

Should the spell duration expire while the subject is still aloft, the magic fails slowly. The subject floats downward 120' per round for 1d10 rounds. If the subject reaches the ground in that amount of time, he or she lands safely. If not, the subject falls the rest of the distance, taking normal falling damage. Since dispelling a spell effectively ends it, the subject also descends in this way if the fly spell is dispelled.

:::

::: {.callout-note icon=false collapse=true}
 
## Haste*
 
Range: 30'+10'/level

Magic User 3

Duration: 1 round/level

This spell accelerates the actions of 1 creature per caster level. The affected creatures move and act twice as quickly as normal, having double their normal movement rates and making twice the normal attacks per round, for the duration of the spell. Spellcasting is not accelerated, nor is the use of magic items such as wands, which may still be used just once per round. Multiple haste or speed effects don’t combine; only apply the most powerful or longest lasting effect.

Reversed, haste becomes **slow**; affected creatures move at half speed, attacking half as often (generally, every other round) and making half a normal move each round. Naturally, target creatures may save vs. Spells to avoid the effect. Haste and slow counter and dispel each other.

:::

::: {.callout-note icon=false collapse=true}
 
## Hold Person
 
Range: 180'

Cleric 2, Magic-User 3

Duration: 2d8 turns

This spell will render any living (not undead) human, demi-human or humanoid creature paralyzed. Creatures larger than ogres will not be affected by this spell. Targets of the spell are aware, and breathe normally, but cannot take any actions, including speech. A successful save vs. Spells will negate the effect. The spell may be cast at a single person, who makes his or her save at -2, or at a group, in which case 1d4 of the creatures in the group may be affected.

A winged creature which is paralyzed cannot flap its wings and falls (if in flight at the time). A paralyzed swimmer can’t swim and may drown.

:::

::: {.callout-note icon=false collapse=true}
 
## Invisibility 10' radius
 
Magic User 3

Range: touch

Duration: 1 turn/level

This spell functions like invisibility, except that this spell confers invisibility upon all creatures within 10 feet of the recipient. The center of the effect is mobile with the recipient.

Those affected by this spell can see each other and themselves as if unaffected by the spell. Affected creatures (other than the recipient) who attack negate the invisibility only for themselves, but if the spell recipient attacks, the invisibility ends for all affected creatures. Any affected creature moving out of the area becomes visible, but creatures moving into the area after the spell is cast do not become invisible (including any previously affected creatures who have become visible as described above).

:::

::: {.callout-note icon=false collapse=true}
 
## Lightning Bolt
 
Range: 50'+10'/level

Magic User 3

Duration: instantaneous

This spell releases a powerful stroke of electrical energy that deals 1d6 points of electricity damage per caster level to each creature within its area. A save vs. Spells for half damage is allowed. The bolt begins at the caster's fingertips and extends to the range given. The caster may choose to limit the range of the spell, but the minimum range is 60 feet. The lightning bolt passes through an area 5' wide, arcing and jumping, so that, while it is not actually 5' wide, for game purposes treat it as if it is so.

The lightning bolt sets fire to combustibles and damages objects in its path. It can melt metals with a low melting point, such as lead, gold, copper, silver, or bronze. If the damage caused to an interposing barrier shatters or breaks through it, the bolt may continue beyond the barrier if the spell’s range permits; otherwise, it may reflect from the barrier back toward the caster, or in a random direction at the GM's option. Creatures already affected by the lightning bolt do not take additional damage if struck by the reflection of the same bolt.

:::

::: {.callout-note icon=false collapse=true}
 
## Protection from Evil 10' Radius*
 
Cleric 4, Magic-User 3

Range: touch

Duration: 1 turn/level

This spell functions exactly as **protection from evil**, but with a 10' radius rather than a 1' radius. All within the radius receive the protection; those who leave and then re-enter, or who enter after the spell is cast, receive the protection as well.

Reversed, this spell becomes **protection from good 10' radius**, and functions exactly as the reversed form of **protection from evil**, except that it covers a 10' radius around the target rather than the normal 1' radius.

:::

::: {.callout-note icon=false collapse=true}
 
## Protection from Normal Missiles
 
Magic User 3

Range: self

Duration: 1 turn/level

The caster is completely protected from small sized, non-magical missile attacks. Therefore, magic arrows, hurled boulders, or other such are not blocked, but any number of normal arrows, sling bullets, crossbow bolts, thrown daggers, etc. will be fended off. Note that normal missiles projected by magic bows count as magical missiles for the purposes of this spell.

:::

::: {.callout-note icon=false collapse=true}
 
## Water Breathing
 
Range: touch

Magic User 3

Duration: 2 hours/level

The affected creatures can breathe water freely. Divide the duration evenly among all the creatures the caster touches. The spell does not make creatures unable to breathe air.

:::

:::

<!-- ----------------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# Level 4, Magic User

::: {.callout-note icon=false collapse=true}
 
## Charm Monster
 
Range: 30'

Magic User 4

Duration: special

This spell functions like **charm person**, except that the effect is not restricted by creature type or size. Undead monsters are unaffected. This spell can affect 3d6 hit dice of creatures of 3 or fewer hit dice, or one creature of more than 3 hit dice. Saving throws are made just as for **charm person**.

:::

::: {.callout-note icon=false collapse=true}
 
## Confusion
 
Range: 360'

Magic User 4

Duration: 2 rounds+1/level

This spell causes up to 3d6 living creatures within a 30' radius circle around the target point to become confused*,*making them unable to independently determine what they will do. A saving throw vs. Spells is allowed to resist the effect. Roll on the following table on each subject's Initiative number each round to see what the subject does.

| d20 | Behavior |
|-----|------------|
| 1--2 | Attack caster with melee or ranged weapons (or close with caster if attack is not possible). |
| 3--4 | Act normally. |
| 5--10 | Do nothing but babble incoherently. |
| 11--14 | Flee away from caster at top possible speed. |
| 15--20 | Attack nearest creature. |

A confused character who can't carry out the indicated action does nothing but babble incoherently. Attackers are not at any special advantage when attacking a confused character. Any confused character who is attacked automatically retaliates on its next turn, as long as it is still confused when its turn comes.

:::

::: {.callout-note icon=false collapse=true}
 
## Dimension Door
 
Range: 10'

Magic User 4

Duration: instantaneous

The caster of this spell instantly transfers himself or herself, or any single target creature within range, to any spot within 200' plus 20' per caster level. The caster or target creature always arrives at exactly the spot desired, whether the caster visualizes the area or states direction and distance. An unwilling target may save vs. Spells to avoid being transported. Anything worn or carried by the caster or target creature will be transported also, including another character or creature if the transportee can lift it. If the target area is within a solid object, the spell fails automatically.

:::

::: {.callout-note icon=false collapse=true}
 
## Growth of Plants*
 
Range: 120'

Magic User 4

Duration: permanent

This spell causes normal vegetation (grasses, briars, bushes, creepers, thistles, trees, vines, etc.) within range to become thick and overgrown. The dimensions of the growth are determined by the caster, but cannot exceed 1000 sq. feet (a 10'x100' area or equivalent) per 5 caster levels. The plants entwine to form a thicket or jungle that creatures must hack or force a way through. All movement within the affected area is reduced to no more than 5' per round for less than giant sized creatures; giant sized creatures are reduced to half normal movement rate. The area must have brush and/or trees in it for this spell to take effect.

The reverse form, **shrink plants**, may be used to render overgrown areas passable. The area of effect is identical to the normal version.

Growth of plants and its reverse are permanent until countered, either by the opposite form or by **dispel magic**. This spell has no effect on animated plant creatures of any sort.

:::

::: {.callout-note icon=false collapse=true}
 
## Hallucinatory Terrain
 
Magic User 4

Range: 400'+40'/level

Duration: 12 turns/level

This spell makes one 10 yard cube per level of outdoor terrain appear like a different type (i.e. field into forest, grassland into desert, or the like). This spell requires a full turn to cast.

The affected terrain looks, sounds, and smells like another sort of natural terrain. Structures, equipment, and creatures within the area are not hidden or changed in appearance. A save vs. Spells is allowed to see through the illusion, but only if the creatures or characters affected actively attempt to do so.

:::

::: {.callout-note icon=false collapse=true}
 
## Ice Storm
 
Range: 300'+30'/level

Magic User 4

Duration: 1 round

This spell causes great magical hailstones to pound down for 1 full round, dealing 5d6 points of damage to every creature in a 20' radius around the target spot; a successful save vs. Spells will reduce damage by half. The ice storm fills a vertical volume of 40', so creatures higher than that distance above the target spot are unaffected. A –20% penalty applies to each Listen roll made within the ice storm’s effect, and all land movement within its area is at half speed. At the end of the duration, the hail disappears, leaving no aftereffects (other than the damage dealt). Any creature naturally resistant to cold takes half damage (or one-quarter damage if it makes its save).

:::

::: {.callout-note icon=false collapse=true}
 
## Massmorph
 
Range: 100'+10'/level

Magic User 4

Duration: 1 hour/level

With this spell the caster causes 1d4+1 man-sized (or smaller) creatures per four caster levels to appear as if they are natural effects of the terrain (for example, trees in a forest, stalagmites in a cave, coral underwater, boulders in a cavern, etc.). All creatures to be affected must be within a 120' radius of the caster at the time the spell is cast. Only those creatures the caster wishes to hide are affected, and then only if they are willing to be concealed. The caster may include himself or herself among the affected creatures.

Those affected are thus concealed from other creatures passing through the area for so long as they remain still. If an affected creature chooses to move or attack, the illusion is dispelled for that creature, but those who remain still continue to be hidden. The caster may end the spell early if he or she wishes by speaking a single word. The illusion can also be ended by **dispel magic**.

:::

::: {.callout-note icon=false collapse=true}
 
## Polymorph Other
 
Range: 30'

Magic User 4

Duration: permanent

This spell allows the caster to change one target into another form of living creature. The assumed form can’t have more hit dice than caster’s level, or be incorporeal or gaseous. Unlike **polymorph self**, the transformed target also gains the behavioral and mental traits, any physical attacks, special, supernatural or spell-like abilities of the new form, in addition to the physical capabilities and statistics of such. If the new form is substantially less intelligent, the target may not remember its former life.

The target creature will have the same number of hit points it previously had, regardless of the hit dice of the form assumed. Incorporeal or gaseous creatures are immune to this spell, as noted above. A creature with shape changing abilities such as a doppleganger can revert to its natural form in one round.

Unwilling targets that successfully save against Polymorph are not affected. The spell is permanent until dispelled or the creature is slain, at which time the target reverts to his or her original form.

:::

::: {.callout-note icon=false collapse=true}
 
## Polymorph Self
 
Range: self

Magic User 4

Duration: 1 hour/level

This spell allows the caster to change into another form of living creature. The assumed form can’t have more hit dice than the caster's level. The caster can’t assume an incorporeal or gaseous form. If slain, the caster reverts to his or her original form.

The caster gains the physical capabilities and statistics of the new form but retains his or her own mental abilities. He or she also gains all physical attacks possessed by the form but does not gain any special, supernatural or spell-like abilities. Dragon breath is a special ability, for instance, so were the caster to assume the form of a dragon he or she could use the dragon's normal claw, bite, and tail swipe attacks, but not the dragon's breath.

The caster can remain transformed up to one hour per level of ability, or may choose to end the spell whenever he or she desires (up to one hour per level, of course).

:::

::: {.callout-note icon=false collapse=true}
 
## Remove Curse*
 
Range: 30'

Cleric 3, Magic-User 4

Duration: instantaneous

Remove curse instantaneously removes all curses on an object or a creature. Remove curse does not remove the curse from a cursed shield, weapon, or suit of armor, although the spell typically enables the creature afflicted with any such cursed item to remove and get rid of it. Certain special curses may not be countered by this spell or may be removed only by a caster of a certain level.

The reverse of this spell, **bestow curse**, allows the caster to place a curse on the subject. A save vs. Spells is allowed to resist. The caster must choose one of the following three effects:

--4 decrease to an ability score (minimum 1).

--4 penalty on attack rolls and saves.

Each round of combat, the target has a 50% chance to act normally; otherwise, it takes no action.

The caster may also invent his or her own curse, but it should be no more powerful than those described above. The curse thus bestowed cannot be dispelled, but it can be removed with a **remove curse** spell.

:::

::: {.callout-note icon=false collapse=true}
 
## Wall of Fire
 
Range: 180'

Cleric 5, Magic-User 4

Duration: 1 round/level

(or special)

An immobile, blazing curtain of shimmering violet fire springs into existence. One side of the wall, selected by the caster, sends forth waves of heat, dealing 2d4 points of fire damage to creatures within 10 feet and 1d4 points of fire damage to those beyond 10 feet but within 20 feet. The wall deals this damage when it appears and on the caster's turn each round to all creatures in the area. In addition, the wall deals 2d6 points +1 point per caster level of fire damage to any creature passing through it. The wall deals double damage to undead creatures.

The wall is either a sheet of flame up to 20' in length per caster level, or a ring with a radius up to 5' per caster level. The caster may choose to make the wall smaller if desired. The wall may be up to 20' tall (as desired by the caster and/or constrained by the ceiling).

If the caster evokes the wall so that it appears where creatures are, each creature takes damage as if passing through the wall; a save vs. Spells is allowed, with success indicating that damage is rolled as if the creature is within 10' of the wall.

The caster may choose to maintain the spell indefinitely (within reasonable limits of endurance) by concentration, or may cast it with the standard duration of 1 round per level, at his or her option.

:::

::: {.callout-note icon=false collapse=true}
 
## Wizard Eye
 
Range: 240'

Magic User 4

Duration: 6 turns

With this spell the caster creates an invisible magical “eye” through which he or she can see. The eye has Darkvision, but otherwise sees exactly as the caster would. It can be created in any place the caster can see, up to a range of 240' away, and thereafter can move at a rate of 40' per round as directed by the caster. The eye will not move more than 240' feet away from the caster under any circumstances. The eye cannot pass through solid objects, but as it is exactly the size of a normal human's eye, it can pass through holes as small as 1 inch in diameter. The caster must concentrate to use the eye.

:::

:::

<!-- ---------------------------------------- -->

::: {.callout-tip icon=false collapse=true}

# Level 5, Magic User

::: {.callout-note icon=false collapse=true}
 
## Animate Dead
 
Range: touch

Cleric 4, Magic-User 5

Duration: special

This spell turns the bones or bodies of dead creatures into undead skeletons or zombies that follow the caster's spoken commands. They remain animated until they are destroyed. The caster may animate a number of hit dice of undead equal to twice his or her caster level, and no more. Animated skeletons have hit dice equal to the number the creature had in life; for skeletons of humans or demi-humans, this means one hit die, regardless of the character level of the deceased. Zombies have one more hit die than the creature had in life. An animated skeleton can be created only from a mostly intact skeleton; a zombie can be created only from a mostly intact corpse. The caster must touch the remains to be animated. No character may normally control more hit dice of undead than 4 times his or her level, regardless of how many times this spell is cast.

:::

::: {.callout-note icon=false collapse=true}
 
## Cloudkill
 
Range: 100'+10'/level

Magic User 5

Duration: 6 rounds/level

This spell creates a 20'x20'x20' cloud of poison gas which moves at a rate of 10' per round under the control of the caster (so long as he or she concentrates on it). The gas kills outright any creatures of 3 or fewer hit dice or levels it comes in contact with; creatures having 4 or more hit dice or levels must save vs. Poison or die. The cloud persists for the entire duration even if the caster ceases to concentrate upon it.

:::

::: {.callout-note icon=false collapse=true}
 
## Conjure Elemental
 
Range: 240'

Magic User 5

Duration: special

A portal to one of the Elemental Planes of Air, Earth, Fire, or Water is opened, allowing the Magic-User to summon an elemental from that plane. At most one elemental of each type may be summoned by the caster in a given day. Once the elemental appears, it serves the conjurer indefinitely, provided the caster concentrates on nothing but controlling the creature; spell casting, combat, or movement over half the normal rate results in loss of concentration. The conjurer, while in control of an elemental, can dismiss it to its native plane at will (doing so on his or her Initiative if in combat). If the Magic-User loses concentration, control of the summoned Elemental is lost and cannot be regained. The creature then seeks to attack the conjurer and all others in its path. Only **dispel magic** or **dispel evil** will banish the elemental once control has been lost. An elemental may, of course, choose to return to its home plane on its own; such creatures will not choose to remain on the material plane for long.

:::

::: {.callout-note icon=false collapse=true}
 
## Feeblemind
 
Range: 180'

Magic User 5

Duration: permanent

If the target creature fails a saving throw vs. Spells, its Intelligence and Charisma scores each drop to 1. The affected creature is unable to cast spells, understand language, or communicate coherently. The victim does remember who its friends are and can follow and protect them from harm. The subject remains in this state until a **heal** spell is used to cancel the effect. A target creature that can cast Magic-User spells suffers a penalty of -4 on its saving throw against this spell.

:::

::: {.callout-note icon=false collapse=true}
 
## Hold Monster
 
This spell functions like **hold person**, except that it affects any living creature that fails its save vs. Spells.

:::

::: {.callout-note icon=false collapse=true}
 
## Magic Jar
 
Range: 60'

Magic User 5

Duration: special

By casting magic jar, the caster places his or her soul in a gem or large crystal within spell range (known as the magic jar), leaving the body lifeless. The caster may then attempt to take control of a nearby living creature within spell range, forcing its soul into the magic jar. The caster may move back to the jar (thereby returning the trapped soul to its body) and attempt to possess another body. The spell ends when the caster's soul returns to his or her own body, leaving the receptacle empty.

To cast the spell, the magic jar must be within spell range and the caster must know where it is, though he or she does not need to be able to see it. When the caster transfers his or her soul upon casting, the caster's body is, as near as anyone can tell, dead, but does not undergo decay as a normal dead body would.

Possession of a creature by means of this spell is blocked by **protection from evil** or a similar ward. The subject is allowed a save vs. Spells to resist. Failure to take over the host leaves the caster's life force in the magic jar, and that target creature is immune to further attempts for the duration of the spell.

If the caster is successful, his or her life force occupies the host body, and the host's life force is imprisoned in the magic jar. The caster keeps his or her Intelligence, Wisdom, Charisma, level, class, attack bonus, saving throws, and mental abilities (including spellcasting ability). The body retains its Strength, Dexterity, Constitution, hit points, and natural abilities. A body with extra limbs does not allow the caster to make more attacks than normal. The caster does not have access to any extraordinary or supernatural abilities of the body.

If the caster's spirit is in the magic jar, and the jar is broken (whether by **dispel magic** or physical damage): If the jar is in range of the caster's body, the caster's spirit returns to its body. Otherwise, the caster's spirit departs (the caster dies). In either case, the spell ends.

If the caster's spirit is driven from the host body by **dispel evil**: If the magic jar is in range of the host body, the caster's spirit returns to the jar, and the host's spirit returns to its body. The caster will not be able to possess the same host again for the remaining duration of the spell. If the magic jar is not in range of the host body, the caster's spirit departs, the host's spirit is freed from the jar (and departs), and the host's body dies.

If the host's spirit is in the magic jar, and the jar is broken: If the jar is in range of the host's body, the caster's spirit departs, the host's spirit returns to its body, and the spell ends. Otherwise, the host's spirit departs, and the caster's spirit is stranded in the host body. Note here that the spell has not ended. **Dispel evil** can still be used to drive the caster's spirit from the body, which departs as noted, ending the spell.

In any case where the spell ends with the caster's body unoccupied by a spirit, that body does truly die.

:::

::: {.callout-note icon=false collapse=true}
 
## Passwall
 
Range: 30'

Magic User 5

Duration: 3 turns

Passwall creates a passage through wooden, plaster, or stone walls, but not through metal or other harder materials. The passage is up to 10 feet deep plus an additional 10 feet deep per three caster levels above 9th (20 feet at 12th, 30 feet deep at 15th, 40 feet deep at 18th). If the wall’s thickness is more than the depth of the passage created, then a single passwall simply makes a niche or short tunnel. Several passwall spells can then form a continuing passage to breach very thick walls. When passwall ends (due to duration, **dispel magic**, or caster's choice), creatures within the passage are ejected out the nearest exit.

:::

::: {.callout-note icon=false collapse=true}
 
## Telekinesis
 
Range: self

Magic User 5

Duration: 3 turns

This spell permits the caster to move objects or creatures by concentration alone. An object weighing no more than 50 pounds per caster level can be moved up to 20 feet per round. A creature can negate the effect on itself or an object it holds or has on its body with a successful save vs. Death Ray. In order to use this power, the caster must maintain concentration, moving no more than normal movement (no running), making no attacks and casting no spells. If concentration is lost (whether intentional or not), the power may be used again on the next round, but the subject of the effect is allowed a new saving throw.

:::

::: {.callout-note icon=false collapse=true}
 
## Teleport
 
Range: self

Magic User 5

Duration: instantaneous

This spell instantly transports the caster to a designated destination, which may be as distant as 100 miles per caster level. Interplanar travel is not possible. The caster can bring along objects or creatures, not to exceed 300 pounds plus 100 pounds per level above 10th. The caster must be in contact with all objects and/or creatures to be transported (although creatures to be transported may be in contact with one another, with at least one of those creatures in contact with the caster). Unwilling creatures are allowed a saving throw vs. Spells to resist the spell, and the caster may need to make an attack roll to make contact with such a creature. Likewise, a successful save vs. Spells will prevent items in a creature's possession from being teleported.

The caster must have some clear idea of the location and layout of the destination. The clearer the mental image, the more likely it is that the teleportation will work. Areas of strong magical energy may make teleportation more hazardous or even impossible.

To determine the results of this spell, roll d% and consult the table below. Below the table is an explanation of the terms used.

| Familiarity | On Target | Off Target | Similar Area | Mishap |
|-----|-----|-----|-----|----|
| Very familiar | 01--97 | 98--99 | 100 | -- |
| Studied carefully | 01--94 | 95--97 | 98--99 | 100 |
| Seen casually | 01--88 | 89--94 | 95--98 | 99--100 |
| Viewed once | 01--76 | 77--88 | 89--96 | 97--100 |
| False destination | -- | -- | 81--92 | 93--100 |

Familiarity: "Very familiar" is a place where the caster has been very often and feels at home. "Studied carefully" is a place the caster knows well, either because it can currently be seen, the caster has been there often, or other means (such as scrying) have been used to study the place for at least one hour. "Seen casually" is a place that the caster has seen more than once but with which he or she is not very familiar. "Viewed once" is a place that the caster has seen once, possibly using magic.

"False destination" is a place that does not truly exist or if the caster is teleporting to an otherwise familiar location that no longer exists as such or has been so completely altered as to no longer be familiar. When rolling on this row, use 1d20+80.

On Target: The caster appears exactly where desired.

Off Target: The caster appears safely a random distance away from the destination in a random direction. Distance off target is 1d10x1d10% of the distance that was to be traveled. The direction off target is determined randomly.

Similar Area: The caster winds up in an area that's visually or thematically similar to the target area. This means that the caster appears in the closest similar place within range. If no such area exists within the spell's range, the spell simply fails instead.

Mishap: The caster and anyone else teleporting with the caster have gotten "scrambled." Each takes 1d10 points of damage; then reroll on the chart to see where they wind up. For these rerolls, roll 1d20+80. Each time "Mishap" comes up, the characters take more damage and must reroll.

:::

::: {.callout-note icon=false collapse=true}
 
## Wall of Stone
 
Range: 15' per level

Magic User 5

Duration: permanent

This spell creates a wall of rock that merges into adjoining rock surfaces. The wall is composed of up to one 10'x10' square section, 1' thick, per caster level. The caster can double the wall's area by halving its thickness. The wall cannot be conjured so that it occupies the same space as a creature or another object.

The caster can create a wall of stone in almost any shape he or she desires. The wall created need not be vertical, nor rest upon any firm foundation; however, it must merge with and be solidly supported by existing stone. It can be used to bridge a chasm, for instance, or as a ramp. For this use, if the span is more than 20 feet, the wall must be arched and buttressed, reducing the spell's area by half. The wall can also be crudely shaped to create crenelations, battlements, and so forth by similarly reducing the area.

Like any other stone wall, this one can be destroyed by a **disintegrate** spell or by normal means such as breaking and chipping.

It is possible, but difficult, to trap mobile opponents within or under a wall of stone, provided the wall is shaped so it can hold the creatures. Creatures can avoid entrapment with successful saves vs. Death Ray.

:::

:::

<!-- ------------------------------------ -->

::: {.callout-tip icon=false collapse=true}

# Level 6, Magic User

::: {.callout-note icon=false collapse=true}
 
## Anti-Magic Shell
 
Anti-Magic Shell
Range: 10' radius

Magic User 6

Duration: 1 turn/level

Within a 10' radius around the caster, all magic is negated for the full duration of the spell. Magical attacks will not affect the caster, magic items and spells within the radius are suppressed, and the caster cannot perform further magic until the spell has expired.

:::

::: {.callout-note icon=false collapse=true}
 
## Death Spell
 
Range: 240'

Magic User 6

Duration: instantaneous

This spell will kill 3d12 hit dice or levels of creatures in a 30' radius sphere centered wherever the caster wishes (within the range limit). Excess levels of effectiveness are lost. Each creature affected is allowed to save vs. Death Ray; those that fail the save die immediately. Creatures of 8 or more hit dice or levels are immune to the spell, as are undead monsters, golems, and any other “creature” that is not truly alive.

:::

::: {.callout-note icon=false collapse=true}
 
## Disintegrate
 
Range: 60'

Magic User 6

Duration: instantaneous

This spell causes a thin, green ray to spring from the caster's pointing finger. Any single creature or object (up to a 10x10x10 foot cube of material) is entirely disintegrated, leaving behind only a trace of fine dust. A disintegrated creature’s equipment is unaffected.

A creature that makes a successful save vs. Spells is unaffected. The ray can target only one creature per casting, if that target saves, the spell is wasted.

:::

::: {.callout-note icon=false collapse=true}
 
## Flesh to Stone*
 
Range: 30'/level

Magic User 6

Duration: permanent

This spell causes the subject, along with all its carried gear, to turn into a mindless, inert statue. A saving throw vs. Petrification is allowed to resist the spell. If the statue resulting from this spell is broken or damaged, the subject (if ever returned to its original state) suffers equivalent damage or deformities. Only creatures made of flesh are affected by this spell.

The reverse spell, **stone to flesh**, acts as a counterspell for **flesh to stone**, restoring the creature just as it was when it was petrified. It does nothing if applied to stone that is not the result of **flesh to stone** or similar petrification effects (such as a medusa's gaze).

:::

::: {.callout-note icon=false collapse=true}
 
## Geas*
 
Range: 5' per level

Magic User 6

Duration: special

Geas places a magical command on a creature to carry out some service or to refrain from some action or course of activity, as desired by the caster. The target creature must be able to understand the caster for this spell to take effect. While a geas cannot compel a creature to kill itself or perform acts that would result in certain death, it can cause almost any other course of activity.

A saving throw vs. Spells will allow an unwilling target to resist a geas when it is first cast. However, the target may choose to accept the geas, typically as part of a bargain with the caster to perform some service.

The geased creature must follow the given instructions until the geas is completed, no matter how long it takes.

If the instructions involve some open-ended task that the recipient cannot complete through his or her own actions, the spell remains in effect for a maximum of one day per caster level. A clever recipient can subvert some instructions, at the GM's discretion.

For every 24 hours that the subject chooses not to obey the geas (or is prevented from obeying it), it suffers a --2 penalty to each of its ability scores, up to a total of --8. No ability score can be reduced to less than 3 by this effect. The ability score penalties are removed 24 hours after the subject resumes obeying the geas.

A geas (and all effects thereof) can be ended by a **remove curse** spell, or by a **wish**, or by the reverse of this spell. **Dispel magic** does not affect a geas.

:::

::: {.callout-note icon=false collapse=true}
 
## Invisible Stalker
 
Range: 0

Magic User 6

Duration: special

The caster summons an **invisible stalker** to do his or her bidding (see the **Monsters** section, below, for details). The spell persists until **dispel evil** is cast on the creature, it is slain, or the task is fulfilled. The GM is advised to review the monster entry for the invisible stalker when this spell is used, as they may not always be reliable servants.

:::

::: {.callout-note icon=false collapse=true}
 
## Lower Water
 
Range: 360'

Magic User 6

Duration: 1 turn/level

This spell causes water or similar liquid to reduce its depth by as much as 2 feet per caster level (to a minimum depth of 1 inch). The water is lowered within a more or less square-shaped depression whose sides are up to 10 feet long per caster level. In extremely large and deep bodies of water, such as a deep ocean, the spell creates a whirlpool that sweeps ships and similar craft downward, putting them at risk and rendering them unable to leave by normal movement for the duration of the spell. When cast on water elementals and other water-based creatures, this spell acts as a **slow** spell (the reverse of **haste**); a save vs. Spells is allowed, with success negating the effect. The spell has no effect on other creatures.

:::

::: {.callout-note icon=false collapse=true}
 
## Projected Image
 
Range: 240'

Magic User 6

Duration: 6 turns

This spell creates a quasi-real, illusory version of the caster. The intangible projected image looks, sounds, and smells like the caster, in addition to mimicking gestures and actions (including speech). Any further spells cast seem to originate from the illusion, not the actual caster. A line of sight between the caster and his or her illusory self must be maintained or the spell ends. **Dimension door**, **teleport**, or any similar spell that breaks the line of sight dispels the image, as does the illusionary caster being struck in combat. Note that this spell grants no special sensory powers to the caster; for example, if the illusory self is positioned so as to be able to see something the caster can't directly see, the caster does not see it. Also, all spell ranges are still figured from the caster's actual position, not the illusory self's position.

:::

::: {.callout-note icon=false collapse=true}
 
## Reincarnate
 
Range: touch

Magic User 6

Duration: instantaneous

With this spell, the caster brings back a dead character (or humanoid creature) in another body, provided that its death occurred no more than one week before the casting of the spell and the subject's soul is free and willing to return. If the subject's soul is not willing to return, the spell does not work.

Roll on the following table to determine what sort of creature the character becomes:

| d% | Incarnation |
|-----|------|
| 01--02 | Bugbear |
| 03--17 | Dwarf |
| 18--28 | Elf |
| 29 | Gnoll |
| 30--39 | Gnome |
| 40--44 | Goblin |
| 45--63 | Halfling |
| 64--88 | Human |
| 89--92 | Kobold |
| 93 | Lizard Man |
| 94--98 | Orc |
| 99 | Troglodyte |
| 100 | Other (GM's choice) |

Since the dead character is returning in a new body, all physical ills and afflictions are repaired. The condition of the remains is not a factor. So long as some small portion of the character's body still exists, it can be reincarnated, but the portion receiving the spell must have been part of the character's body at the time of death. The magic of the spell creates an entirely new young adult body for the soul to inhabit from the natural elements at hand. This process takes one hour to complete. When the body is ready, the subject is reincarnated.

A reincarnated character recalls the majority of its former life and form. Its class is unchanged, as are the character's Intelligence, Wisdom, and Charisma. Strength, Dexterity, and Constitution scores should be rerolled. (If the character's ability scores are outside the allowable range for the new form, they should be adjusted up or down by the GM as needed.) The subject's level (or Hit Dice) is reduced by 1; this is a real reduction, not a negative level, and is not subject to magical **restoration**. Roll one hit die and subtract the total from the character's original hit point total; this is the new form's hit points. If the subject was 1^st^ level, instead of a hit point reduction, its new Constitution score is reduced by 2.

A character that has been turned into an undead creature or killed by a death effect can't be returned to life by this spell. Constructs, elementals, and undead creatures can't be reincarnated. The spell cannot bring back a creature who has died of old age.

The reincarnated creature gains all abilities associated with its new form, including forms of movement and speeds, natural armor, natural attacks, extraordinary abilities, and the like, but it doesn't automatically speak the language of the new form.

:::

::: {.callout-note icon=false collapse=true}
 
## Wall of Iron
 
Range: 90'

Magic User 6

Duration: permanent

This spell causes a flat, vertical iron wall to spring into being. The wall is composed of up to one 10'x10' square section, one inch thick, per caster level. If the caster so desires, the wall can bond itself into any surrounding nonliving material if its area is sufficient to do so. The wall cannot be conjured so that it occupies the same space as a creature or another object. The wall must always be a flat plane, though the edges can be shaped to fit the available space, and it must always be conjured in contact with the ground.

The caster can increase the thickness of the wall with a proportionate reduction in the area; for example, doubling the thickness halves the area. The wall may not be made less than one inch thick. The caster can create the wall vertically resting on a flat surface but not attached to the surface, so that it can be tipped over to fall on and crush creatures beneath it. The wall is 50% likely to tip in either direction if left un-pushed. Creatures can push the wall in one direction rather than letting it fall randomly. A creature with 13 Strength (or 4 or more Hit Dice) can push the wall over; or several creatures can work together to do so. (If the optional Ability Roll rule is being used, a Strength roll at -3 is sufficient to topple the wall.) Creatures with room to flee the falling wall may do so by making successful saves vs. Death Ray (with Dexterity bonus added). Any creature of Ogre-size or smaller that fails the save takes 10d6 points of damage. The wall cannot crush larger creatures.

Like any iron wall, this wall is subject to rust, perforation, and other natural phenomena.

:::

:::