# Vehicles

The following tables give details of various land and sea vehicles. Game Masters should feel free to create their own vehicles, in which case the table can be used for guidance. Some of the statistics given below are explained in detail later.

## Land Transportation

::: {.column-screen-inset-right}

| Vehicle | Length x width* | Weight | Cargo | Movement | Hardness / HP | Cost (gp) |
|---|---|---|---|---|---|---|
| Chariot | 15' x 6' | 300 | 750 lbs | 60' (10') | 10 / 10 | 400 |
| Coach | 30' x 8' | 1,000 | 2,000 lbs | 40' (15') | 6 / 12 | 1,500 |
| Wagon | 35' x 8' | 2,000 | 4,000 lbs | 20' (15') | 6 / 16 | 500 |


:::

*Includes hitched horses or mules.

## Water Transportation

::: {.column-screen-inset-right}

| Vehicle | Length x Width | Cargo | Crew | Movement | Miles/Day | Hardness / HP | Cost (gp) |
|---|---|---|---|---|---|---|---|
| Canoe | 15' x 4' | ½ ton | 1 | 40' | (5') | 30 | 4 / 4 | 50 |
| Caravel | 55' x 15' | 75 tons | 10 | 20' | (20') | 42 | 8 / 75 | 10,000 |
| Carrack | 60' x 20' | 135 tons | 20 | 30' | (30') | 48 | 10 / 120 | 20,000 |
| Galley, Small | 100' x 15' | 210 tons | 90 | 20' | (20') | 36 / 24 | 8 / 75 | 15,000 |
| Galley, Large | 120' x 20' | 375 tons | 160 | 30' | (25') | 42 / 24 | 10 / 120 | 30,000 |
| Longship | 110' x 15' | 10 tons | 70 | 30' | (25') | 42 / 24 | 9 / 110 | 25,000 |
| Raft/Barge | per 10' x 10' | 1 ton | 2 | 40' | (10') | 18 | 6 / 12 | 100 |
| Riverboat | 50' x 20' | 50 tons | 10 | 20' | (20') | 30 | 8 / 30 | 3,500 |
| Rowboat | 15' x 6' | 1 ton | 1 | 30' | (10') | 24 | 6 / 8 | 60 |
| Sailboat | 40' x 8' | 5 tons | 1 | 40' | (15') | 36 | 7 / 20 | 2,000 |


::: 

## Notes Regarding Vehicles

The** Crew** figure given reflects the minimum number of sailors and/or rowers needed to operate the ship. Officers are not counted among these numbers, and of course it is always a good idea to hire extra sailors and/or rowers to ensure that any casualties will not slow down the ship.

**Cargo** for wagons is given in pounds, while for ships it is given in tons. If the ship sails night and day, each passenger requires living space equivalent to one ton of cargo; in addition, provisions for one man for one month occupy 1/10 of a ton of space.

**Movement** is given separately here in feet (yards, actually; see **Time and Scale** in **Part 4: The Adventure** for an explanation) as well as miles per day. The encounter movement of ships is not directly related to the long-distance travel rate, since the crew must work hard to make the ship move quickly in combat, and this level of effort cannot be maintained day and night.

The parenthesized figure represents maneuverability; see **Maneuverability** in **Part 5: The Encounter** for details.

See **Attacking a Vehicle,** also in the **Encounter** section, for details on the **Hardness** and **HP** statistics.

A **chariot** requires a single horse, generally a warhorse, to pull it. Both **coaches** and** wagons** require at least a pair of draft horses to pull them.

A **caravel** is a highly maneuverable sailing ship with two or three masts. Though superficially similar to the larger carrack, caravels are capable of sailing up rivers, a task for which the larger ship is ill suited.

A **carrack** is a large, ocean-going sailing ship with three or four masts.

**Galleys** are equipped with both sails and oars; the second listed movement rate for galleys is the rowing speed. A small galley will have around 20 rows of oars, with each oar pulled by two men (for a total of 80 rowers) while a large galley will have around 35 rows of oars (for a total of 140 rowers). Galleys are generally much more maneuverable than sailing ships such as the carrack or caravel, and may be outfitted with rams.

The **longship** commonly used by northern raiders is very similar to the large galley. However, where more civilized nations have specialist rowers, sailors, and marines, the crew of a longship is more generalized; most crewmen will be qualified for all of these tasks.

## Siege Engines

These are weapons used to attack strongholds, or sometimes ships. Their cost may be up to twice as high in a remote location. A siege engine that throws missiles (a ballista, onager or trebuchet) must have a trained artillerist to fire it; this is the character who makes the attack rolls for the weapon. Missile-throwing engines have attack penalties, detailed below. Note: siege engines are not generally usable against individuals or monsters; the GM may make exceptions for very large monsters like giants or dragons.


::: {.column-screen-inset-right}

| Weapon | Cost | Rate of Fire | Attack Penalty | Damage | Short Range (+1) | Medium Range (+0) | Long Range (-2) |
|---|---|---|---|---|---|---|---|
| Ballista | 100 gp | 1/4 | -3 | 2d8 | 50' | 100' | 150' |
| Battering Ram | 200 gp | 1/3 | +0 | 2d8 | N/A | N/A | N/A |
| Onager | 300 gp | 1/6 | -6 | 2d12 | 100' | 200' | 300' |
| Trebuchet | 400 gp | 1/10 | -8 | 3d10 | N/A | 300' | 400' |

::: 

**Ballista:** This is effectively a very large crossbow that may fire a spear-like bolt or a large stone. It is usually mounted on a tripod or wagon, but may also be mounted on a ship. When firing bolts, a ballista cannot damage brick or stone. A ballista requires a crew of three to operate.

**Battering Ram:** These are usually operated under a sow (a sort of portable roof). They require a crew of eight or more.

**Onager:** This weapon throws a stone with a fairly flat trajectory. An onager requires a crew of four to operate.

**Trebuchet:** This mighty weapon uses a counterweight to fling a stone on a high, arcing path. It cannot fire at targets within 200 yards. If it is aimed at a target that is more than 20' higher than the weapon, there is an additional --2 attack penalty. A trebuchet requires a crew of eight to operate.

